{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"adContent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdContent","preciseIdentifier":"c:@M@TAMediaAdsFramework@objc(cs)TADNativeAdContent","text":"TADNativeAdContent"},{"kind":"text","text":"! { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/tamediaadsframework\/tadnativead\/adcontent"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/tamediaadsframework\/tadnativead\/adcontent"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAd\/adContent","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"廣告內容，使用此物件來設定原生廣告視圖的屬性，以呈現廣告。"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"adContent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TADNativeAdContent","preciseIdentifier":"c:@M@TAMediaAdsFramework@objc(cs)TADNativeAdContent"},{"kind":"text","text":"!"}],"title":"adContent","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)TADNativeAd(py)adContent","modules":[{"name":"TAMediaAdsFramework"}],"navigatorTitle":[{"kind":"identifier","text":"adContent"}]},"hierarchy":{"paths":[["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAd"]]},"references":{"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework":{"role":"collection","title":"TAMediaAdsFramework","abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","kind":"symbol","type":"topic","url":"\/documentation\/tamediaadsframework"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADNativeAdContent":{"role":"symbol","title":"TADNativeAdContent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADNativeAdContent"}],"abstract":[{"type":"text","text":"封裝 native 廣告的物件"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdContent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TADNativeAdContent"}],"url":"\/documentation\/tamediaadsframework\/tadnativeadcontent"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADNativeAd":{"role":"symbol","title":"TADNativeAd","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADNativeAd"}],"abstract":[{"type":"text","text":"Native廣告的物件。"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAd","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TADNativeAd"}],"url":"\/documentation\/tamediaadsframework\/tadnativead"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADNativeAd/adContent":{"role":"symbol","title":"adContent","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"adContent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TADNativeAdContent","preciseIdentifier":"c:@M@TAMediaAdsFramework@objc(cs)TADNativeAdContent"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"廣告內容，使用此物件來設定原生廣告視圖的屬性，以呈現廣告。"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAd\/adContent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"adContent"}],"url":"\/documentation\/tamediaadsframework\/tadnativead\/adcontent"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"adContent"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"adContent"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdContent","preciseIdentifier":"c:@M@TAMediaAdsFramework@objc(cs)TADNativeAdContent","text":"TADNativeAdContent"},{"kind":"text","text":" *"},{"kind":"identifier","text":"adContent"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAdContent\/title","value":"TADNativeAdContent"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAdContent\/fragments","value":[{"kind":"identifier","text":"TADNativeAdContent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAd\/title","value":"TADNativeAd"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAd\/fragments","value":[{"kind":"identifier","text":"TADNativeAd"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAd~1adContent\/title","value":"adContent"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAd~1adContent\/fragments","value":[{"kind":"identifier","text":"adContent"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}