{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"impressionOwner"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDOwner","preciseIdentifier":"c:@E@OMIDOwner","text":"OMIDOwner"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/tamediaadsframework\/omidtaiwanmobileadsessionconfiguration\/impressionowner"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/tamediaadsframework\/omidtaiwanmobileadsessionconfiguration\/impressionowner"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileAdSessionConfiguration\/impressionOwner","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"impressionOwner"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"OMIDOwner","preciseIdentifier":"c:@E@OMIDOwner"}],"title":"impressionOwner","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)OMIDTaiwanmobileAdSessionConfiguration(py)impressionOwner","modules":[{"name":"TAMediaAdsFramework"}],"navigatorTitle":[{"kind":"identifier","text":"impressionOwner"}]},"hierarchy":{"paths":[["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileAdSessionConfiguration"]]},"references":{"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework":{"role":"collection","title":"TAMediaAdsFramework","abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","kind":"symbol","type":"topic","url":"\/documentation\/tamediaadsframework"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/OMIDOwner":{"role":"symbol","title":"OMIDOwner","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"OMIDOwner"}],"abstract":[{"type":"text","text":"Identifies which integration layer is responsible for sending certain events."}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDOwner","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OMIDOwner"}],"url":"\/documentation\/tamediaadsframework\/omidowner"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/OMIDTaiwanmobileAdSessionConfiguration":{"role":"symbol","title":"OMIDTaiwanmobileAdSessionConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OMIDTaiwanmobileAdSessionConfiguration"}],"abstract":[{"type":"text","text":"The ad session configuration supplies the owner for both the impression and video events."},{"type":"text","text":" "},{"type":"text","text":"The OM SDK JS service will use this information to help identify where the source of these"},{"type":"text","text":" "},{"type":"text","text":"events is expected to be received."}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileAdSessionConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OMIDTaiwanmobileAdSessionConfiguration"}],"url":"\/documentation\/tamediaadsframework\/omidtaiwanmobileadsessionconfiguration"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/OMIDTaiwanmobileAdSessionConfiguration/impressionOwner":{"role":"symbol","title":"impressionOwner","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"impressionOwner"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"OMIDOwner","preciseIdentifier":"c:@E@OMIDOwner"}],"abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileAdSessionConfiguration\/impressionOwner","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"impressionOwner"}],"url":"\/documentation\/tamediaadsframework\/omidtaiwanmobileadsessionconfiguration\/impressionowner"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"impressionOwner"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"impressionOwner"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"atomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDOwner","preciseIdentifier":"c:@E@OMIDOwner","text":"OMIDOwner"},{"kind":"identifier","text":"impressionOwner"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDOwner\/title","value":"OMIDOwner"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDOwner\/fragments","value":[{"kind":"identifier","text":"OMIDOwner"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDTaiwanmobileAdSessionConfiguration\/title","value":"OMIDTaiwanmobileAdSessionConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDTaiwanmobileAdSessionConfiguration\/fragments","value":[{"kind":"identifier","text":"OMIDTaiwanmobileAdSessionConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDTaiwanmobileAdSessionConfiguration~1impressionOwner\/title","value":"impressionOwner"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDTaiwanmobileAdSessionConfiguration~1impressionOwner\/fragments","value":[{"kind":"identifier","text":"impressionOwner"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}