{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"testDevices"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]! { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/tamediaadsframework\/tadrequest\/testdevices"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/tamediaadsframework\/tadrequest\/testdevices"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADRequest\/testDevices","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"將設備的 identifierForVendor 添加到此數組中以進行測試。"}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"testDevices"}],"role":"symbol","title":"testDevices","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"testDevices"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]!"}],"symbolKind":"property","externalID":"c:objc(cs)TADRequest(py)testDevices","modules":[{"name":"TAMediaAdsFramework"}],"platforms":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"6.0","deprecated":false}]},"hierarchy":{"paths":[["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADRequest"]]},"references":{"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADRequest":{"role":"symbol","title":"TADRequest","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADRequest"}],"abstract":[{"type":"text","text":"廣告請求的物件，可對其設定可選的參數。"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADRequest","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TADRequest"}],"url":"\/documentation\/tamediaadsframework\/tadrequest"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework":{"role":"collection","title":"TAMediaAdsFramework","abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","kind":"symbol","type":"topic","url":"\/documentation\/tamediaadsframework"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADRequest/testDevices":{"role":"symbol","title":"testDevices","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"testDevices"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]!"}],"abstract":[{"type":"text","text":"將設備的 identifierForVendor 添加到此數組中以進行測試。"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADRequest\/testDevices","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"testDevices"}],"url":"\/documentation\/tamediaadsframework\/tadrequest\/testdevices"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"6.0","deprecated":false}]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"testDevices"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"testDevices"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"retain"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSArray","preciseIdentifier":"c:objc(cs)NSArray"},{"kind":"text","text":" *"},{"kind":"identifier","text":"testDevices"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADRequest\/title","value":"TADRequest"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADRequest\/fragments","value":[{"kind":"identifier","text":"TADRequest"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADRequest~1testDevices\/title","value":"testDevices"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADRequest~1testDevices\/fragments","value":[{"kind":"identifier","text":"testDevices"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}