{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addFriendlyObstruction"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"friendlyObstruction"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"purpose"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDFriendlyObstructionType","preciseIdentifier":"c:@E@OMIDFriendlyObstructionType","text":"OMIDFriendlyObstructionType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"detailedReason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) "},{"kind":"keyword","text":"throws"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This method will have no affect if called after the ad session has finished."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"obvious from the purpose. Can be nil. If not nil, must be 50 characters or less and only contain characers"},{"type":"text","text":" "},{"type":"codeVoice","code":"A-z"},{"type":"text","text":", "},{"type":"codeVoice","code":"0-9"},{"type":"text","text":", or spaces."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"friendlyObstruction has already been added for this session, this method will return NO with no associated"},{"type":"text","text":" "},{"type":"text","text":"error object. However, if one or more arguments are against requirements, it will return NO with an error"},{"type":"text","text":" "},{"type":"text","text":"object assigned."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/tamediaadsframework\/omidtaiwanmobileadsession\/addfriendlyobstruction(_:purpose:detailedreason:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/tamediaadsframework\/omidtaiwanmobileadsession\/addfriendlyobstruction(_:purpose:detailedreason:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileAdSession\/addFriendlyObstruction(_:purpose:detailedReason:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Adds friendly obstruction which should then be excluded from all ad session viewability calculations."},{"type":"text","text":" "},{"type":"text","text":"It also provides a purpose and detailed reason string to pass forward to the measurement vendors."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addFriendlyObstruction"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"purpose"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"OMIDFriendlyObstructionType","preciseIdentifier":"c:@E@OMIDFriendlyObstructionType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"detailedReason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) "},{"kind":"keyword","text":"throws"}],"title":"addFriendlyObstruction(_:purpose:detailedReason:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)OMIDTaiwanmobileAdSession(im)addFriendlyObstruction:purpose:detailedReason:error:","modules":[{"name":"TAMediaAdsFramework"}],"navigatorTitle":[{"kind":"identifier","text":"addFriendlyObstruction:purpose:detailedReason:error:"}]},"hierarchy":{"paths":[["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileAdSession"]]},"references":{"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/OMIDFriendlyObstructionType":{"role":"symbol","title":"OMIDFriendlyObstructionType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"OMIDFriendlyObstructionType"}],"abstract":[{"type":"text","text":"List of allowed friendly obstruction purposes."}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDFriendlyObstructionType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OMIDFriendlyObstructionType"}],"url":"\/documentation\/tamediaadsframework\/omidfriendlyobstructiontype"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/OMIDTaiwanmobileAdSession":{"role":"symbol","title":"OMIDTaiwanmobileAdSession","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OMIDTaiwanmobileAdSession"}],"abstract":[{"type":"text","text":"Ad session API enabling the integration partner to notify OMID of key state relating to viewability calculations."},{"type":"text","text":" "},{"type":"text","text":"In addition to viewability this API will also notify all verification providers of key ad session lifecycle events."}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileAdSession","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OMIDTaiwanmobileAdSession"}],"url":"\/documentation\/tamediaadsframework\/omidtaiwanmobileadsession"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework":{"role":"collection","title":"TAMediaAdsFramework","abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","kind":"symbol","type":"topic","url":"\/documentation\/tamediaadsframework"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/OMIDTaiwanmobileAdSession/addFriendlyObstruction(_:purpose:detailedReason:)":{"role":"symbol","title":"addFriendlyObstruction(_:purpose:detailedReason:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addFriendlyObstruction"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"purpose"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"OMIDFriendlyObstructionType","preciseIdentifier":"c:@E@OMIDFriendlyObstructionType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"detailedReason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) "},{"kind":"keyword","text":"throws"}],"abstract":[{"type":"text","text":"Adds friendly obstruction which should then be excluded from all ad session viewability calculations."},{"type":"text","text":" "},{"type":"text","text":"It also provides a purpose and detailed reason string to pass forward to the measurement vendors."}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileAdSession\/addFriendlyObstruction(_:purpose:detailedReason:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"addFriendlyObstruction:purpose:detailedReason:error:"}],"url":"\/documentation\/tamediaadsframework\/omidtaiwanmobileadsession\/addfriendlyobstruction(_:purpose:detailedreason:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"addFriendlyObstruction:purpose:detailedReason:error:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addFriendlyObstruction:purpose:detailedReason:error:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"addFriendlyObstruction:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"friendlyObstruction"},{"kind":"text","text":" "},{"kind":"identifier","text":"purpose:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDFriendlyObstructionType","preciseIdentifier":"c:@E@OMIDFriendlyObstructionType","text":"OMIDFriendlyObstructionType"},{"kind":"text","text":")"},{"kind":"internalParam","text":"purpose"},{"kind":"text","text":" "},{"kind":"identifier","text":"detailedReason:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"detailedReason"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" * *)"},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDFriendlyObstructionType\/title","value":"OMIDFriendlyObstructionType"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDFriendlyObstructionType\/fragments","value":[{"kind":"identifier","text":"OMIDFriendlyObstructionType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDTaiwanmobileAdSession\/title","value":"OMIDTaiwanmobileAdSession"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDTaiwanmobileAdSession\/fragments","value":[{"kind":"identifier","text":"OMIDTaiwanmobileAdSession"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDTaiwanmobileAdSession~1addFriendlyObstruction(_:purpose:detailedReason:)\/title","value":"addFriendlyObstruction:purpose:detailedReason:error:"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDTaiwanmobileAdSession~1addFriendlyObstruction(_:purpose:detailedReason:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addFriendlyObstruction:purpose:detailedReason:error:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}