{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createTADRequest"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withResponseCode"},{"kind":"text","text":" "},{"kind":"internalParam","text":"responseCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADRequestError","preciseIdentifier":"c:objc(cs)TADRequestError","text":"TADRequestError"},{"kind":"text","text":"!"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/tamediaadsframework\/tadrequesterror\/createtadrequest(withresponsecode:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/tamediaadsframework\/tadrequesterror\/createtadrequest(withresponsecode:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADRequestError\/createTADRequest(withResponseCode:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createTADRequest"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withResponseCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"TADRequestError","preciseIdentifier":"c:objc(cs)TADRequestError"},{"kind":"text","text":"!"}],"title":"createTADRequest(withResponseCode:)","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)TADRequestError(cm)createTADRequestWithResponseCode:","modules":[{"name":"TAMediaAdsFramework"}],"navigatorTitle":[{"kind":"identifier","text":"createTADRequestWithResponseCode:"}]},"hierarchy":{"paths":[["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADRequestError"]]},"references":{"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADRequestError":{"role":"symbol","title":"TADRequestError","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADRequestError"}],"abstract":[{"type":"text","text":"Tamedia中定義的NSError資訊"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADRequestError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TADRequestError"}],"url":"\/documentation\/tamediaadsframework\/tadrequesterror"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework":{"role":"collection","title":"TAMediaAdsFramework","abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","kind":"symbol","type":"topic","url":"\/documentation\/tamediaadsframework"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADRequestError/createTADRequest(withResponseCode:)":{"role":"symbol","title":"createTADRequest(withResponseCode:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createTADRequest"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withResponseCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"TADRequestError","preciseIdentifier":"c:objc(cs)TADRequestError"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADRequestError\/createTADRequest(withResponseCode:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"createTADRequestWithResponseCode:"}],"url":"\/documentation\/tamediaadsframework\/tadrequesterror\/createtadrequest(withresponsecode:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"createTADRequestWithResponseCode:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createTADRequestWithResponseCode:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADRequestError","preciseIdentifier":"c:objc(cs)TADRequestError","text":"TADRequestError"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"createTADRequestWithResponseCode:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":")"},{"kind":"internalParam","text":"responseCode"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADRequestError\/title","value":"TADRequestError"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADRequestError\/fragments","value":[{"kind":"identifier","text":"TADRequestError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADRequestError~1createTADRequest(withResponseCode:)\/title","value":"createTADRequestWithResponseCode:"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADRequestError~1createTADRequest(withResponseCode:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createTADRequestWithResponseCode:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}