{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileAdSessionConfiguration","preciseIdentifier":"c:objc(cs)OMIDTaiwanmobileAdSessionConfiguration","text":"OMIDTaiwanmobileAdSessionConfiguration"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/tamediaadsframework\/omidtaiwanmobileadsession\/configuration"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/tamediaadsframework\/omidtaiwanmobileadsession\/configuration"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileAdSession\/configuration","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The AdSession configuration is used for check owners."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"OMIDTaiwanmobileAdSessionConfiguration","preciseIdentifier":"c:objc(cs)OMIDTaiwanmobileAdSessionConfiguration"}],"title":"configuration","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)OMIDTaiwanmobileAdSession(py)configuration","modules":[{"name":"TAMediaAdsFramework"}],"navigatorTitle":[{"kind":"identifier","text":"configuration"}]},"hierarchy":{"paths":[["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileAdSession"]]},"references":{"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/OMIDTaiwanmobileAdSession":{"role":"symbol","title":"OMIDTaiwanmobileAdSession","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OMIDTaiwanmobileAdSession"}],"abstract":[{"type":"text","text":"Ad session API enabling the integration partner to notify OMID of key state relating to viewability calculations."},{"type":"text","text":" "},{"type":"text","text":"In addition to viewability this API will also notify all verification providers of key ad session lifecycle events."}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileAdSession","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OMIDTaiwanmobileAdSession"}],"url":"\/documentation\/tamediaadsframework\/omidtaiwanmobileadsession"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/OMIDTaiwanmobileAdSessionConfiguration":{"role":"symbol","title":"OMIDTaiwanmobileAdSessionConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OMIDTaiwanmobileAdSessionConfiguration"}],"abstract":[{"type":"text","text":"The ad session configuration supplies the owner for both the impression and video events."},{"type":"text","text":" "},{"type":"text","text":"The OM SDK JS service will use this information to help identify where the source of these"},{"type":"text","text":" "},{"type":"text","text":"events is expected to be received."}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileAdSessionConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OMIDTaiwanmobileAdSessionConfiguration"}],"url":"\/documentation\/tamediaadsframework\/omidtaiwanmobileadsessionconfiguration"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework":{"role":"collection","title":"TAMediaAdsFramework","abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","kind":"symbol","type":"topic","url":"\/documentation\/tamediaadsframework"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/OMIDTaiwanmobileAdSession/configuration":{"role":"symbol","title":"configuration","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"OMIDTaiwanmobileAdSessionConfiguration","preciseIdentifier":"c:objc(cs)OMIDTaiwanmobileAdSessionConfiguration"}],"abstract":[{"type":"text","text":"The AdSession configuration is used for check owners."}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileAdSession\/configuration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"configuration"}],"url":"\/documentation\/tamediaadsframework\/omidtaiwanmobileadsession\/configuration"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"configuration"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"configuration"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileAdSessionConfiguration","preciseIdentifier":"c:objc(cs)OMIDTaiwanmobileAdSessionConfiguration","text":"OMIDTaiwanmobileAdSessionConfiguration"},{"kind":"text","text":" *"},{"kind":"identifier","text":"configuration"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDTaiwanmobileAdSession\/title","value":"OMIDTaiwanmobileAdSession"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDTaiwanmobileAdSession\/fragments","value":[{"kind":"identifier","text":"OMIDTaiwanmobileAdSession"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDTaiwanmobileAdSessionConfiguration\/title","value":"OMIDTaiwanmobileAdSessionConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDTaiwanmobileAdSessionConfiguration\/fragments","value":[{"kind":"identifier","text":"OMIDTaiwanmobileAdSessionConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDTaiwanmobileAdSession~1configuration\/title","value":"configuration"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDTaiwanmobileAdSession~1configuration\/fragments","value":[{"kind":"identifier","text":"configuration"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}