{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileAdSessionConfiguration","preciseIdentifier":"c:objc(cs)OMIDTaiwanmobileAdSessionConfiguration","text":"OMIDTaiwanmobileAdSessionConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"adSessionContext"},{"kind":"text","text":" "},{"kind":"internalParam","text":"context"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileAdSessionContext","preciseIdentifier":"c:objc(cs)OMIDTaiwanmobileAdSessionContext","text":"OMIDTaiwanmobileAdSessionContext"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Note that creating an OMIDAdSession sends a message to the OM SDK JS Service running in the"},{"type":"text","text":" "},{"type":"text","text":"webview.  If the OM SDK JS Service has not loaded before the ad session is created, the"},{"type":"text","text":" "},{"type":"text","text":"message is lost, and the verification scripts will not receive any events."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"To prevent this, the implementation must wait until the webview finishes loading OM SDK"},{"type":"text","text":" "},{"type":"text","text":"JavaScript before creating the OMIDAdSession.  The easiest way is to create the OMIDAdSession"},{"type":"text","text":" "},{"type":"text","text":"in a webview delegate callback (-[WKNavigationDelegate webView:didFinishNavigation:].  Alternatively,"},{"type":"text","text":" "},{"type":"text","text":"if an implementation can receive an HTML5 DOMContentLoaded event from the webview, it can create"},{"type":"text","text":" "},{"type":"text","text":"the OMIDAdSession in a message handler for that event."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/tamediaadsframework\/omidtaiwanmobileadsession\/init(configuration:adsessioncontext:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/tamediaadsframework\/omidtaiwanmobileadsession\/init(configuration:adsessioncontext:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileAdSession\/init(configuration:adSessionContext:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Initializes new ad session supplying the context."}],"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"OMIDTaiwanmobileAdSessionConfiguration","preciseIdentifier":"c:objc(cs)OMIDTaiwanmobileAdSessionConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"adSessionContext"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"OMIDTaiwanmobileAdSessionContext","preciseIdentifier":"c:objc(cs)OMIDTaiwanmobileAdSessionContext"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"title":"init(configuration:adSessionContext:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:objc(cs)OMIDTaiwanmobileAdSession(im)initWithConfiguration:adSessionContext:error:","modules":[{"name":"TAMediaAdsFramework"}],"navigatorTitle":[{"kind":"identifier","text":"initWithConfiguration:adSessionContext:error:"}]},"hierarchy":{"paths":[["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileAdSession"]]},"references":{"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework":{"role":"collection","title":"TAMediaAdsFramework","abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","kind":"symbol","type":"topic","url":"\/documentation\/tamediaadsframework"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/OMIDTaiwanmobileAdSession":{"role":"symbol","title":"OMIDTaiwanmobileAdSession","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OMIDTaiwanmobileAdSession"}],"abstract":[{"type":"text","text":"Ad session API enabling the integration partner to notify OMID of key state relating to viewability calculations."},{"type":"text","text":" "},{"type":"text","text":"In addition to viewability this API will also notify all verification providers of key ad session lifecycle events."}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileAdSession","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OMIDTaiwanmobileAdSession"}],"url":"\/documentation\/tamediaadsframework\/omidtaiwanmobileadsession"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/OMIDTaiwanmobileAdSession/init(configuration:adSessionContext:)":{"role":"symbol","title":"init(configuration:adSessionContext:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"OMIDTaiwanmobileAdSessionConfiguration","preciseIdentifier":"c:objc(cs)OMIDTaiwanmobileAdSessionConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"adSessionContext"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"OMIDTaiwanmobileAdSessionContext","preciseIdentifier":"c:objc(cs)OMIDTaiwanmobileAdSessionContext"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[{"type":"text","text":"Initializes new ad session supplying the context."}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileAdSession\/init(configuration:adSessionContext:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithConfiguration:adSessionContext:error:"}],"url":"\/documentation\/tamediaadsframework\/omidtaiwanmobileadsession\/init(configuration:adsessioncontext:)"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/OMIDTaiwanmobileAdSessionConfiguration":{"role":"symbol","title":"OMIDTaiwanmobileAdSessionConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OMIDTaiwanmobileAdSessionConfiguration"}],"abstract":[{"type":"text","text":"The ad session configuration supplies the owner for both the impression and video events."},{"type":"text","text":" "},{"type":"text","text":"The OM SDK JS service will use this information to help identify where the source of these"},{"type":"text","text":" "},{"type":"text","text":"events is expected to be received."}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileAdSessionConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OMIDTaiwanmobileAdSessionConfiguration"}],"url":"\/documentation\/tamediaadsframework\/omidtaiwanmobileadsessionconfiguration"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/OMIDTaiwanmobileAdSessionContext":{"role":"symbol","title":"OMIDTaiwanmobileAdSessionContext","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OMIDTaiwanmobileAdSessionContext"}],"abstract":[{"type":"text","text":"Provides the ad session with details of the partner and whether to an HTML,"},{"type":"text","text":" "},{"type":"text","text":"JavaScript, or native session."}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileAdSessionContext","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OMIDTaiwanmobileAdSessionContext"}],"url":"\/documentation\/tamediaadsframework\/omidtaiwanmobileadsessioncontext"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithConfiguration:adSessionContext:error:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithConfiguration:adSessionContext:error:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithConfiguration:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileAdSessionConfiguration","preciseIdentifier":"c:objc(cs)OMIDTaiwanmobileAdSessionConfiguration","text":"OMIDTaiwanmobileAdSessionConfiguration"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"configuration"},{"kind":"text","text":" "},{"kind":"identifier","text":"adSessionContext:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileAdSessionContext","preciseIdentifier":"c:objc(cs)OMIDTaiwanmobileAdSessionContext","text":"OMIDTaiwanmobileAdSessionContext"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"context"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" * *)"},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDTaiwanmobileAdSession\/title","value":"OMIDTaiwanmobileAdSession"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDTaiwanmobileAdSession\/fragments","value":[{"kind":"identifier","text":"OMIDTaiwanmobileAdSession"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDTaiwanmobileAdSession~1init(configuration:adSessionContext:)\/title","value":"initWithConfiguration:adSessionContext:error:"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDTaiwanmobileAdSession~1init(configuration:adSessionContext:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithConfiguration:adSessionContext:error:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDTaiwanmobileAdSessionConfiguration\/title","value":"OMIDTaiwanmobileAdSessionConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDTaiwanmobileAdSessionConfiguration\/fragments","value":[{"kind":"identifier","text":"OMIDTaiwanmobileAdSessionConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDTaiwanmobileAdSessionContext\/title","value":"OMIDTaiwanmobileAdSessionContext"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDTaiwanmobileAdSessionContext\/fragments","value":[{"kind":"identifier","text":"OMIDTaiwanmobileAdSessionContext"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}