{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"adViewDidReceiveAd"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"view"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADBannerView","preciseIdentifier":"c:objc(cs)TADBannerView","text":"TADBannerView"},{"kind":"text","text":"!)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/tamediaadsframework\/tadbannerviewdelegate\/adviewdidreceivead(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/tamediaadsframework\/tadbannerviewdelegate\/adviewdidreceivead(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADBannerViewDelegate\/adViewDidReceiveAd(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"廣告取得成功"}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"adViewDidReceiveAd:"}],"role":"symbol","title":"adViewDidReceiveAd(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"adViewDidReceiveAd"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"TADBannerView","preciseIdentifier":"c:objc(cs)TADBannerView"},{"kind":"text","text":"!)"}],"symbolKind":"method","externalID":"c:objc(pl)TADBannerViewDelegate(im)adViewDidReceiveAd:","required":true,"modules":[{"name":"TAMediaAdsFramework"}]},"hierarchy":{"paths":[["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADBannerViewDelegate"]]},"references":{"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADBannerViewDelegate/adViewDidReceiveAd(_:)":{"navigatorTitle":[{"kind":"identifier","text":"adViewDidReceiveAd:"}],"role":"symbol","title":"adViewDidReceiveAd(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"adViewDidReceiveAd"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"TADBannerView","preciseIdentifier":"c:objc(cs)TADBannerView"},{"kind":"text","text":"!)"}],"abstract":[{"type":"text","text":"廣告取得成功"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADBannerViewDelegate\/adViewDidReceiveAd(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/tamediaadsframework\/tadbannerviewdelegate\/adviewdidreceivead(_:)"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework":{"role":"collection","title":"TAMediaAdsFramework","abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","kind":"symbol","type":"topic","url":"\/documentation\/tamediaadsframework"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADBannerViewDelegate":{"role":"symbol","title":"TADBannerViewDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADBannerViewDelegate"}],"abstract":[{"type":"text","text":"用於從 TADBannerView 接收狀態更改消息的委託，例如廣告請求成功\/失敗或點擊廣告時。"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADBannerViewDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TADBannerViewDelegate"}],"url":"\/documentation\/tamediaadsframework\/tadbannerviewdelegate"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADBannerView":{"role":"symbol","title":"TADBannerView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADBannerView"}],"abstract":[{"type":"text","text":"顯示橫幅廣告的視圖。"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADBannerView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TADBannerView"}],"url":"\/documentation\/tamediaadsframework\/tadbannerview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"adViewDidReceiveAd:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"adViewDidReceiveAd:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"adViewDidReceiveAd:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADBannerView","preciseIdentifier":"c:objc(cs)TADBannerView","text":"TADBannerView"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"view"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADBannerViewDelegate~1adViewDidReceiveAd(_:)\/title","value":"adViewDidReceiveAd:"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADBannerViewDelegate~1adViewDidReceiveAd(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"adViewDidReceiveAd:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADBannerViewDelegate\/title","value":"TADBannerViewDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADBannerViewDelegate\/fragments","value":[{"kind":"identifier","text":"TADBannerViewDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADBannerView\/title","value":"TADBannerView"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADBannerView\/fragments","value":[{"kind":"identifier","text":"TADBannerView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}