{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeFriendlyObstruction"},{"kind":"text","text":"("},{"kind":"externalParam","text":"view"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"view","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"指定視圖"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/tamediaadsframework\/tadnativeadview\/removefriendlyobstruction(view:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/tamediaadsframework\/tadnativeadview\/removefriendlyobstruction(view:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdView\/removeFriendlyObstruction(view:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"移除障礙物"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeFriendlyObstruction"},{"kind":"text","text":"("},{"kind":"externalParam","text":"view"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":")"}],"title":"removeFriendlyObstruction(view:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@TAMediaAdsFramework@objc(cs)TADNativeAdView(im)removeFriendlyObstructionWithView:","modules":[{"name":"TAMediaAdsFramework"}],"navigatorTitle":[{"kind":"identifier","text":"removeFriendlyObstructionWithView:"}]},"hierarchy":{"paths":[["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdView"]]},"references":{"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADNativeAdView/removeFriendlyObstruction(view:)":{"role":"symbol","title":"removeFriendlyObstruction(view:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeFriendlyObstruction"},{"kind":"text","text":"("},{"kind":"externalParam","text":"view"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"移除障礙物"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdView\/removeFriendlyObstruction(view:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"removeFriendlyObstructionWithView:"}],"url":"\/documentation\/tamediaadsframework\/tadnativeadview\/removefriendlyobstruction(view:)"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework":{"role":"collection","title":"TAMediaAdsFramework","abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","kind":"symbol","type":"topic","url":"\/documentation\/tamediaadsframework"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADNativeAdView":{"role":"symbol","title":"TADNativeAdView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADNativeAdView"}],"abstract":[{"type":"text","text":"用於呈現 NativeAd 的視圖，內有 Label、ImageView、mediaView 等屬性可控制。"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TADNativeAdView"}],"url":"\/documentation\/tamediaadsframework\/tadnativeadview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"removeFriendlyObstructionWithView:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeFriendlyObstructionWithView:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"removeFriendlyObstructionWithView:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"view"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAdView~1removeFriendlyObstruction(view:)\/title","value":"removeFriendlyObstructionWithView:"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAdView~1removeFriendlyObstruction(view:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeFriendlyObstructionWithView:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAdView\/title","value":"TADNativeAdView"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAdView\/fragments","value":[{"kind":"identifier","text":"TADNativeAdView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}