{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"acceptInvitation"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/tamediaadsframework\/omidinteractiontype\/acceptinvitation"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/tamediaadsframework\/omidinteractiontype\/acceptinvitation"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDInteractionType\/acceptInvitation","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The user engaged with ad content to load a separate experience."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"acceptInvitation"}],"title":"OMIDInteractionType.acceptInvitation","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@OMIDInteractionType@OMIDInteractionTypeAcceptInvitation","modules":[{"name":"TAMediaAdsFramework"}],"navigatorTitle":[{"kind":"identifier","text":"OMIDInteractionTypeAcceptInvitation"}]},"hierarchy":{"paths":[["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDInteractionType"]]},"references":{"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/OMIDInteractionType/acceptInvitation":{"role":"symbol","title":"OMIDInteractionType.acceptInvitation","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"acceptInvitation"}],"abstract":[{"type":"text","text":"The user engaged with ad content to load a separate experience."}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDInteractionType\/acceptInvitation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OMIDInteractionTypeAcceptInvitation"}],"url":"\/documentation\/tamediaadsframework\/omidinteractiontype\/acceptinvitation"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/OMIDInteractionType":{"role":"symbol","title":"OMIDInteractionType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"OMIDInteractionType"}],"abstract":[{"type":"text","text":"List of supported media event user interaction types."}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDInteractionType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OMIDInteractionType"}],"url":"\/documentation\/tamediaadsframework\/omidinteractiontype"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework":{"role":"collection","title":"TAMediaAdsFramework","abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","kind":"symbol","type":"topic","url":"\/documentation\/tamediaadsframework"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"OMIDInteractionTypeAcceptInvitation"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"OMIDInteractionTypeAcceptInvitation"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"OMIDInteractionTypeAcceptInvitation"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDInteractionType~1acceptInvitation\/title","value":"OMIDInteractionTypeAcceptInvitation"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDInteractionType~1acceptInvitation\/fragments","value":[{"kind":"identifier","text":"OMIDInteractionTypeAcceptInvitation"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDInteractionType\/title","value":"OMIDInteractionType"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDInteractionType\/fragments","value":[{"kind":"identifier","text":"OMIDInteractionType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}