{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addFriendlyObstruction"},{"kind":"text","text":"("},{"kind":"externalParam","text":"view"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"purpose"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADFriendlyObstructionPurpose","preciseIdentifier":"c:@M@TAMediaAdsFramework@E@TADFriendyObstrucitonPurpose","text":"TADFriendlyObstructionPurpose"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"view","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"指定視圖"}]}]},{"name":"purpose","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"障礙物類型。參照"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADFriendlyObstructionPurpose"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/tamediaadsframework\/tadnativeadview\/addfriendlyobstruction(view:purpose:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/tamediaadsframework\/tadnativeadview\/addfriendlyobstruction(view:purpose:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdView\/addFriendlyObstruction(view:purpose:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"加入障礙物"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addFriendlyObstruction"},{"kind":"text","text":"("},{"kind":"externalParam","text":"view"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"purpose"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TADFriendlyObstructionPurpose","preciseIdentifier":"c:@M@TAMediaAdsFramework@E@TADFriendyObstrucitonPurpose"},{"kind":"text","text":")"}],"title":"addFriendlyObstruction(view:purpose:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@TAMediaAdsFramework@objc(cs)TADNativeAdView(im)addFriendlyObstructionWithView:purpose:","modules":[{"name":"TAMediaAdsFramework"}],"navigatorTitle":[{"kind":"identifier","text":"addFriendlyObstructionWithView:purpose:"}]},"hierarchy":{"paths":[["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdView"]]},"references":{"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADFriendlyObstructionPurpose":{"role":"symbol","title":"TADFriendlyObstructionPurpose","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADFriendlyObstructionPurpose"}],"abstract":[{"type":"text","text":"顯示在廣告頁面的障礙物類型"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADFriendlyObstructionPurpose","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TADFriendlyObstructionPurpose"}],"url":"\/documentation\/tamediaadsframework\/tadfriendlyobstructionpurpose"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADNativeAdView":{"role":"symbol","title":"TADNativeAdView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADNativeAdView"}],"abstract":[{"type":"text","text":"用於呈現 NativeAd 的視圖，內有 Label、ImageView、mediaView 等屬性可控制。"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TADNativeAdView"}],"url":"\/documentation\/tamediaadsframework\/tadnativeadview"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework":{"role":"collection","title":"TAMediaAdsFramework","abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","kind":"symbol","type":"topic","url":"\/documentation\/tamediaadsframework"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADNativeAdView/addFriendlyObstruction(view:purpose:)":{"role":"symbol","title":"addFriendlyObstruction(view:purpose:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addFriendlyObstruction"},{"kind":"text","text":"("},{"kind":"externalParam","text":"view"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"purpose"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TADFriendlyObstructionPurpose","preciseIdentifier":"c:@M@TAMediaAdsFramework@E@TADFriendyObstrucitonPurpose"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"加入障礙物"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdView\/addFriendlyObstruction(view:purpose:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"addFriendlyObstructionWithView:purpose:"}],"url":"\/documentation\/tamediaadsframework\/tadnativeadview\/addfriendlyobstruction(view:purpose:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"addFriendlyObstructionWithView:purpose:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addFriendlyObstructionWithView:purpose:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"addFriendlyObstructionWithView:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"view"},{"kind":"text","text":" "},{"kind":"identifier","text":"purpose:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADFriendlyObstructionPurpose","preciseIdentifier":"c:@M@TAMediaAdsFramework@E@TADFriendyObstrucitonPurpose","text":"TADFriendyObstrucitonPurpose"},{"kind":"text","text":")"},{"kind":"internalParam","text":"purpose"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADFriendlyObstructionPurpose\/title","value":"TADFriendyObstrucitonPurpose"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADFriendlyObstructionPurpose\/fragments","value":[{"kind":"identifier","text":"TADFriendyObstrucitonPurpose"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAdView\/title","value":"TADNativeAdView"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAdView\/fragments","value":[{"kind":"identifier","text":"TADNativeAdView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAdView~1addFriendlyObstruction(view:purpose:)\/title","value":"addFriendlyObstructionWithView:purpose:"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAdView~1addFriendlyObstruction(view:purpose:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addFriendlyObstructionWithView:purpose:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}