{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"closeAd"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/tamediaadsframework\/omidfriendlyobstructiontype\/closead"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/tamediaadsframework\/omidfriendlyobstructiontype\/closead"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDFriendlyObstructionType\/closeAd","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The friendly obstruction relates to closing an ad (such as a close button)."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"closeAd"}],"title":"OMIDFriendlyObstructionType.closeAd","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@OMIDFriendlyObstructionType@OMIDFriendlyObstructionCloseAd","modules":[{"name":"TAMediaAdsFramework"}],"navigatorTitle":[{"kind":"identifier","text":"OMIDFriendlyObstructionCloseAd"}]},"hierarchy":{"paths":[["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDFriendlyObstructionType"]]},"references":{"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/OMIDFriendlyObstructionType/closeAd":{"role":"symbol","title":"OMIDFriendlyObstructionType.closeAd","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"closeAd"}],"abstract":[{"type":"text","text":"The friendly obstruction relates to closing an ad (such as a close button)."}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDFriendlyObstructionType\/closeAd","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OMIDFriendlyObstructionCloseAd"}],"url":"\/documentation\/tamediaadsframework\/omidfriendlyobstructiontype\/closead"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework":{"role":"collection","title":"TAMediaAdsFramework","abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","kind":"symbol","type":"topic","url":"\/documentation\/tamediaadsframework"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/OMIDFriendlyObstructionType":{"role":"symbol","title":"OMIDFriendlyObstructionType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"OMIDFriendlyObstructionType"}],"abstract":[{"type":"text","text":"List of allowed friendly obstruction purposes."}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDFriendlyObstructionType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OMIDFriendlyObstructionType"}],"url":"\/documentation\/tamediaadsframework\/omidfriendlyobstructiontype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"OMIDFriendlyObstructionCloseAd"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"OMIDFriendlyObstructionCloseAd"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"OMIDFriendlyObstructionCloseAd"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDFriendlyObstructionType~1closeAd\/title","value":"OMIDFriendlyObstructionCloseAd"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDFriendlyObstructionType~1closeAd\/fragments","value":[{"kind":"identifier","text":"OMIDFriendlyObstructionCloseAd"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDFriendlyObstructionType\/title","value":"OMIDFriendlyObstructionType"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDFriendlyObstructionType\/fragments","value":[{"kind":"identifier","text":"OMIDFriendlyObstructionType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}