{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"interstitialWillDismissScreen"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"ad"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInterstitial","preciseIdentifier":"c:objc(cs)TADInterstitial","text":"TADInterstitial"},{"kind":"text","text":"!)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/tamediaadsframework\/tadinterstitialdelegate\/interstitialwilldismissscreen(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/tamediaadsframework\/tadinterstitialdelegate\/interstitialwilldismissscreen(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInterstitialDelegate\/interstitialWillDismissScreen(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Interstitial廣告關閉, 在螢幕上消失之前呼叫, 再次提醒在Interstitail消失前, 必須將Interstitial及delegate設為nil (可以在這個function中執行)"}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"interstitialWillDismissScreen:"}],"role":"symbol","title":"interstitialWillDismissScreen(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"interstitialWillDismissScreen"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"TADInterstitial","preciseIdentifier":"c:objc(cs)TADInterstitial"},{"kind":"text","text":"!)"}],"symbolKind":"method","externalID":"c:objc(pl)TADInterstitialDelegate(im)interstitialWillDismissScreen:","required":true,"modules":[{"name":"TAMediaAdsFramework"}]},"hierarchy":{"paths":[["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInterstitialDelegate"]]},"references":{"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework":{"role":"collection","title":"TAMediaAdsFramework","abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","kind":"symbol","type":"topic","url":"\/documentation\/tamediaadsframework"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADInterstitialDelegate/interstitialWillDismissScreen(_:)":{"navigatorTitle":[{"kind":"identifier","text":"interstitialWillDismissScreen:"}],"role":"symbol","title":"interstitialWillDismissScreen(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"interstitialWillDismissScreen"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"TADInterstitial","preciseIdentifier":"c:objc(cs)TADInterstitial"},{"kind":"text","text":"!)"}],"abstract":[{"type":"text","text":"Interstitial廣告關閉, 在螢幕上消失之前呼叫, 再次提醒在Interstitail消失前, 必須將Interstitial及delegate設為nil (可以在這個function中執行)"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInterstitialDelegate\/interstitialWillDismissScreen(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/tamediaadsframework\/tadinterstitialdelegate\/interstitialwilldismissscreen(_:)"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADInterstitial":{"role":"symbol","title":"TADInterstitial","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADInterstitial"}],"abstract":[{"type":"text","text":"顯示插頁式廣告。 這是一個全屏廣告，顯示在您的應用程序中，例如遊戲關卡或新聞故事之間。"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInterstitial","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TADInterstitial"}],"url":"\/documentation\/tamediaadsframework\/tadinterstitial"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADInterstitialDelegate":{"role":"symbol","title":"TADInterstitialDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADInterstitialDelegate"}],"abstract":[{"type":"text","text":"用於從 TADInterstitialDelegate 接收狀態更改消息的委託，例如插頁式廣告請求成功\/失敗。"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInterstitialDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TADInterstitialDelegate"}],"url":"\/documentation\/tamediaadsframework\/tadinterstitialdelegate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"interstitialWillDismissScreen:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"interstitialWillDismissScreen:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"interstitialWillDismissScreen:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInterstitial","preciseIdentifier":"c:objc(cs)TADInterstitial","text":"TADInterstitial"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"ad"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADInterstitialDelegate~1interstitialWillDismissScreen(_:)\/title","value":"interstitialWillDismissScreen:"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADInterstitialDelegate~1interstitialWillDismissScreen(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"interstitialWillDismissScreen:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADInterstitial\/title","value":"TADInterstitial"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADInterstitial\/fragments","value":[{"kind":"identifier","text":"TADInterstitial"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADInterstitialDelegate\/title","value":"TADInterstitialDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADInterstitialDelegate\/fragments","value":[{"kind":"identifier","text":"TADInterstitialDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}