{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"iconRect"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdImage","preciseIdentifier":"c:@M@TAMediaAdsFramework@objc(cs)TADNativeAdImage","text":"TADNativeAdImage"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/tamediaadsframework\/tadnativeadcontent\/iconrect"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/tamediaadsframework\/tadnativeadcontent\/iconrect"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdContent\/iconRect","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"小圖示 長 icon rectangle, ※預設值為空字串"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"iconRect"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TADNativeAdImage","preciseIdentifier":"c:@M@TAMediaAdsFramework@objc(cs)TADNativeAdImage"},{"kind":"text","text":"?"}],"title":"iconRect","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@TAMediaAdsFramework@objc(cs)TADNativeAdContent(py)iconRect","modules":[{"name":"TAMediaAdsFramework"}],"navigatorTitle":[{"kind":"identifier","text":"iconRect"}]},"hierarchy":{"paths":[["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdContent"]]},"references":{"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADNativeAdImage":{"role":"symbol","title":"TADNativeAdImage","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADNativeAdImage"}],"abstract":[{"type":"text","text":"用於NativeAd的圖像物件"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdImage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TADNativeAdImage"}],"url":"\/documentation\/tamediaadsframework\/tadnativeadimage"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADNativeAdContent/iconRect":{"role":"symbol","title":"iconRect","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"iconRect"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TADNativeAdImage","preciseIdentifier":"c:@M@TAMediaAdsFramework@objc(cs)TADNativeAdImage"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"小圖示 長 icon rectangle, ※預設值為空字串"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdContent\/iconRect","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"iconRect"}],"url":"\/documentation\/tamediaadsframework\/tadnativeadcontent\/iconrect"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework":{"role":"collection","title":"TAMediaAdsFramework","abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","kind":"symbol","type":"topic","url":"\/documentation\/tamediaadsframework"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADNativeAdContent":{"role":"symbol","title":"TADNativeAdContent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADNativeAdContent"}],"abstract":[{"type":"text","text":"封裝 native 廣告的物件"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdContent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TADNativeAdContent"}],"url":"\/documentation\/tamediaadsframework\/tadnativeadcontent"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"iconRect"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"iconRect"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdImage","preciseIdentifier":"c:@M@TAMediaAdsFramework@objc(cs)TADNativeAdImage","text":"TADNativeAdImage"},{"kind":"text","text":" *"},{"kind":"identifier","text":"iconRect"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAdImage\/title","value":"TADNativeAdImage"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAdImage\/fragments","value":[{"kind":"identifier","text":"TADNativeAdImage"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAdContent~1iconRect\/title","value":"iconRect"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAdContent~1iconRect\/fragments","value":[{"kind":"identifier","text":"iconRect"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAdContent\/title","value":"TADNativeAdContent"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAdContent\/fragments","value":[{"kind":"identifier","text":"TADNativeAdContent"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}