{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"versionString"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Both name and version are mandatory."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/tamediaadsframework\/omidtaiwanmobilepartner\/init(name:versionstring:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/tamediaadsframework\/omidtaiwanmobilepartner\/init(name:versionstring:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobilePartner\/init(name:versionString:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Initializes new partner instance providing both name and versionString."}],"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"versionString"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"title":"init(name:versionString:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:objc(cs)OMIDTaiwanmobilePartner(im)initWithName:versionString:","modules":[{"name":"TAMediaAdsFramework"}],"navigatorTitle":[{"kind":"identifier","text":"initWithName:versionString:"}]},"hierarchy":{"paths":[["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobilePartner"]]},"references":{"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/OMIDTaiwanmobilePartner/init(name:versionString:)":{"role":"symbol","title":"init(name:versionString:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"versionString"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Initializes new partner instance providing both name and versionString."}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobilePartner\/init(name:versionString:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithName:versionString:"}],"url":"\/documentation\/tamediaadsframework\/omidtaiwanmobilepartner\/init(name:versionstring:)"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/OMIDTaiwanmobilePartner":{"role":"symbol","title":"OMIDTaiwanmobilePartner","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OMIDTaiwanmobilePartner"}],"abstract":[{"type":"text","text":"Details about the integration partner which will be supplied to the ad session."}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobilePartner","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OMIDTaiwanmobilePartner"}],"url":"\/documentation\/tamediaadsframework\/omidtaiwanmobilepartner"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework":{"role":"collection","title":"TAMediaAdsFramework","abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","kind":"symbol","type":"topic","url":"\/documentation\/tamediaadsframework"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithName:versionString:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithName:versionString:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithName:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"name"},{"kind":"text","text":" "},{"kind":"identifier","text":"versionString:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"versionString"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDTaiwanmobilePartner~1init(name:versionString:)\/title","value":"initWithName:versionString:"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDTaiwanmobilePartner~1init(name:versionString:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithName:versionString:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDTaiwanmobilePartner\/title","value":"OMIDTaiwanmobilePartner"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDTaiwanmobilePartner\/fragments","value":[{"kind":"identifier","text":"OMIDTaiwanmobilePartner"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}