{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"partner"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobilePartner","preciseIdentifier":"c:objc(cs)OMIDTaiwanmobilePartner","text":"OMIDTaiwanmobilePartner"},{"kind":"text","text":", "},{"kind":"externalParam","text":"script"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"resources"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileVerificationScriptResource","preciseIdentifier":"c:objc(cs)OMIDTaiwanmobileVerificationScriptResource","text":"OMIDTaiwanmobileVerificationScriptResource"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"contentUrl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"customReferenceIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) "},{"kind":"keyword","text":"throws"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Calling this method will set the ad session type to "},{"type":"codeVoice","code":"native"},{"type":"text","text":"."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"event data. Must contain at least one verification script. The receiver creates a"},{"type":"text","text":" "},{"type":"text","text":"deep copy of the array."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/tamediaadsframework\/omidtaiwanmobileadsessioncontext\/init(partner:script:resources:contenturl:customreferenceidentifier:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/tamediaadsframework\/omidtaiwanmobileadsessioncontext\/init(partner:script:resources:contenturl:customreferenceidentifier:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileAdSessionContext\/init(partner:script:resources:contentUrl:customReferenceIdentifier:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Initializes a new ad session context providing reference to partner and a list of"},{"type":"text","text":" "},{"type":"text","text":"script resources which should be managed by OMID."}],"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"partner"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"OMIDTaiwanmobilePartner","preciseIdentifier":"c:objc(cs)OMIDTaiwanmobilePartner"},{"kind":"text","text":", "},{"kind":"externalParam","text":"script"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"resources"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"OMIDTaiwanmobileVerificationScriptResource","preciseIdentifier":"c:objc(cs)OMIDTaiwanmobileVerificationScriptResource"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"contentUrl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"customReferenceIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) "},{"kind":"keyword","text":"throws"}],"title":"init(partner:script:resources:contentUrl:customReferenceIdentifier:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:objc(cs)OMIDTaiwanmobileAdSessionContext(im)initWithPartner:script:resources:contentUrl:customReferenceIdentifier:error:","modules":[{"name":"TAMediaAdsFramework"}],"navigatorTitle":[{"kind":"identifier","text":"initWithPartner:script:resources:contentUrl:customReferenceIdentifier:error:"}]},"hierarchy":{"paths":[["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileAdSessionContext"]]},"references":{"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/OMIDTaiwanmobilePartner":{"role":"symbol","title":"OMIDTaiwanmobilePartner","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OMIDTaiwanmobilePartner"}],"abstract":[{"type":"text","text":"Details about the integration partner which will be supplied to the ad session."}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobilePartner","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OMIDTaiwanmobilePartner"}],"url":"\/documentation\/tamediaadsframework\/omidtaiwanmobilepartner"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/OMIDTaiwanmobileVerificationScriptResource":{"role":"symbol","title":"OMIDTaiwanmobileVerificationScriptResource","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OMIDTaiwanmobileVerificationScriptResource"}],"abstract":[{"type":"text","text":"Details about the verification provider which will be supplied to the ad session."}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileVerificationScriptResource","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OMIDTaiwanmobileVerificationScriptResource"}],"url":"\/documentation\/tamediaadsframework\/omidtaiwanmobileverificationscriptresource"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/OMIDTaiwanmobileAdSessionContext":{"role":"symbol","title":"OMIDTaiwanmobileAdSessionContext","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OMIDTaiwanmobileAdSessionContext"}],"abstract":[{"type":"text","text":"Provides the ad session with details of the partner and whether to an HTML,"},{"type":"text","text":" "},{"type":"text","text":"JavaScript, or native session."}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileAdSessionContext","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OMIDTaiwanmobileAdSessionContext"}],"url":"\/documentation\/tamediaadsframework\/omidtaiwanmobileadsessioncontext"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/OMIDTaiwanmobileAdSessionContext/init(partner:script:resources:contentUrl:customReferenceIdentifier:)":{"role":"symbol","title":"init(partner:script:resources:contentUrl:customReferenceIdentifier:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"partner"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"OMIDTaiwanmobilePartner","preciseIdentifier":"c:objc(cs)OMIDTaiwanmobilePartner"},{"kind":"text","text":", "},{"kind":"externalParam","text":"script"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"resources"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"OMIDTaiwanmobileVerificationScriptResource","preciseIdentifier":"c:objc(cs)OMIDTaiwanmobileVerificationScriptResource"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"contentUrl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"customReferenceIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) "},{"kind":"keyword","text":"throws"}],"abstract":[{"type":"text","text":"Initializes a new ad session context providing reference to partner and a list of"},{"type":"text","text":" "},{"type":"text","text":"script resources which should be managed by OMID."}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileAdSessionContext\/init(partner:script:resources:contentUrl:customReferenceIdentifier:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithPartner:script:resources:contentUrl:customReferenceIdentifier:error:"}],"url":"\/documentation\/tamediaadsframework\/omidtaiwanmobileadsessioncontext\/init(partner:script:resources:contenturl:customreferenceidentifier:)"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework":{"role":"collection","title":"TAMediaAdsFramework","abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","kind":"symbol","type":"topic","url":"\/documentation\/tamediaadsframework"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithPartner:script:resources:contentUrl:customReferenceIdentifier:error:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithPartner:script:resources:contentUrl:customReferenceIdentifier:error:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithPartner:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobilePartner","preciseIdentifier":"c:objc(cs)OMIDTaiwanmobilePartner","text":"OMIDTaiwanmobilePartner"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"partner"},{"kind":"text","text":" "},{"kind":"identifier","text":"script:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"script"},{"kind":"text","text":" "},{"kind":"identifier","text":"resources:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<OMIDTaiwanmobileVerificationScriptResource *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"resources"},{"kind":"text","text":" "},{"kind":"identifier","text":"contentUrl:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"contentUrl"},{"kind":"text","text":" "},{"kind":"identifier","text":"customReferenceIdentifier:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"customReferenceIdentifier"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" * *)"},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDTaiwanmobilePartner\/title","value":"OMIDTaiwanmobilePartner"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDTaiwanmobilePartner\/fragments","value":[{"kind":"identifier","text":"OMIDTaiwanmobilePartner"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDTaiwanmobileVerificationScriptResource\/title","value":"OMIDTaiwanmobileVerificationScriptResource"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDTaiwanmobileVerificationScriptResource\/fragments","value":[{"kind":"identifier","text":"OMIDTaiwanmobileVerificationScriptResource"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDTaiwanmobileAdSessionContext\/title","value":"OMIDTaiwanmobileAdSessionContext"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDTaiwanmobileAdSessionContext\/fragments","value":[{"kind":"identifier","text":"OMIDTaiwanmobileAdSessionContext"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDTaiwanmobileAdSessionContext~1init(partner:script:resources:contentUrl:customReferenceIdentifier:)\/title","value":"initWithPartner:script:resources:contentUrl:customReferenceIdentifier:error:"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDTaiwanmobileAdSessionContext~1init(partner:script:resources:contentUrl:customReferenceIdentifier:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithPartner:script:resources:contentUrl:customReferenceIdentifier:error:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}