{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"audio"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/tamediaadsframework\/omidcreativetype\/audio"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/tamediaadsframework\/omidcreativetype\/audio"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDCreativeType\/audio","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Similar to video but only contains audio media."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"audio"}],"title":"OMIDCreativeType.audio","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@OMIDCreativeType@OMIDCreativeTypeAudio","modules":[{"name":"TAMediaAdsFramework"}],"navigatorTitle":[{"kind":"identifier","text":"OMIDCreativeTypeAudio"}]},"hierarchy":{"paths":[["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDCreativeType"]]},"references":{"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework":{"role":"collection","title":"TAMediaAdsFramework","abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","kind":"symbol","type":"topic","url":"\/documentation\/tamediaadsframework"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/OMIDCreativeType/audio":{"role":"symbol","title":"OMIDCreativeType.audio","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"audio"}],"abstract":[{"type":"text","text":"Similar to video but only contains audio media."}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDCreativeType\/audio","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OMIDCreativeTypeAudio"}],"url":"\/documentation\/tamediaadsframework\/omidcreativetype\/audio"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/OMIDCreativeType":{"role":"symbol","title":"OMIDCreativeType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"OMIDCreativeType"}],"abstract":[{"type":"text","text":"List of supported creative types."}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDCreativeType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OMIDCreativeType"}],"url":"\/documentation\/tamediaadsframework\/omidcreativetype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"OMIDCreativeTypeAudio"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"OMIDCreativeTypeAudio"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"OMIDCreativeTypeAudio"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDCreativeType~1audio\/title","value":"OMIDCreativeTypeAudio"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDCreativeType~1audio\/fragments","value":[{"kind":"identifier","text":"OMIDCreativeTypeAudio"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDCreativeType\/title","value":"OMIDCreativeType"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDCreativeType\/fragments","value":[{"kind":"identifier","text":"OMIDCreativeType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}