{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"Flag1200x627w"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/tamediaadsframework\/tadadsizeflags\/flag1200x627w"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/tamediaadsframework\/tadadsizeflags\/flag1200x627w"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADAdSizeFlags\/Flag1200x627w","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"1200x627RatioBannerWithWidth"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"Flag1200x627w"}],"title":"TADAdSizeFlags.Flag1200x627w","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@TADAdSizeFlags@Flag1200x627w","modules":[{"name":"TAMediaAdsFramework"}],"navigatorTitle":[{"kind":"identifier","text":"Flag1200x627w"}]},"hierarchy":{"paths":[["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADAdSizeFlags"]]},"references":{"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework":{"role":"collection","title":"TAMediaAdsFramework","abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","kind":"symbol","type":"topic","url":"\/documentation\/tamediaadsframework"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADAdSizeFlags/Flag1200x627w":{"role":"symbol","title":"TADAdSizeFlags.Flag1200x627w","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"Flag1200x627w"}],"abstract":[{"type":"text","text":"1200x627RatioBannerWithWidth"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADAdSizeFlags\/Flag1200x627w","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Flag1200x627w"}],"url":"\/documentation\/tamediaadsframework\/tadadsizeflags\/flag1200x627w"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADAdSizeFlags":{"role":"symbol","title":"TADAdSizeFlags","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADAdSizeFlags"}],"abstract":[{"type":"text","text":"AdSize標籤，用於分類不同廣告尺寸對應的標籤"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADAdSizeFlags","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TADAdSizeFlags"}],"url":"\/documentation\/tamediaadsframework\/tadadsizeflags"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"Flag1200x627w"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"Flag1200x627w"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"Flag1200x627w"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADAdSizeFlags~1Flag1200x627w\/title","value":"Flag1200x627w"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADAdSizeFlags~1Flag1200x627w\/fragments","value":[{"kind":"identifier","text":"Flag1200x627w"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADAdSizeFlags\/title","value":"TADAdSizeFlags"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADAdSizeFlags\/fragments","value":[{"kind":"identifier","text":"TADAdSizeFlags"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}