{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"CGSizeFromTADAdSize"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"size"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADAdSize","preciseIdentifier":"c:@S@TADAdSize","text":"TADAdSize"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/tamediaadsframework\/cgsizefromtadadsize(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/tamediaadsframework\/cgsizefromtadadsize(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/CGSizeFromTADAdSize(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"給定一個 TADAdSize 常量，返回一個 CGSize。"},{"type":"text","text":" "},{"type":"text","text":"如果 TADAdSize 未知，返回 CGSizeZero。"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"CGSizeFromTADAdSize"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"TADAdSize","preciseIdentifier":"c:@S@TADAdSize"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"}],"title":"CGSizeFromTADAdSize(_:)","roleHeading":"Function","role":"symbol","symbolKind":"func","externalID":"c:@F@CGSizeFromTADAdSize","modules":[{"name":"TAMediaAdsFramework"}],"navigatorTitle":[{"kind":"identifier","text":"CGSizeFromTADAdSize"}]},"hierarchy":{"paths":[["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework"]]},"references":{"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework":{"role":"collection","title":"TAMediaAdsFramework","abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","kind":"symbol","type":"topic","url":"\/documentation\/tamediaadsframework"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADAdSize":{"role":"symbol","title":"TADAdSize","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADAdSize"}],"abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADAdSize","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TADAdSize"}],"url":"\/documentation\/tamediaadsframework\/tadadsize"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/CGSizeFromTADAdSize(_:)":{"role":"symbol","title":"CGSizeFromTADAdSize(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"CGSizeFromTADAdSize"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"TADAdSize","preciseIdentifier":"c:@S@TADAdSize"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"}],"abstract":[{"type":"text","text":"給定一個 TADAdSize 常量，返回一個 CGSize。"},{"type":"text","text":" "},{"type":"text","text":"如果 TADAdSize 未知，返回 CGSizeZero。"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/CGSizeFromTADAdSize(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CGSizeFromTADAdSize"}],"url":"\/documentation\/tamediaadsframework\/cgsizefromtadadsize(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Function"},{"op":"replace","path":"\/metadata\/title","value":"CGSizeFromTADAdSize"},{"op":"replace","path":"\/metadata\/symbolKind","value":"func"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"CGSizeFromTADAdSize"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":" "},{"kind":"identifier","text":"CGSizeFromTADAdSize"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADAdSize","preciseIdentifier":"c:@S@TADAdSize","text":"TADAdSize"},{"kind":"text","text":" "},{"kind":"internalParam","text":"size"},{"kind":"text","text":")"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADAdSize\/title","value":"TADAdSize"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADAdSize\/fragments","value":[{"kind":"identifier","text":"TADAdSize"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1CGSizeFromTADAdSize(_:)\/title","value":"CGSizeFromTADAdSize"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1CGSizeFromTADAdSize(_:)\/fragments","value":[{"kind":"identifier","text":"CGSizeFromTADAdSize"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}