{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"kTADAdSizeMediumRectangle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADAdSize","preciseIdentifier":"c:@S@TADAdSize","text":"TADAdSize"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/tamediaadsframework\/ktadadsizemediumrectangle"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/tamediaadsframework\/ktadadsizemediumrectangle"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/kTADAdSizeMediumRectangle","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"iPad 的中等矩形大小（尤其是在 UISplitView 的左窗格中）。"},{"type":"text","text":" "},{"type":"text","text":"通常為 300x250。"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"kTADAdSizeMediumRectangle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TADAdSize","preciseIdentifier":"c:@S@TADAdSize"}],"title":"kTADAdSizeMediumRectangle","roleHeading":"Global Variable","role":"symbol","symbolKind":"var","externalID":"c:@kTADAdSizeMediumRectangle","modules":[{"name":"TAMediaAdsFramework"}],"navigatorTitle":[{"kind":"identifier","text":"kTADAdSizeMediumRectangle"}]},"hierarchy":{"paths":[["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework"]]},"references":{"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework":{"role":"collection","title":"TAMediaAdsFramework","abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","kind":"symbol","type":"topic","url":"\/documentation\/tamediaadsframework"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADAdSize":{"role":"symbol","title":"TADAdSize","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADAdSize"}],"abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADAdSize","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TADAdSize"}],"url":"\/documentation\/tamediaadsframework\/tadadsize"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/kTADAdSizeMediumRectangle":{"role":"symbol","title":"kTADAdSizeMediumRectangle","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"kTADAdSizeMediumRectangle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TADAdSize","preciseIdentifier":"c:@S@TADAdSize"}],"abstract":[{"type":"text","text":"iPad 的中等矩形大小（尤其是在 UISplitView 的左窗格中）。"},{"type":"text","text":" "},{"type":"text","text":"通常為 300x250。"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/kTADAdSizeMediumRectangle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"kTADAdSizeMediumRectangle"}],"url":"\/documentation\/tamediaadsframework\/ktadadsizemediumrectangle"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Global Variable"},{"op":"replace","path":"\/metadata\/title","value":"kTADAdSizeMediumRectangle"},{"op":"replace","path":"\/metadata\/symbolKind","value":"var"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"kTADAdSizeMediumRectangle"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADAdSize","preciseIdentifier":"c:@S@TADAdSize","text":"TADAdSize"},{"kind":"text","text":" "},{"kind":"identifier","text":"kTADAdSizeMediumRectangle"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADAdSize\/title","value":"TADAdSize"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADAdSize\/fragments","value":[{"kind":"identifier","text":"TADAdSize"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1kTADAdSizeMediumRectangle\/title","value":"kTADAdSizeMediumRectangle"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1kTADAdSizeMediumRectangle\/fragments","value":[{"kind":"identifier","text":"kTADAdSizeMediumRectangle"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}