{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"kTADAdSizeBanner"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADAdSize","preciseIdentifier":"c:@S@TADAdSize","text":"TADAdSize"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/tamediaadsframework\/ktadadsizebanner"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/tamediaadsframework\/ktadadsizebanner"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/kTADAdSizeBanner","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"iPhone 或 iPod Touch的廣告尺寸，通常為320x50。"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"kTADAdSizeBanner"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TADAdSize","preciseIdentifier":"c:@S@TADAdSize"}],"title":"kTADAdSizeBanner","roleHeading":"Global Variable","role":"symbol","symbolKind":"var","externalID":"c:@kTADAdSizeBanner","modules":[{"name":"TAMediaAdsFramework"}],"navigatorTitle":[{"kind":"identifier","text":"kTADAdSizeBanner"}]},"hierarchy":{"paths":[["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework"]]},"references":{"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/kTADAdSizeBanner":{"role":"symbol","title":"kTADAdSizeBanner","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"kTADAdSizeBanner"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TADAdSize","preciseIdentifier":"c:@S@TADAdSize"}],"abstract":[{"type":"text","text":"iPhone 或 iPod Touch的廣告尺寸，通常為320x50。"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/kTADAdSizeBanner","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"kTADAdSizeBanner"}],"url":"\/documentation\/tamediaadsframework\/ktadadsizebanner"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADAdSize":{"role":"symbol","title":"TADAdSize","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADAdSize"}],"abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADAdSize","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TADAdSize"}],"url":"\/documentation\/tamediaadsframework\/tadadsize"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework":{"role":"collection","title":"TAMediaAdsFramework","abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","kind":"symbol","type":"topic","url":"\/documentation\/tamediaadsframework"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Global Variable"},{"op":"replace","path":"\/metadata\/title","value":"kTADAdSizeBanner"},{"op":"replace","path":"\/metadata\/symbolKind","value":"var"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"kTADAdSizeBanner"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADAdSize","preciseIdentifier":"c:@S@TADAdSize","text":"TADAdSize"},{"kind":"text","text":" "},{"kind":"identifier","text":"kTADAdSizeBanner"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1kTADAdSizeBanner\/title","value":"kTADAdSizeBanner"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1kTADAdSizeBanner\/fragments","value":[{"kind":"identifier","text":"kTADAdSizeBanner"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADAdSize\/title","value":"TADAdSize"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADAdSize\/fragments","value":[{"kind":"identifier","text":"TADAdSize"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}