{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OMIDTaiwanmobileMediaEvents"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/tamediaadsframework\/omidtaiwanmobilemediaevents"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/tamediaadsframework\/omidtaiwanmobilemediaevents"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)NSObject","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/s7CVarArgP","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/s28CustomDebugStringConvertibleP","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/s23CustomStringConvertibleP","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/SQ","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileMediaEvents","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This provides a complete list of native media events supported by OMID."},{"type":"text","text":" "},{"type":"text","text":"Using this event API assumes the media player is fully responsible for communicating all media events at the appropriate times."},{"type":"text","text":" "},{"type":"text","text":"Only one media events implementation can be associated with the ad session and any attempt to create multiple instances will result in an error."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OMIDTaiwanmobileMediaEvents"}],"title":"OMIDTaiwanmobileMediaEvents","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)OMIDTaiwanmobileMediaEvents","modules":[{"name":"TAMediaAdsFramework"}],"navigatorTitle":[{"kind":"identifier","text":"OMIDTaiwanmobileMediaEvents"}]},"hierarchy":{"paths":[["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileMediaEvents\/init(adSession:)"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileMediaEvents\/adUserInteraction(withType:)","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileMediaEvents\/bufferFinish()","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileMediaEvents\/bufferStart()","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileMediaEvents\/complete()","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileMediaEvents\/firstQuartile()","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileMediaEvents\/midpoint()","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileMediaEvents\/pause()","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileMediaEvents\/playerStateChange(to:)","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileMediaEvents\/resume()","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileMediaEvents\/skipped()","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileMediaEvents\/start(withDuration:mediaPlayerVolume:)","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileMediaEvents\/thirdQuartile()","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileMediaEvents\/volumeChange(to:)"]}],"references":{"doc://com.taiwanmobile.TAMediaAdsFramework/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/SQ"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/OMIDTaiwanmobileMediaEvents/adUserInteraction(withType:)":{"role":"symbol","title":"adUserInteraction(withType:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"adUserInteraction"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"OMIDInteractionType","preciseIdentifier":"c:@E@OMIDInteractionType"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Notifies all media listeners that the user has performed an ad interaction."},{"type":"text","text":" "},{"type":"text","text":"See "},{"type":"codeVoice","code":"OMIDInteractionType"},{"type":"text","text":" for a list of supported types."}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileMediaEvents\/adUserInteraction(withType:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"adUserInteractionWithType:"}],"url":"\/documentation\/tamediaadsframework\/omidtaiwanmobilemediaevents\/aduserinteraction(withtype:)"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/OMIDTaiwanmobileMediaEvents/volumeChange(to:)":{"role":"symbol","title":"volumeChange(to:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"volumeChange"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Notifies all media listeners that the media player volume has changed."}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileMediaEvents\/volumeChange(to:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"volumeChangeTo:"}],"url":"\/documentation\/tamediaadsframework\/omidtaiwanmobilemediaevents\/volumechange(to:)"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/OMIDTaiwanmobileMediaEvents/thirdQuartile()":{"role":"symbol","title":"thirdQuartile()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"thirdQuartile"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Notifies all media listeners that media playback has reached the third quartile."}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileMediaEvents\/thirdQuartile()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"thirdQuartile"}],"url":"\/documentation\/tamediaadsframework\/omidtaiwanmobilemediaevents\/thirdquartile()"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/OMIDTaiwanmobileMediaEvents/firstQuartile()":{"role":"symbol","title":"firstQuartile()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"firstQuartile"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Notifies all media listeners that media playback has reached the first quartile."}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileMediaEvents\/firstQuartile()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"firstQuartile"}],"url":"\/documentation\/tamediaadsframework\/omidtaiwanmobilemediaevents\/firstquartile()"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/OMIDTaiwanmobileMediaEvents/start(withDuration:mediaPlayerVolume:)":{"role":"symbol","title":"start(withDuration:mediaPlayerVolume:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"start"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withDuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mediaPlayerVolume"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Notifies all media listeners that media content has started playing."}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileMediaEvents\/start(withDuration:mediaPlayerVolume:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startWithDuration:mediaPlayerVolume:"}],"url":"\/documentation\/tamediaadsframework\/omidtaiwanmobilemediaevents\/start(withduration:mediaplayervolume:)"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/OMIDTaiwanmobileMediaEvents":{"role":"symbol","title":"OMIDTaiwanmobileMediaEvents","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OMIDTaiwanmobileMediaEvents"}],"abstract":[{"type":"text","text":"This provides a complete list of native media events supported by OMID."},{"type":"text","text":" "},{"type":"text","text":"Using this event API assumes the media player is fully responsible for communicating all media events at the appropriate times."},{"type":"text","text":" "},{"type":"text","text":"Only one media events implementation can be associated with the ad session and any attempt to create multiple instances will result in an error."}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileMediaEvents","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OMIDTaiwanmobileMediaEvents"}],"url":"\/documentation\/tamediaadsframework\/omidtaiwanmobilemediaevents"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/OMIDTaiwanmobileMediaEvents/playerStateChange(to:)":{"role":"symbol","title":"playerStateChange(to:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"playerStateChange"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"OMIDPlayerState","preciseIdentifier":"c:@E@OMIDPlayerState"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Notifies all media listeners that media player state has changed."},{"type":"text","text":" "},{"type":"text","text":"See "},{"type":"codeVoice","code":"OMIDPlayerState"},{"type":"text","text":" for list of supported states."}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileMediaEvents\/playerStateChange(to:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"playerStateChangeTo:"}],"url":"\/documentation\/tamediaadsframework\/omidtaiwanmobilemediaevents\/playerstatechange(to:)"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/OMIDTaiwanmobileMediaEvents/init(adSession:)":{"role":"symbol","title":"init(adSession:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"adSession"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"OMIDTaiwanmobileAdSession","preciseIdentifier":"c:objc(cs)OMIDTaiwanmobileAdSession"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[{"type":"text","text":"Initializes media events instance for the associated ad session."},{"type":"text","text":" "},{"type":"text","text":"Any attempt to create a media events instance will fail if the supplied ad session has already started."}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileMediaEvents\/init(adSession:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithAdSession:error:"}],"url":"\/documentation\/tamediaadsframework\/omidtaiwanmobilemediaevents\/init(adsession:)"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework":{"role":"collection","title":"TAMediaAdsFramework","abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","kind":"symbol","type":"topic","url":"\/documentation\/tamediaadsframework"},"doc://com.taiwanmobile.TAMediaAdsFramework/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/SH"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/OMIDTaiwanmobileMediaEvents/bufferStart()":{"role":"symbol","title":"bufferStart()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"bufferStart"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Notifies all media listeners that media playback has stopped and started buffering."}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileMediaEvents\/bufferStart()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"bufferStart"}],"url":"\/documentation\/tamediaadsframework\/omidtaiwanmobilemediaevents\/bufferstart()"},"doc://com.taiwanmobile.TAMediaAdsFramework/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/s23CustomStringConvertibleP"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/OMIDTaiwanmobileMediaEvents/resume()":{"role":"symbol","title":"resume()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"resume"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Notifies all media listeners that media playback has resumed after being paused."}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileMediaEvents\/resume()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"resume"}],"url":"\/documentation\/tamediaadsframework\/omidtaiwanmobilemediaevents\/resume()"},"doc://com.taiwanmobile.TAMediaAdsFramework/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)NSObject"},"doc://com.taiwanmobile.TAMediaAdsFramework/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/s7CVarArgP"},"doc://com.taiwanmobile.TAMediaAdsFramework/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(cs)NSObject"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/OMIDTaiwanmobileMediaEvents/skipped()":{"role":"symbol","title":"skipped()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"skipped"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Notifies all media listeners that media playback has stopped as a user skip interaction."},{"type":"text","text":" "},{"type":"text","text":"Once skipped, it should not be possible for the media to resume playing content."}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileMediaEvents\/skipped()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"skipped"}],"url":"\/documentation\/tamediaadsframework\/omidtaiwanmobilemediaevents\/skipped()"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/OMIDTaiwanmobileMediaEvents/complete()":{"role":"symbol","title":"complete()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"complete"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Notifies all media listeners that media playback is complete."}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileMediaEvents\/complete()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"complete"}],"url":"\/documentation\/tamediaadsframework\/omidtaiwanmobilemediaevents\/complete()"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/OMIDTaiwanmobileMediaEvents/pause()":{"role":"symbol","title":"pause()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pause"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Notifies all media listeners that media playback has paused after a user interaction."}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileMediaEvents\/pause()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"pause"}],"url":"\/documentation\/tamediaadsframework\/omidtaiwanmobilemediaevents\/pause()"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/OMIDTaiwanmobileMediaEvents/bufferFinish()":{"role":"symbol","title":"bufferFinish()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"bufferFinish"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Notifies all media listeners that buffering has finished and media playback has resumed."}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileMediaEvents\/bufferFinish()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"bufferFinish"}],"url":"\/documentation\/tamediaadsframework\/omidtaiwanmobilemediaevents\/bufferfinish()"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/OMIDTaiwanmobileMediaEvents/midpoint()":{"role":"symbol","title":"midpoint()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"midpoint"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Notifies all media listeners that media playback has reached the midpoint."}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileMediaEvents\/midpoint()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"midpoint"}],"url":"\/documentation\/tamediaadsframework\/omidtaiwanmobilemediaevents\/midpoint()"},"doc://com.taiwanmobile.TAMediaAdsFramework/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/s28CustomDebugStringConvertibleP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"OMIDTaiwanmobileMediaEvents"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"OMIDTaiwanmobileMediaEvents"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"OMIDTaiwanmobileMediaEvents"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileMediaEvents\/adUserInteraction(withType:)","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileMediaEvents\/bufferFinish()","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileMediaEvents\/bufferStart()","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileMediaEvents\/complete()","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileMediaEvents\/firstQuartile()","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileMediaEvents\/init(adSession:)","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileMediaEvents\/midpoint()","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileMediaEvents\/pause()","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileMediaEvents\/playerStateChange(to:)","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileMediaEvents\/resume()","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileMediaEvents\/skipped()","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileMediaEvents\/start(withDuration:mediaPlayerVolume:)","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileMediaEvents\/thirdQuartile()","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileMediaEvents\/volumeChange(to:)"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"OMIDTaiwanmobileMediaEvents"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDTaiwanmobileMediaEvents~1adUserInteraction(withType:)\/title","value":"adUserInteractionWithType:"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDTaiwanmobileMediaEvents~1adUserInteraction(withType:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"adUserInteractionWithType:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDTaiwanmobileMediaEvents~1volumeChange(to:)\/title","value":"volumeChangeTo:"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDTaiwanmobileMediaEvents~1volumeChange(to:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"volumeChangeTo:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDTaiwanmobileMediaEvents~1thirdQuartile()\/title","value":"thirdQuartile"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDTaiwanmobileMediaEvents~1thirdQuartile()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"thirdQuartile"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDTaiwanmobileMediaEvents~1firstQuartile()\/title","value":"firstQuartile"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDTaiwanmobileMediaEvents~1firstQuartile()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"firstQuartile"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDTaiwanmobileMediaEvents~1start(withDuration:mediaPlayerVolume:)\/title","value":"startWithDuration:mediaPlayerVolume:"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDTaiwanmobileMediaEvents~1start(withDuration:mediaPlayerVolume:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startWithDuration:mediaPlayerVolume:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDTaiwanmobileMediaEvents\/title","value":"OMIDTaiwanmobileMediaEvents"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDTaiwanmobileMediaEvents\/fragments","value":[{"kind":"identifier","text":"OMIDTaiwanmobileMediaEvents"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDTaiwanmobileMediaEvents~1playerStateChange(to:)\/title","value":"playerStateChangeTo:"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDTaiwanmobileMediaEvents~1playerStateChange(to:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"playerStateChangeTo:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDTaiwanmobileMediaEvents~1init(adSession:)\/title","value":"initWithAdSession:error:"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDTaiwanmobileMediaEvents~1init(adSession:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithAdSession:error:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDTaiwanmobileMediaEvents~1bufferStart()\/title","value":"bufferStart"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDTaiwanmobileMediaEvents~1bufferStart()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"bufferStart"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDTaiwanmobileMediaEvents~1resume()\/title","value":"resume"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDTaiwanmobileMediaEvents~1resume()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"resume"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDTaiwanmobileMediaEvents~1skipped()\/title","value":"skipped"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDTaiwanmobileMediaEvents~1skipped()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"skipped"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDTaiwanmobileMediaEvents~1complete()\/title","value":"complete"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDTaiwanmobileMediaEvents~1complete()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"complete"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDTaiwanmobileMediaEvents~1pause()\/title","value":"pause"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDTaiwanmobileMediaEvents~1pause()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"pause"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDTaiwanmobileMediaEvents~1bufferFinish()\/title","value":"bufferFinish"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDTaiwanmobileMediaEvents~1bufferFinish()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"bufferFinish"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDTaiwanmobileMediaEvents~1midpoint()\/title","value":"midpoint"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDTaiwanmobileMediaEvents~1midpoint()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"midpoint"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}