{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"OMIDFriendlyObstructionType"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/tamediaadsframework\/omidfriendlyobstructiontype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/tamediaadsframework\/omidfriendlyobstructiontype"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/SQ","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/SH","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/SY","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDFriendlyObstructionType","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"List of allowed friendly obstruction purposes."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"OMIDFriendlyObstructionType"}],"title":"OMIDFriendlyObstructionType","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@OMIDFriendlyObstructionType","modules":[{"name":"TAMediaAdsFramework"}],"navigatorTitle":[{"kind":"identifier","text":"OMIDFriendlyObstructionType"}]},"hierarchy":{"paths":[["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDFriendlyObstructionType\/closeAd","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDFriendlyObstructionType\/mediaControls","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDFriendlyObstructionType\/notVisible","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDFriendlyObstructionType\/other"]},{"title":"Initializers","identifiers":["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDFriendlyObstructionType\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDFriendlyObstructionType\/Equatable-Implementations","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDFriendlyObstructionType\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework":{"role":"collection","title":"TAMediaAdsFramework","abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","kind":"symbol","type":"topic","url":"\/documentation\/tamediaadsframework"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/OMIDFriendlyObstructionType/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDFriendlyObstructionType\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/tamediaadsframework\/omidfriendlyobstructiontype\/rawrepresentable-implementations"},"doc://com.taiwanmobile.TAMediaAdsFramework/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/SH"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/OMIDFriendlyObstructionType/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDFriendlyObstructionType\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/tamediaadsframework\/omidfriendlyobstructiontype\/equatable-implementations"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/OMIDFriendlyObstructionType/notVisible":{"role":"symbol","title":"OMIDFriendlyObstructionType.notVisible","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"notVisible"}],"abstract":[{"type":"text","text":"The friendly obstruction is not visibly obstructing the ad but may seem so due to technical"},{"type":"text","text":" "},{"type":"text","text":"limitations."}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDFriendlyObstructionType\/notVisible","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OMIDFriendlyObstructionNotVisible"}],"url":"\/documentation\/tamediaadsframework\/omidfriendlyobstructiontype\/notvisible"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/OMIDFriendlyObstructionType/closeAd":{"role":"symbol","title":"OMIDFriendlyObstructionType.closeAd","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"closeAd"}],"abstract":[{"type":"text","text":"The friendly obstruction relates to closing an ad (such as a close button)."}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDFriendlyObstructionType\/closeAd","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OMIDFriendlyObstructionCloseAd"}],"url":"\/documentation\/tamediaadsframework\/omidfriendlyobstructiontype\/closead"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/OMIDFriendlyObstructionType/mediaControls":{"role":"symbol","title":"OMIDFriendlyObstructionType.mediaControls","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"mediaControls"}],"abstract":[{"type":"text","text":"The friendly obstruction relates to interacting with a video (such as play\/pause buttons)."}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDFriendlyObstructionType\/mediaControls","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OMIDFriendlyObstructionMediaControls"}],"url":"\/documentation\/tamediaadsframework\/omidfriendlyobstructiontype\/mediacontrols"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/OMIDFriendlyObstructionType/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDFriendlyObstructionType\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/tamediaadsframework\/omidfriendlyobstructiontype\/init(rawvalue:)"},"doc://com.taiwanmobile.TAMediaAdsFramework/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/SQ"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/OMIDFriendlyObstructionType/other":{"role":"symbol","title":"OMIDFriendlyObstructionType.other","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"other"}],"abstract":[{"type":"text","text":"The friendly obstruction is obstructing for any purpose not already described."}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDFriendlyObstructionType\/other","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OMIDFriendlyObstructionOther"}],"url":"\/documentation\/tamediaadsframework\/omidfriendlyobstructiontype\/other"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/OMIDFriendlyObstructionType":{"role":"symbol","title":"OMIDFriendlyObstructionType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"OMIDFriendlyObstructionType"}],"abstract":[{"type":"text","text":"List of allowed friendly obstruction purposes."}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDFriendlyObstructionType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OMIDFriendlyObstructionType"}],"url":"\/documentation\/tamediaadsframework\/omidfriendlyobstructiontype"},"doc://com.taiwanmobile.TAMediaAdsFramework/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/s8SendableP"},"doc://com.taiwanmobile.TAMediaAdsFramework/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/SY"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"OMIDFriendlyObstructionType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"OMIDFriendlyObstructionType"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"OMIDFriendlyObstructionType"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDFriendlyObstructionType\/closeAd","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDFriendlyObstructionType\/mediaControls","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDFriendlyObstructionType\/notVisible","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDFriendlyObstructionType\/other"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"OMIDFriendlyObstructionType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDFriendlyObstructionType~1notVisible\/title","value":"OMIDFriendlyObstructionNotVisible"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDFriendlyObstructionType~1notVisible\/fragments","value":[{"kind":"identifier","text":"OMIDFriendlyObstructionNotVisible"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDFriendlyObstructionType~1closeAd\/title","value":"OMIDFriendlyObstructionCloseAd"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDFriendlyObstructionType~1closeAd\/fragments","value":[{"kind":"identifier","text":"OMIDFriendlyObstructionCloseAd"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDFriendlyObstructionType~1mediaControls\/title","value":"OMIDFriendlyObstructionMediaControls"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDFriendlyObstructionType~1mediaControls\/fragments","value":[{"kind":"identifier","text":"OMIDFriendlyObstructionMediaControls"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDFriendlyObstructionType~1other\/title","value":"OMIDFriendlyObstructionOther"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDFriendlyObstructionType~1other\/fragments","value":[{"kind":"identifier","text":"OMIDFriendlyObstructionOther"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDFriendlyObstructionType\/title","value":"OMIDFriendlyObstructionType"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDFriendlyObstructionType\/fragments","value":[{"kind":"identifier","text":"OMIDFriendlyObstructionType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}