{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OMIDTaiwanmobileSDK"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Note that OM SDK may only be used on the main UI thread."},{"type":"text","text":" "},{"type":"text","text":"Make sure you are on the main thread when you initialize the SDK, create its"},{"type":"text","text":" "},{"type":"text","text":"objects, and invoke its methods."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/tamediaadsframework\/omidtaiwanmobilesdk"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/tamediaadsframework\/omidtaiwanmobilesdk"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)NSObject","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/s7CVarArgP","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/s28CustomDebugStringConvertibleP","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/s23CustomStringConvertibleP","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/SQ","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileSDK","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This application level class will be called by all integration partners to ensure OM SDK has been activated before calling any other API methods."},{"type":"text","text":" "},{"type":"text","text":"Any attempt to use other API methods prior to activation will result in an error."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OMIDTaiwanmobileSDK"}],"title":"OMIDTaiwanmobileSDK","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)OMIDTaiwanmobileSDK","modules":[{"name":"TAMediaAdsFramework"}],"navigatorTitle":[{"kind":"identifier","text":"OMIDTaiwanmobileSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileSDK\/isActive"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileSDK\/activate()"]},{"title":"Type Properties","identifiers":["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileSDK\/shared"]},{"title":"Type Methods","identifiers":["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileSDK\/versionString()"]}],"references":{"doc://com.taiwanmobile.TAMediaAdsFramework/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/SQ"},"doc://com.taiwanmobile.TAMediaAdsFramework/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/s23CustomStringConvertibleP"},"doc://com.taiwanmobile.TAMediaAdsFramework/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/s7CVarArgP"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework":{"role":"collection","title":"TAMediaAdsFramework","abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","kind":"symbol","type":"topic","url":"\/documentation\/tamediaadsframework"},"doc://com.taiwanmobile.TAMediaAdsFramework/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(cs)NSObject"},"doc://com.taiwanmobile.TAMediaAdsFramework/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)NSObject"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/OMIDTaiwanmobileSDK/versionString()":{"role":"symbol","title":"versionString()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"versionString"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"The current semantic version of the integrated OMID library."}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileSDK\/versionString()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"versionString"}],"url":"\/documentation\/tamediaadsframework\/omidtaiwanmobilesdk\/versionstring()"},"doc://com.taiwanmobile.TAMediaAdsFramework/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/s28CustomDebugStringConvertibleP"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/OMIDTaiwanmobileSDK/isActive":{"role":"symbol","title":"isActive","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isActive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"A Boolean value indicating whether the OMID library has been activated."}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileSDK\/isActive","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"active"}],"url":"\/documentation\/tamediaadsframework\/omidtaiwanmobilesdk\/isactive"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/OMIDTaiwanmobileSDK":{"role":"symbol","title":"OMIDTaiwanmobileSDK","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OMIDTaiwanmobileSDK"}],"abstract":[{"type":"text","text":"This application level class will be called by all integration partners to ensure OM SDK has been activated before calling any other API methods."},{"type":"text","text":" "},{"type":"text","text":"Any attempt to use other API methods prior to activation will result in an error."}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileSDK","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OMIDTaiwanmobileSDK"}],"url":"\/documentation\/tamediaadsframework\/omidtaiwanmobilesdk"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/OMIDTaiwanmobileSDK/shared":{"role":"symbol","title":"shared","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shared"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"OMIDTaiwanmobileSDK","preciseIdentifier":"c:objc(cs)OMIDTaiwanmobileSDK"}],"abstract":[{"type":"text","text":"Shared OMIDSDK instance."}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileSDK\/shared","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sharedInstance"}],"url":"\/documentation\/tamediaadsframework\/omidtaiwanmobilesdk\/shared"},"doc://com.taiwanmobile.TAMediaAdsFramework/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/SH"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/OMIDTaiwanmobileSDK/activate()":{"role":"symbol","title":"activate()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"activate"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Enables the integration partner to activate OMID."}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileSDK\/activate()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"activate"}],"url":"\/documentation\/tamediaadsframework\/omidtaiwanmobilesdk\/activate()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"OMIDTaiwanmobileSDK"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"OMIDTaiwanmobileSDK"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"OMIDTaiwanmobileSDK"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileSDK\/isActive","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileSDK\/shared"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileSDK\/activate()"]},{"title":"Type Methods","identifiers":["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileSDK\/versionString()"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"OMIDTaiwanmobileSDK"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDTaiwanmobileSDK~1versionString()\/title","value":"versionString"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDTaiwanmobileSDK~1versionString()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"versionString"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDTaiwanmobileSDK~1isActive\/title","value":"active"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDTaiwanmobileSDK~1isActive\/fragments","value":[{"kind":"identifier","text":"active"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDTaiwanmobileSDK\/title","value":"OMIDTaiwanmobileSDK"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDTaiwanmobileSDK\/fragments","value":[{"kind":"identifier","text":"OMIDTaiwanmobileSDK"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDTaiwanmobileSDK~1shared\/title","value":"sharedInstance"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDTaiwanmobileSDK~1shared\/fragments","value":[{"kind":"identifier","text":"sharedInstance"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDTaiwanmobileSDK~1activate()\/title","value":"activate"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDTaiwanmobileSDK~1activate()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"activate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}