{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADAdSizeFromCGSize"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"size"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADAdSize","preciseIdentifier":"c:@S@TADAdSize","text":"TADAdSize"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/tamediaadsframework\/tadadsizefromcgsize(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/tamediaadsframework\/tadadsizefromcgsize(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADAdSizeFromCGSize(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"給定一個 CGSize，返回一個自定義的 TADAdSize。 僅當您需要非標準尺寸，"},{"type":"text","text":" "},{"type":"text","text":"否則，使用kTADAdSize其中一種尺寸設置。"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADAdSizeFromCGSize"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"TADAdSize","preciseIdentifier":"c:@S@TADAdSize"}],"title":"TADAdSizeFromCGSize(_:)","roleHeading":"Function","role":"symbol","symbolKind":"func","externalID":"c:@F@TADAdSizeFromCGSize","modules":[{"name":"TAMediaAdsFramework"}],"navigatorTitle":[{"kind":"identifier","text":"TADAdSizeFromCGSize"}]},"hierarchy":{"paths":[["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework"]]},"references":{"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADAdSize":{"role":"symbol","title":"TADAdSize","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADAdSize"}],"abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADAdSize","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TADAdSize"}],"url":"\/documentation\/tamediaadsframework\/tadadsize"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADAdSizeFromCGSize(_:)":{"role":"symbol","title":"TADAdSizeFromCGSize(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADAdSizeFromCGSize"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"TADAdSize","preciseIdentifier":"c:@S@TADAdSize"}],"abstract":[{"type":"text","text":"給定一個 CGSize，返回一個自定義的 TADAdSize。 僅當您需要非標準尺寸，"},{"type":"text","text":" "},{"type":"text","text":"否則，使用kTADAdSize其中一種尺寸設置。"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADAdSizeFromCGSize(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TADAdSizeFromCGSize"}],"url":"\/documentation\/tamediaadsframework\/tadadsizefromcgsize(_:)"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework":{"role":"collection","title":"TAMediaAdsFramework","abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","kind":"symbol","type":"topic","url":"\/documentation\/tamediaadsframework"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Function"},{"op":"replace","path":"\/metadata\/title","value":"TADAdSizeFromCGSize"},{"op":"replace","path":"\/metadata\/symbolKind","value":"func"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"TADAdSizeFromCGSize"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"typeIdentifier","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADAdSize","preciseIdentifier":"c:@S@TADAdSize","text":"TADAdSize"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADAdSizeFromCGSize"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":" "},{"kind":"internalParam","text":"size"},{"kind":"text","text":")"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADAdSize\/title","value":"TADAdSize"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADAdSize\/fragments","value":[{"kind":"identifier","text":"TADAdSize"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADAdSizeFromCGSize(_:)\/title","value":"TADAdSizeFromCGSize"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADAdSizeFromCGSize(_:)\/fragments","value":[{"kind":"identifier","text":"TADAdSizeFromCGSize"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}