{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADBannerView"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/tamediaadsframework\/tadbannerview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/tamediaadsframework\/tadbannerview"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)NSCoding","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)NSObject","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)CALayerDelegate","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/s7CVarArgP","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/s28CustomDebugStringConvertibleP","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/s23CustomStringConvertibleP","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/SQ","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/SH","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/s8SendableP","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UIAccessibilityIdentification","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UIAppearance","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UIAppearanceContainer","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UICoordinateSpace","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UIDynamicItem","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UIFocusEnvironment","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UIFocusItem","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UIFocusItemContainer","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UILargeContentViewerItem","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UITraitEnvironment","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADBannerView","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"顯示橫幅廣告的視圖。"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADBannerView"}],"title":"TADBannerView","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)TADBannerView","modules":[{"name":"TAMediaAdsFramework"}],"navigatorTitle":[{"kind":"identifier","text":"TADBannerView"}]},"hierarchy":{"paths":[["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADBannerView\/init(adSize:)","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADBannerView\/init(adSize:origin:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADBannerView\/adSize","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADBannerView\/adUnitID","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADBannerView\/delegate","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADBannerView\/hasAutoRefreshed","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADBannerView\/rootViewController","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADBannerView\/turnOnMicrophone"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADBannerView\/load(_:)"]}],"references":{"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADBannerView/delegate":{"role":"symbol","title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TADBannerViewDelegate","preciseIdentifier":"c:objc(pl)TADBannerViewDelegate"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"從TADNativeAd 接收狀態更改通知的可選委託對象。 請記住不使用此對象之前將委託設為 nil。"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADBannerView\/delegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"delegate"}],"url":"\/documentation\/tamediaadsframework\/tadbannerview\/delegate"},"doc://com.taiwanmobile.TAMediaAdsFramework/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/SQ"},"doc://com.taiwanmobile.TAMediaAdsFramework/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)NSObject"},"doc://com.taiwanmobile.TAMediaAdsFramework/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/s8SendableP"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADBannerView/load(_:)":{"role":"symbol","title":"load(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"load"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"TADRequest","preciseIdentifier":"c:objc(cs)TADRequest"},{"kind":"text","text":"!)"}],"abstract":[{"type":"text","text":"發出廣告請求。"},{"type":"text","text":" "},{"type":"text","text":"刷新廣告可通過再次調用此方法。"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADBannerView\/load(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"loadRequest:"}],"url":"\/documentation\/tamediaadsframework\/tadbannerview\/load(_:)"},"doc://com.taiwanmobile.TAMediaAdsFramework/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UIFocusItemContainer"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADBannerView/hasAutoRefreshed":{"role":"symbol","title":"hasAutoRefreshed","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hasAutoRefreshed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"自動刷新後回傳YES。"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADBannerView\/hasAutoRefreshed","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"hasAutoRefreshed"}],"url":"\/documentation\/tamediaadsframework\/tadbannerview\/hasautorefreshed"},"doc://com.taiwanmobile.TAMediaAdsFramework/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/s7CVarArgP"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework":{"role":"collection","title":"TAMediaAdsFramework","abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","kind":"symbol","type":"topic","url":"\/documentation\/tamediaadsframework"},"doc://com.taiwanmobile.TAMediaAdsFramework/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UIResponderStandardEditActions"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADBannerView/turnOnMicrophone":{"role":"symbol","title":"turnOnMicrophone","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"turnOnMicrophone"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"如果設置為 NO，則用戶無法與麥克風廣告互動，預設為 YES"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADBannerView\/turnOnMicrophone","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"turnOnMicrophone"}],"url":"\/documentation\/tamediaadsframework\/tadbannerview\/turnonmicrophone"},"doc://com.taiwanmobile.TAMediaAdsFramework/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UIFocusItem"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADBannerView/adUnitID":{"role":"symbol","title":"adUnitID","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"adUnitID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"由 TAMedia 提供的廣告 ID。"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADBannerView\/adUnitID","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"adUnitID"}],"url":"\/documentation\/tamediaadsframework\/tadbannerview\/adunitid"},"doc://com.taiwanmobile.TAMediaAdsFramework/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UIAppearanceContainer"},"doc://com.taiwanmobile.TAMediaAdsFramework/objc(pl)CALayerDelegate":{"type":"unresolvable","title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)CALayerDelegate"},"doc://com.taiwanmobile.TAMediaAdsFramework/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADBannerView/init(adSize:)":{"role":"symbol","title":"init(adSize:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"!("},{"kind":"externalParam","text":"adSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TADAdSize","preciseIdentifier":"c:@S@TADAdSize"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"初始化一個 TADBannerView 並將其設置為指定的大小。"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADBannerView\/init(adSize:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithAdSize:"}],"url":"\/documentation\/tamediaadsframework\/tadbannerview\/init(adsize:)"},"doc://com.taiwanmobile.TAMediaAdsFramework/objc(cs)UIView":{"type":"unresolvable","title":"UIView","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(cs)UIView"},"doc://com.taiwanmobile.TAMediaAdsFramework/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.taiwanmobile.TAMediaAdsFramework/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UIAccessibilityIdentification"},"doc://com.taiwanmobile.TAMediaAdsFramework/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/s23CustomStringConvertibleP"},"doc://com.taiwanmobile.TAMediaAdsFramework/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UIUserActivityRestoring"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADBannerView/rootViewController":{"role":"symbol","title":"rootViewController","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rootViewController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"必需引用當前的ViewController。"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADBannerView\/rootViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rootViewController"}],"url":"\/documentation\/tamediaadsframework\/tadbannerview\/rootviewcontroller"},"doc://com.taiwanmobile.TAMediaAdsFramework/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UIAppearance"},"doc://com.taiwanmobile.TAMediaAdsFramework/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UIDynamicItem"},"doc://com.taiwanmobile.TAMediaAdsFramework/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/s28CustomDebugStringConvertibleP"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADBannerView/init(adSize:origin:)":{"role":"symbol","title":"init(adSize:origin:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"!("},{"kind":"externalParam","text":"adSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TADAdSize","preciseIdentifier":"c:@S@TADAdSize"},{"kind":"text","text":", "},{"kind":"externalParam","text":"origin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"初始化一個 TADBannerView 並將其設置為指定的大小，並指定"},{"type":"text","text":" "},{"type":"text","text":"它在其父視圖邊界內的位置。如果size無效，TADBannerView 的實例無法被創建，將返回 nil。"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADBannerView\/init(adSize:origin:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithAdSize:origin:"}],"url":"\/documentation\/tamediaadsframework\/tadbannerview\/init(adsize:origin:)"},"doc://com.taiwanmobile.TAMediaAdsFramework/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UIFocusEnvironment"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADBannerView":{"role":"symbol","title":"TADBannerView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADBannerView"}],"abstract":[{"type":"text","text":"顯示橫幅廣告的視圖。"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADBannerView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TADBannerView"}],"url":"\/documentation\/tamediaadsframework\/tadbannerview"},"doc://com.taiwanmobile.TAMediaAdsFramework/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)NSCoding"},"doc://com.taiwanmobile.TAMediaAdsFramework/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADBannerView/adSize":{"role":"symbol","title":"adSize","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"adSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TADAdSize","preciseIdentifier":"c:@S@TADAdSize"}],"abstract":[{"type":"text","text":"需要將此橫幅視圖設置為適當的大小。永遠不要直接創建TADAdSize 。"},{"type":"text","text":" "},{"type":"text","text":"使用預定義的標準廣告尺寸之一（例如kTADAdSizeBanner），或者使用TADAdSizeFromCGSize創建一個。"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADBannerView\/adSize","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"adSize"}],"url":"\/documentation\/tamediaadsframework\/tadbannerview\/adsize"},"doc://com.taiwanmobile.TAMediaAdsFramework/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/SH"},"doc://com.taiwanmobile.TAMediaAdsFramework/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UITraitEnvironment"},"doc://com.taiwanmobile.TAMediaAdsFramework/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UILargeContentViewerItem"},"doc://com.taiwanmobile.TAMediaAdsFramework/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UICoordinateSpace"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"TADBannerView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"TADBannerView"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"TADBannerView"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADBannerView\/adSize","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADBannerView\/adUnitID","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADBannerView\/delegate","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADBannerView\/hasAutoRefreshed","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADBannerView\/rootViewController","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADBannerView\/turnOnMicrophone"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADBannerView\/init(adSize:)","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADBannerView\/init(adSize:origin:)","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADBannerView\/load(_:)"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADBannerView"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADBannerView~1delegate\/title","value":"delegate"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADBannerView~1delegate\/fragments","value":[{"kind":"identifier","text":"delegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADBannerView~1load(_:)\/title","value":"loadRequest:"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADBannerView~1load(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"loadRequest:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADBannerView~1hasAutoRefreshed\/title","value":"hasAutoRefreshed"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADBannerView~1hasAutoRefreshed\/fragments","value":[{"kind":"identifier","text":"hasAutoRefreshed"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADBannerView~1turnOnMicrophone\/title","value":"turnOnMicrophone"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADBannerView~1turnOnMicrophone\/fragments","value":[{"kind":"identifier","text":"turnOnMicrophone"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADBannerView~1adUnitID\/title","value":"adUnitID"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADBannerView~1adUnitID\/fragments","value":[{"kind":"identifier","text":"adUnitID"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADBannerView~1init(adSize:)\/title","value":"initWithAdSize:"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADBannerView~1init(adSize:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithAdSize:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADBannerView~1rootViewController\/title","value":"rootViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADBannerView~1rootViewController\/fragments","value":[{"kind":"identifier","text":"rootViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADBannerView~1init(adSize:origin:)\/title","value":"initWithAdSize:origin:"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADBannerView~1init(adSize:origin:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithAdSize:origin:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADBannerView\/title","value":"TADBannerView"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADBannerView\/fragments","value":[{"kind":"identifier","text":"TADBannerView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADBannerView~1adSize\/title","value":"adSize"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADBannerView~1adSize\/fragments","value":[{"kind":"identifier","text":"adSize"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}