{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADRequestError"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/tamediaadsframework\/tadrequesterror"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/tamediaadsframework\/tadrequesterror"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(cs)NSError"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)NSCoding","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)NSCopying","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)NSSecureCoding","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)NSObject","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/s7CVarArgP","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/s28CustomDebugStringConvertibleP","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/s23CustomStringConvertibleP","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/SQ","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/s5ErrorP","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/SH","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADRequestError","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Tamedia中定義的NSError資訊"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADRequestError"}],"title":"TADRequestError","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)TADRequestError","modules":[{"name":"TAMediaAdsFramework"}],"navigatorTitle":[{"kind":"identifier","text":"TADRequestError"}]},"hierarchy":{"paths":[["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADRequestError\/responseCode"]},{"title":"Type Methods","identifiers":["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADRequestError\/createTADRequest(withResponseCode:)","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADRequestError\/createTADRequestError(with:)-2xlxd","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADRequestError\/createTADRequestError(with:)-4pocy","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADRequestError\/createTADRequestNoSlotIdError()"]}],"references":{"doc://com.taiwanmobile.TAMediaAdsFramework/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/SH"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADRequestError":{"role":"symbol","title":"TADRequestError","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADRequestError"}],"abstract":[{"type":"text","text":"Tamedia中定義的NSError資訊"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADRequestError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TADRequestError"}],"url":"\/documentation\/tamediaadsframework\/tadrequesterror"},"doc://com.taiwanmobile.TAMediaAdsFramework/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/SQ"},"doc://com.taiwanmobile.TAMediaAdsFramework/objc(cs)NSError":{"type":"unresolvable","title":"NSError","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(cs)NSError"},"doc://com.taiwanmobile.TAMediaAdsFramework/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/s7CVarArgP"},"doc://com.taiwanmobile.TAMediaAdsFramework/objc(pl)NSSecureCoding":{"type":"unresolvable","title":"Foundation.NSSecureCoding","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)NSSecureCoding"},"doc://com.taiwanmobile.TAMediaAdsFramework/objc(pl)NSCopying":{"type":"unresolvable","title":"Foundation.NSCopying","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)NSCopying"},"doc://com.taiwanmobile.TAMediaAdsFramework/s5ErrorP":{"type":"unresolvable","title":"Swift.Error","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/s5ErrorP"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework":{"role":"collection","title":"TAMediaAdsFramework","abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","kind":"symbol","type":"topic","url":"\/documentation\/tamediaadsframework"},"doc://com.taiwanmobile.TAMediaAdsFramework/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/s23CustomStringConvertibleP"},"doc://com.taiwanmobile.TAMediaAdsFramework/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/s8SendableP"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADRequestError/createTADRequestNoSlotIdError()":{"role":"symbol","title":"createTADRequestNoSlotIdError()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createTADRequestNoSlotIdError"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"TADRequestError","preciseIdentifier":"c:objc(cs)TADRequestError"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADRequestError\/createTADRequestNoSlotIdError()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"createTADRequestNoSlotIdError"}],"url":"\/documentation\/tamediaadsframework\/tadrequesterror\/createtadrequestnoslotiderror()"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADRequestError/createTADRequest(withResponseCode:)":{"role":"symbol","title":"createTADRequest(withResponseCode:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createTADRequest"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withResponseCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"TADRequestError","preciseIdentifier":"c:objc(cs)TADRequestError"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADRequestError\/createTADRequest(withResponseCode:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"createTADRequestWithResponseCode:"}],"url":"\/documentation\/tamediaadsframework\/tadrequesterror\/createtadrequest(withresponsecode:)"},"doc://com.taiwanmobile.TAMediaAdsFramework/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/s28CustomDebugStringConvertibleP"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADRequestError/responseCode":{"role":"symbol","title":"responseCode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"responseCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADRequestError\/responseCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"responseCode"}],"url":"\/documentation\/tamediaadsframework\/tadrequesterror\/responsecode"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADRequestError/createTADRequestError(with:)-4pocy":{"role":"symbol","title":"createTADRequestError(with:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createTADRequestError"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TADErrorCode","preciseIdentifier":"c:@E@TADErrorCode"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"TADRequestError","preciseIdentifier":"c:objc(cs)TADRequestError"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADRequestError\/createTADRequestError(with:)-4pocy","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"createTADRequestErrorWithTADErrorCode:"}],"url":"\/documentation\/tamediaadsframework\/tadrequesterror\/createtadrequesterror(with:)-4pocy"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADRequestError/createTADRequestError(with:)-2xlxd":{"role":"symbol","title":"createTADRequestError(with:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createTADRequestError"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"TADRequestError","preciseIdentifier":"c:objc(cs)TADRequestError"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADRequestError\/createTADRequestError(with:)-2xlxd","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"createTADRequestErrorWithNSError:"}],"url":"\/documentation\/tamediaadsframework\/tadrequesterror\/createtadrequesterror(with:)-2xlxd"},"doc://com.taiwanmobile.TAMediaAdsFramework/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)NSObject"},"doc://com.taiwanmobile.TAMediaAdsFramework/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)NSCoding"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"TADRequestError"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"TADRequestError"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"TADRequestError"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADRequestError\/responseCode"]},{"title":"Type Methods","identifiers":["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADRequestError\/createTADRequest(withResponseCode:)","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADRequestError\/createTADRequestError(with:)-2xlxd","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADRequestError\/createTADRequestError(with:)-4pocy","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADRequestError\/createTADRequestNoSlotIdError()"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADRequestError"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADRequestError\/title","value":"TADRequestError"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADRequestError\/fragments","value":[{"kind":"identifier","text":"TADRequestError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADRequestError~1createTADRequestNoSlotIdError()\/title","value":"createTADRequestNoSlotIdError"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADRequestError~1createTADRequestNoSlotIdError()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createTADRequestNoSlotIdError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADRequestError~1createTADRequest(withResponseCode:)\/title","value":"createTADRequestWithResponseCode:"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADRequestError~1createTADRequest(withResponseCode:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createTADRequestWithResponseCode:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADRequestError~1responseCode\/title","value":"responseCode"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADRequestError~1responseCode\/fragments","value":[{"kind":"identifier","text":"responseCode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADRequestError~1createTADRequestError(with:)-4pocy\/title","value":"createTADRequestErrorWithTADErrorCode:"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADRequestError~1createTADRequestError(with:)-4pocy\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createTADRequestErrorWithTADErrorCode:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADRequestError~1createTADRequestError(with:)-2xlxd\/title","value":"createTADRequestErrorWithNSError:"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADRequestError~1createTADRequestError(with:)-2xlxd\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createTADRequestErrorWithNSError:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}