{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADVideoStatusDelegate"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/tamediaadsframework\/tadvideostatusdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/tamediaadsframework\/tadvideostatusdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADVideoStatusDelegate","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"影片播放事件回報"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADVideoStatusDelegate"}],"title":"TADVideoStatusDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:@M@TAMediaAdsFramework@objc(pl)TADVideoStatusDelegate","modules":[{"name":"TAMediaAdsFramework"}],"navigatorTitle":[{"kind":"identifier","text":"TADVideoStatusDelegate"}]},"hierarchy":{"paths":[["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADVideoStatusDelegate\/didEndVideoPlayback()","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADVideoStatusDelegate\/didMuteVideo()","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADVideoStatusDelegate\/didPauseVideo()","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADVideoStatusDelegate\/didPlayVideo()","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADVideoStatusDelegate\/didStartVideo()","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADVideoStatusDelegate\/didUnmuteVideo()"]}],"references":{"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADVideoStatusDelegate":{"role":"symbol","title":"TADVideoStatusDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADVideoStatusDelegate"}],"abstract":[{"type":"text","text":"影片播放事件回報"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADVideoStatusDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TADVideoStatusDelegate"}],"url":"\/documentation\/tamediaadsframework\/tadvideostatusdelegate"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADVideoStatusDelegate/didUnmuteVideo()":{"navigatorTitle":[{"kind":"identifier","text":"didUnmuteVideo"}],"role":"symbol","title":"didUnmuteVideo()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didUnmuteVideo"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"開啟影片聲音"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADVideoStatusDelegate\/didUnmuteVideo()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/tamediaadsframework\/tadvideostatusdelegate\/didunmutevideo()"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADVideoStatusDelegate/didMuteVideo()":{"navigatorTitle":[{"kind":"identifier","text":"didMuteVideo"}],"role":"symbol","title":"didMuteVideo()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didMuteVideo"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"關閉影片聲音"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADVideoStatusDelegate\/didMuteVideo()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/tamediaadsframework\/tadvideostatusdelegate\/didmutevideo()"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADVideoStatusDelegate/didPauseVideo()":{"navigatorTitle":[{"kind":"identifier","text":"didPauseVideo"}],"role":"symbol","title":"didPauseVideo()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didPauseVideo"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"影片暫停播放"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADVideoStatusDelegate\/didPauseVideo()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/tamediaadsframework\/tadvideostatusdelegate\/didpausevideo()"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADVideoStatusDelegate/didStartVideo()":{"navigatorTitle":[{"kind":"identifier","text":"didStartVideo"}],"role":"symbol","title":"didStartVideo()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didStartVideo"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"影片開始播放"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADVideoStatusDelegate\/didStartVideo()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/tamediaadsframework\/tadvideostatusdelegate\/didstartvideo()"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework":{"role":"collection","title":"TAMediaAdsFramework","abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","kind":"symbol","type":"topic","url":"\/documentation\/tamediaadsframework"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADVideoStatusDelegate/didEndVideoPlayback()":{"navigatorTitle":[{"kind":"identifier","text":"didEndVideoPlayback"}],"role":"symbol","title":"didEndVideoPlayback()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didEndVideoPlayback"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"影片播放完畢"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADVideoStatusDelegate\/didEndVideoPlayback()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/tamediaadsframework\/tadvideostatusdelegate\/didendvideoplayback()"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADVideoStatusDelegate/didPlayVideo()":{"navigatorTitle":[{"kind":"identifier","text":"didPlayVideo"}],"role":"symbol","title":"didPlayVideo()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didPlayVideo"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"影片繼續播放"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADVideoStatusDelegate\/didPlayVideo()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/tamediaadsframework\/tadvideostatusdelegate\/didplayvideo()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"TADVideoStatusDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"TADVideoStatusDelegate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"TADVideoStatusDelegate"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADVideoStatusDelegate\/didEndVideoPlayback()","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADVideoStatusDelegate\/didMuteVideo()","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADVideoStatusDelegate\/didPauseVideo()","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADVideoStatusDelegate\/didPlayVideo()","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADVideoStatusDelegate\/didStartVideo()","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADVideoStatusDelegate\/didUnmuteVideo()"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADVideoStatusDelegate"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADVideoStatusDelegate\/title","value":"TADVideoStatusDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADVideoStatusDelegate\/fragments","value":[{"kind":"identifier","text":"TADVideoStatusDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADVideoStatusDelegate~1didUnmuteVideo()\/title","value":"didUnmuteVideo"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADVideoStatusDelegate~1didUnmuteVideo()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didUnmuteVideo"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADVideoStatusDelegate~1didMuteVideo()\/title","value":"didMuteVideo"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADVideoStatusDelegate~1didMuteVideo()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didMuteVideo"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADVideoStatusDelegate~1didPauseVideo()\/title","value":"didPauseVideo"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADVideoStatusDelegate~1didPauseVideo()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didPauseVideo"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADVideoStatusDelegate~1didStartVideo()\/title","value":"didStartVideo"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADVideoStatusDelegate~1didStartVideo()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didStartVideo"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADVideoStatusDelegate~1didEndVideoPlayback()\/title","value":"didEndVideoPlayback"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADVideoStatusDelegate~1didEndVideoPlayback()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didEndVideoPlayback"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADVideoStatusDelegate~1didPlayVideo()\/title","value":"didPlayVideo"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADVideoStatusDelegate~1didPlayVideo()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didPlayVideo"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}