{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didMuteVideo"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/tamediaadsframework\/tadvideostatusdelegate\/didmutevideo()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/tamediaadsframework\/tadvideostatusdelegate\/didmutevideo()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADVideoStatusDelegate\/didMuteVideo()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"關閉影片聲音"}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"didMuteVideo"}],"role":"symbol","title":"didMuteVideo()","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didMuteVideo"},{"kind":"text","text":"()"}],"symbolKind":"method","externalID":"c:@M@TAMediaAdsFramework@objc(pl)TADVideoStatusDelegate(im)didMuteVideo","required":true,"modules":[{"name":"TAMediaAdsFramework"}]},"hierarchy":{"paths":[["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADVideoStatusDelegate"]]},"references":{"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADVideoStatusDelegate":{"role":"symbol","title":"TADVideoStatusDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADVideoStatusDelegate"}],"abstract":[{"type":"text","text":"影片播放事件回報"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADVideoStatusDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TADVideoStatusDelegate"}],"url":"\/documentation\/tamediaadsframework\/tadvideostatusdelegate"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADVideoStatusDelegate/didMuteVideo()":{"navigatorTitle":[{"kind":"identifier","text":"didMuteVideo"}],"role":"symbol","title":"didMuteVideo()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didMuteVideo"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"關閉影片聲音"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADVideoStatusDelegate\/didMuteVideo()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/tamediaadsframework\/tadvideostatusdelegate\/didmutevideo()"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework":{"role":"collection","title":"TAMediaAdsFramework","abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","kind":"symbol","type":"topic","url":"\/documentation\/tamediaadsframework"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"didMuteVideo"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didMuteVideo"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"didMuteVideo"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADVideoStatusDelegate\/title","value":"TADVideoStatusDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADVideoStatusDelegate\/fragments","value":[{"kind":"identifier","text":"TADVideoStatusDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADVideoStatusDelegate~1didMuteVideo()\/title","value":"didMuteVideo"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADVideoStatusDelegate~1didMuteVideo()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didMuteVideo"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}