{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didPauseVideo"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/tamediaadsframework\/tadvideostatusdelegate\/didpausevideo()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/tamediaadsframework\/tadvideostatusdelegate\/didpausevideo()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADVideoStatusDelegate\/didPauseVideo()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"影片暫停播放"}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"didPauseVideo"}],"role":"symbol","title":"didPauseVideo()","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didPauseVideo"},{"kind":"text","text":"()"}],"symbolKind":"method","externalID":"c:@M@TAMediaAdsFramework@objc(pl)TADVideoStatusDelegate(im)didPauseVideo","required":true,"modules":[{"name":"TAMediaAdsFramework"}]},"hierarchy":{"paths":[["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADVideoStatusDelegate"]]},"references":{"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADVideoStatusDelegate/didPauseVideo()":{"navigatorTitle":[{"kind":"identifier","text":"didPauseVideo"}],"role":"symbol","title":"didPauseVideo()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didPauseVideo"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"影片暫停播放"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADVideoStatusDelegate\/didPauseVideo()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/tamediaadsframework\/tadvideostatusdelegate\/didpausevideo()"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework":{"role":"collection","title":"TAMediaAdsFramework","abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","kind":"symbol","type":"topic","url":"\/documentation\/tamediaadsframework"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADVideoStatusDelegate":{"role":"symbol","title":"TADVideoStatusDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADVideoStatusDelegate"}],"abstract":[{"type":"text","text":"影片播放事件回報"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADVideoStatusDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TADVideoStatusDelegate"}],"url":"\/documentation\/tamediaadsframework\/tadvideostatusdelegate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"didPauseVideo"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didPauseVideo"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"didPauseVideo"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADVideoStatusDelegate~1didPauseVideo()\/title","value":"didPauseVideo"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADVideoStatusDelegate~1didPauseVideo()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didPauseVideo"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADVideoStatusDelegate\/title","value":"TADVideoStatusDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADVideoStatusDelegate\/fragments","value":[{"kind":"identifier","text":"TADVideoStatusDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}