{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"friendlyObstructions"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADFriendlyObstruction","preciseIdentifier":"c:@M@TAMediaAdsFramework@objc(cs)TADFriendlyObstruction","text":"TADFriendlyObstruction"},{"kind":"text","text":"] { get }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/tamediaadsframework\/tadnativeadview\/friendlyobstructions"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/tamediaadsframework\/tadnativeadview\/friendlyobstructions"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdView\/friendlyObstructions","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"friendlyObstructions"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"TADFriendlyObstruction","preciseIdentifier":"c:@M@TAMediaAdsFramework@objc(cs)TADFriendlyObstruction"},{"kind":"text","text":"]"}],"title":"friendlyObstructions","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@TAMediaAdsFramework@objc(cs)TADNativeAdView(py)friendlyObstructions","modules":[{"name":"TAMediaAdsFramework"}],"navigatorTitle":[{"kind":"identifier","text":"friendlyObstructions"}]},"hierarchy":{"paths":[["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdView"]]},"references":{"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework":{"role":"collection","title":"TAMediaAdsFramework","abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","kind":"symbol","type":"topic","url":"\/documentation\/tamediaadsframework"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADFriendlyObstruction":{"role":"symbol","title":"TADFriendlyObstruction","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADFriendlyObstruction"}],"abstract":[{"type":"text","text":"顯示在廣告頁面的障礙物，例如關閉按鈕，影音控制項"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADFriendlyObstruction","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TADFriendlyObstruction"}],"url":"\/documentation\/tamediaadsframework\/tadfriendlyobstruction"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADNativeAdView":{"role":"symbol","title":"TADNativeAdView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADNativeAdView"}],"abstract":[{"type":"text","text":"用於呈現 NativeAd 的視圖，內有 Label、ImageView、mediaView 等屬性可控制。"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TADNativeAdView"}],"url":"\/documentation\/tamediaadsframework\/tadnativeadview"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADNativeAdView/friendlyObstructions":{"role":"symbol","title":"friendlyObstructions","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"friendlyObstructions"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"TADFriendlyObstruction","preciseIdentifier":"c:@M@TAMediaAdsFramework@objc(cs)TADFriendlyObstruction"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdView\/friendlyObstructions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"friendlyObstructions"}],"url":"\/documentation\/tamediaadsframework\/tadnativeadview\/friendlyobstructions"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"friendlyObstructions"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"friendlyObstructions"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSArray<TADFriendlyObstruction *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *"},{"kind":"identifier","text":"friendlyObstructions"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADFriendlyObstruction\/title","value":"TADFriendlyObstruction"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADFriendlyObstruction\/fragments","value":[{"kind":"identifier","text":"TADFriendlyObstruction"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAdView\/title","value":"TADNativeAdView"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAdView\/fragments","value":[{"kind":"identifier","text":"TADNativeAdView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAdView~1friendlyObstructions\/title","value":"friendlyObstructions"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAdView~1friendlyObstructions\/fragments","value":[{"kind":"identifier","text":"friendlyObstructions"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}