{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"onePixel"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/tamediaadsframework\/omidimpressiontype\/onepixel"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/tamediaadsframework\/omidimpressiontype\/onepixel"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDImpressionType\/onePixel","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The integration is using one-pixel criteria (when the creative has at least 1 visible pixel on"},{"type":"text","text":" "},{"type":"text","text":"screen) for the OMID impression."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"onePixel"}],"title":"OMIDImpressionType.onePixel","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@OMIDImpressionType@OMIDImpressionTypeOnePixel","modules":[{"name":"TAMediaAdsFramework"}],"navigatorTitle":[{"kind":"identifier","text":"OMIDImpressionTypeOnePixel"}]},"hierarchy":{"paths":[["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDImpressionType"]]},"references":{"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/OMIDImpressionType/onePixel":{"role":"symbol","title":"OMIDImpressionType.onePixel","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"onePixel"}],"abstract":[{"type":"text","text":"The integration is using one-pixel criteria (when the creative has at least 1 visible pixel on"},{"type":"text","text":" "},{"type":"text","text":"screen) for the OMID impression."}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDImpressionType\/onePixel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OMIDImpressionTypeOnePixel"}],"url":"\/documentation\/tamediaadsframework\/omidimpressiontype\/onepixel"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework":{"role":"collection","title":"TAMediaAdsFramework","abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","kind":"symbol","type":"topic","url":"\/documentation\/tamediaadsframework"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/OMIDImpressionType":{"role":"symbol","title":"OMIDImpressionType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"OMIDImpressionType"}],"abstract":[{"type":"text","text":"The criterion for an ad session’s OMID impression event."},{"type":"text","text":" "},{"type":"text","text":"Declaring an impression type makes it easier to understand discrepancies between measurers"},{"type":"text","text":" "},{"type":"text","text":"of the ad session, since many metrics depend on impressions."}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDImpressionType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OMIDImpressionType"}],"url":"\/documentation\/tamediaadsframework\/omidimpressiontype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"OMIDImpressionTypeOnePixel"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"OMIDImpressionTypeOnePixel"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"OMIDImpressionTypeOnePixel"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDImpressionType~1onePixel\/title","value":"OMIDImpressionTypeOnePixel"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDImpressionType~1onePixel\/fragments","value":[{"kind":"identifier","text":"OMIDImpressionTypeOnePixel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDImpressionType\/title","value":"OMIDImpressionType"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDImpressionType\/fragments","value":[{"kind":"identifier","text":"OMIDImpressionType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}