{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"fullscreen"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/tamediaadsframework\/omidplayerstate\/fullscreen"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/tamediaadsframework\/omidplayerstate\/fullscreen"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDPlayerState\/fullscreen","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The player has entered fullscreen mode."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"fullscreen"}],"title":"OMIDPlayerState.fullscreen","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@OMIDPlayerState@OMIDPlayerStateFullscreen","modules":[{"name":"TAMediaAdsFramework"}],"navigatorTitle":[{"kind":"identifier","text":"OMIDPlayerStateFullscreen"}]},"hierarchy":{"paths":[["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDPlayerState"]]},"references":{"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework":{"role":"collection","title":"TAMediaAdsFramework","abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","kind":"symbol","type":"topic","url":"\/documentation\/tamediaadsframework"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/OMIDPlayerState/fullscreen":{"role":"symbol","title":"OMIDPlayerState.fullscreen","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"fullscreen"}],"abstract":[{"type":"text","text":"The player has entered fullscreen mode."}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDPlayerState\/fullscreen","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OMIDPlayerStateFullscreen"}],"url":"\/documentation\/tamediaadsframework\/omidplayerstate\/fullscreen"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/OMIDPlayerState":{"role":"symbol","title":"OMIDPlayerState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"OMIDPlayerState"}],"abstract":[{"type":"text","text":"List of supported media event player states."}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDPlayerState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OMIDPlayerState"}],"url":"\/documentation\/tamediaadsframework\/omidplayerstate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"OMIDPlayerStateFullscreen"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"OMIDPlayerStateFullscreen"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"OMIDPlayerStateFullscreen"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDPlayerState~1fullscreen\/title","value":"OMIDPlayerStateFullscreen"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDPlayerState~1fullscreen\/fragments","value":[{"kind":"identifier","text":"OMIDPlayerStateFullscreen"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDPlayerState\/title","value":"OMIDPlayerState"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDPlayerState\/fragments","value":[{"kind":"identifier","text":"OMIDPlayerState"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}