{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"FlagPortrait"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/tamediaadsframework\/tadadsizeflags\/flagportrait"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/tamediaadsframework\/tadadsizeflags\/flagportrait"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADAdSizeFlags\/FlagPortrait","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"SmartBannerPortrait"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"FlagPortrait"}],"title":"TADAdSizeFlags.FlagPortrait","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@TADAdSizeFlags@FlagPortrait","modules":[{"name":"TAMediaAdsFramework"}],"navigatorTitle":[{"kind":"identifier","text":"FlagPortrait"}]},"hierarchy":{"paths":[["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADAdSizeFlags"]]},"references":{"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADAdSizeFlags":{"role":"symbol","title":"TADAdSizeFlags","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADAdSizeFlags"}],"abstract":[{"type":"text","text":"AdSize標籤，用於分類不同廣告尺寸對應的標籤"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADAdSizeFlags","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TADAdSizeFlags"}],"url":"\/documentation\/tamediaadsframework\/tadadsizeflags"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADAdSizeFlags/FlagPortrait":{"role":"symbol","title":"TADAdSizeFlags.FlagPortrait","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"FlagPortrait"}],"abstract":[{"type":"text","text":"SmartBannerPortrait"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADAdSizeFlags\/FlagPortrait","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FlagPortrait"}],"url":"\/documentation\/tamediaadsframework\/tadadsizeflags\/flagportrait"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework":{"role":"collection","title":"TAMediaAdsFramework","abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","kind":"symbol","type":"topic","url":"\/documentation\/tamediaadsframework"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"FlagPortrait"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"FlagPortrait"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"FlagPortrait"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADAdSizeFlags\/title","value":"TADAdSizeFlags"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADAdSizeFlags\/fragments","value":[{"kind":"identifier","text":"TADAdSizeFlags"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADAdSizeFlags~1FlagPortrait\/title","value":"FlagPortrait"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADAdSizeFlags~1FlagPortrait\/fragments","value":[{"kind":"identifier","text":"FlagPortrait"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}