{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADVideoController","preciseIdentifier":"c:@M@TAMediaAdsFramework@objc(cs)TADVideoController","text":"TADVideoController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/tamediaadsframework\/tadnativeadmediacontent\/videocontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/tamediaadsframework\/tadnativeadmediacontent\/videocontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdMediaContent\/videoController","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"影片 playback 的控制物件"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TADVideoController","preciseIdentifier":"c:@M@TAMediaAdsFramework@objc(cs)TADVideoController"}],"title":"videoController","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@TAMediaAdsFramework@objc(cs)TADNativeAdMediaContent(py)videoController","modules":[{"name":"TAMediaAdsFramework"}],"navigatorTitle":[{"kind":"identifier","text":"videoController"}]},"hierarchy":{"paths":[["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdMediaContent"]]},"references":{"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADNativeAdMediaContent":{"role":"symbol","title":"TADNativeAdMediaContent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADNativeAdMediaContent"}],"abstract":[{"type":"text","text":"封裝原生廣告的 media 物件, 其中包含圖片和影片"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdMediaContent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TADNativeAdMediaContent"}],"url":"\/documentation\/tamediaadsframework\/tadnativeadmediacontent"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADVideoController":{"role":"symbol","title":"TADVideoController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADVideoController"}],"abstract":[{"type":"text","text":"影片 playback 的控制物件"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADVideoController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TADVideoController"}],"url":"\/documentation\/tamediaadsframework\/tadvideocontroller"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework":{"role":"collection","title":"TAMediaAdsFramework","abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","kind":"symbol","type":"topic","url":"\/documentation\/tamediaadsframework"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADNativeAdMediaContent/videoController":{"role":"symbol","title":"videoController","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TADVideoController","preciseIdentifier":"c:@M@TAMediaAdsFramework@objc(cs)TADVideoController"}],"abstract":[{"type":"text","text":"影片 playback 的控制物件"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdMediaContent\/videoController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"videoController"}],"url":"\/documentation\/tamediaadsframework\/tadnativeadmediacontent\/videocontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"videoController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"videoController"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADVideoController","preciseIdentifier":"c:@M@TAMediaAdsFramework@objc(cs)TADVideoController","text":"TADVideoController"},{"kind":"text","text":" *"},{"kind":"identifier","text":"videoController"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAdMediaContent\/title","value":"TADNativeAdMediaContent"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAdMediaContent\/fragments","value":[{"kind":"identifier","text":"TADNativeAdMediaContent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADVideoController\/title","value":"TADVideoController"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADVideoController\/fragments","value":[{"kind":"identifier","text":"TADVideoController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAdMediaContent~1videoController\/title","value":"videoController"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAdMediaContent~1videoController\/fragments","value":[{"kind":"identifier","text":"videoController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}