{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"impressionType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDImpressionType","preciseIdentifier":"c:@E@OMIDImpressionType","text":"OMIDImpressionType"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/tamediaadsframework\/omidtaiwanmobileadsessionconfiguration\/impressiontype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/tamediaadsframework\/omidtaiwanmobileadsessionconfiguration\/impressiontype"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileAdSessionConfiguration\/impressionType","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"impressionType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"OMIDImpressionType","preciseIdentifier":"c:@E@OMIDImpressionType"}],"title":"impressionType","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)OMIDTaiwanmobileAdSessionConfiguration(py)impressionType","modules":[{"name":"TAMediaAdsFramework"}],"navigatorTitle":[{"kind":"identifier","text":"impressionType"}]},"hierarchy":{"paths":[["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileAdSessionConfiguration"]]},"references":{"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/OMIDTaiwanmobileAdSessionConfiguration":{"role":"symbol","title":"OMIDTaiwanmobileAdSessionConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OMIDTaiwanmobileAdSessionConfiguration"}],"abstract":[{"type":"text","text":"The ad session configuration supplies the owner for both the impression and video events."},{"type":"text","text":" "},{"type":"text","text":"The OM SDK JS service will use this information to help identify where the source of these"},{"type":"text","text":" "},{"type":"text","text":"events is expected to be received."}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileAdSessionConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OMIDTaiwanmobileAdSessionConfiguration"}],"url":"\/documentation\/tamediaadsframework\/omidtaiwanmobileadsessionconfiguration"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/OMIDImpressionType":{"role":"symbol","title":"OMIDImpressionType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"OMIDImpressionType"}],"abstract":[{"type":"text","text":"The criterion for an ad session’s OMID impression event."},{"type":"text","text":" "},{"type":"text","text":"Declaring an impression type makes it easier to understand discrepancies between measurers"},{"type":"text","text":" "},{"type":"text","text":"of the ad session, since many metrics depend on impressions."}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDImpressionType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OMIDImpressionType"}],"url":"\/documentation\/tamediaadsframework\/omidimpressiontype"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework":{"role":"collection","title":"TAMediaAdsFramework","abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","kind":"symbol","type":"topic","url":"\/documentation\/tamediaadsframework"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/OMIDTaiwanmobileAdSessionConfiguration/impressionType":{"role":"symbol","title":"impressionType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"impressionType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"OMIDImpressionType","preciseIdentifier":"c:@E@OMIDImpressionType"}],"abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileAdSessionConfiguration\/impressionType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"impressionType"}],"url":"\/documentation\/tamediaadsframework\/omidtaiwanmobileadsessionconfiguration\/impressiontype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"impressionType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"impressionType"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"atomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDImpressionType","preciseIdentifier":"c:@E@OMIDImpressionType","text":"OMIDImpressionType"},{"kind":"identifier","text":"impressionType"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDTaiwanmobileAdSessionConfiguration\/title","value":"OMIDTaiwanmobileAdSessionConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDTaiwanmobileAdSessionConfiguration\/fragments","value":[{"kind":"identifier","text":"OMIDTaiwanmobileAdSessionConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDImpressionType\/title","value":"OMIDImpressionType"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDImpressionType\/fragments","value":[{"kind":"identifier","text":"OMIDImpressionType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDTaiwanmobileAdSessionConfiguration~1impressionType\/title","value":"impressionType"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDTaiwanmobileAdSessionConfiguration~1impressionType\/fragments","value":[{"kind":"identifier","text":"impressionType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}