{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"creativeType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDCreativeType","preciseIdentifier":"c:@E@OMIDCreativeType","text":"OMIDCreativeType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"impressionType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDImpressionType","preciseIdentifier":"c:@E@OMIDImpressionType","text":"OMIDImpressionType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"impressionOwner"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDOwner","preciseIdentifier":"c:@E@OMIDOwner","text":"OMIDOwner"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mediaEventsOwner"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDOwner","preciseIdentifier":"c:@E@OMIDOwner","text":"OMIDOwner"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isolateVerificationScripts"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"the impression event."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"supplying media events. This needs to be set only for non-display ad sessions and can be set to"},{"type":"text","text":" "},{"type":"codeVoice","code":"OMIDNoneOwner"},{"type":"text","text":" for display. When the creativeType is "},{"type":"codeVoice","code":"OMIDCreativeTypeDefinedByJavaScript"},{"type":"text","text":" then"},{"type":"text","text":" "},{"type":"text","text":"this should be set to "},{"type":"codeVoice","code":"OMIDJavaScriptOwner"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"sandboxed environment. This will not have any effect for native sessions."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"or arguments are invalid."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/tamediaadsframework\/omidtaiwanmobileadsessionconfiguration\/init(creativetype:impressiontype:impressionowner:mediaeventsowner:isolateverificationscripts:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/tamediaadsframework\/omidtaiwanmobileadsessionconfiguration\/init(creativetype:impressiontype:impressionowner:mediaeventsowner:isolateverificationscripts:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileAdSessionConfiguration\/init(creativeType:impressionType:impressionOwner:mediaEventsOwner:isolateVerificationScripts:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Create new ad session configuration supplying the owner for both the impression and media"},{"type":"text","text":" "},{"type":"text","text":"events along with the type of creative being rendered\/measured."},{"type":"text","text":" "},{"type":"text","text":"The OM SDK JS service will use this information to help identify where the source of these"},{"type":"text","text":" "},{"type":"text","text":"events is expected to be received."}],"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"creativeType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"OMIDCreativeType","preciseIdentifier":"c:@E@OMIDCreativeType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"impressionType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"OMIDImpressionType","preciseIdentifier":"c:@E@OMIDImpressionType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"impressionOwner"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"OMIDOwner","preciseIdentifier":"c:@E@OMIDOwner"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mediaEventsOwner"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"OMIDOwner","preciseIdentifier":"c:@E@OMIDOwner"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isolateVerificationScripts"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"title":"init(creativeType:impressionType:impressionOwner:mediaEventsOwner:isolateVerificationScripts:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:objc(cs)OMIDTaiwanmobileAdSessionConfiguration(im)initWithCreativeType:impressionType:impressionOwner:mediaEventsOwner:isolateVerificationScripts:error:","modules":[{"name":"TAMediaAdsFramework"}],"navigatorTitle":[{"kind":"identifier","text":"initWithCreativeType:impressionType:impressionOwner:mediaEventsOwner:isolateVerificationScripts:error:"}]},"hierarchy":{"paths":[["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileAdSessionConfiguration"]]},"references":{"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/OMIDImpressionType":{"role":"symbol","title":"OMIDImpressionType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"OMIDImpressionType"}],"abstract":[{"type":"text","text":"The criterion for an ad session’s OMID impression event."},{"type":"text","text":" "},{"type":"text","text":"Declaring an impression type makes it easier to understand discrepancies between measurers"},{"type":"text","text":" "},{"type":"text","text":"of the ad session, since many metrics depend on impressions."}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDImpressionType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OMIDImpressionType"}],"url":"\/documentation\/tamediaadsframework\/omidimpressiontype"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/OMIDTaiwanmobileAdSessionConfiguration":{"role":"symbol","title":"OMIDTaiwanmobileAdSessionConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OMIDTaiwanmobileAdSessionConfiguration"}],"abstract":[{"type":"text","text":"The ad session configuration supplies the owner for both the impression and video events."},{"type":"text","text":" "},{"type":"text","text":"The OM SDK JS service will use this information to help identify where the source of these"},{"type":"text","text":" "},{"type":"text","text":"events is expected to be received."}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileAdSessionConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OMIDTaiwanmobileAdSessionConfiguration"}],"url":"\/documentation\/tamediaadsframework\/omidtaiwanmobileadsessionconfiguration"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework":{"role":"collection","title":"TAMediaAdsFramework","abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","kind":"symbol","type":"topic","url":"\/documentation\/tamediaadsframework"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/OMIDCreativeType":{"role":"symbol","title":"OMIDCreativeType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"OMIDCreativeType"}],"abstract":[{"type":"text","text":"List of supported creative types."}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDCreativeType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OMIDCreativeType"}],"url":"\/documentation\/tamediaadsframework\/omidcreativetype"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/OMIDTaiwanmobileAdSessionConfiguration/init(creativeType:impressionType:impressionOwner:mediaEventsOwner:isolateVerificationScripts:)":{"role":"symbol","title":"init(creativeType:impressionType:impressionOwner:mediaEventsOwner:isolateVerificationScripts:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"creativeType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"OMIDCreativeType","preciseIdentifier":"c:@E@OMIDCreativeType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"impressionType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"OMIDImpressionType","preciseIdentifier":"c:@E@OMIDImpressionType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"impressionOwner"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"OMIDOwner","preciseIdentifier":"c:@E@OMIDOwner"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mediaEventsOwner"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"OMIDOwner","preciseIdentifier":"c:@E@OMIDOwner"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isolateVerificationScripts"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[{"type":"text","text":"Create new ad session configuration supplying the owner for both the impression and media"},{"type":"text","text":" "},{"type":"text","text":"events along with the type of creative being rendered\/measured."},{"type":"text","text":" "},{"type":"text","text":"The OM SDK JS service will use this information to help identify where the source of these"},{"type":"text","text":" "},{"type":"text","text":"events is expected to be received."}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileAdSessionConfiguration\/init(creativeType:impressionType:impressionOwner:mediaEventsOwner:isolateVerificationScripts:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCreativeType:impressionType:impressionOwner:mediaEventsOwner:isolateVerificationScripts:error:"}],"url":"\/documentation\/tamediaadsframework\/omidtaiwanmobileadsessionconfiguration\/init(creativetype:impressiontype:impressionowner:mediaeventsowner:isolateverificationscripts:)"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/OMIDOwner":{"role":"symbol","title":"OMIDOwner","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"OMIDOwner"}],"abstract":[{"type":"text","text":"Identifies which integration layer is responsible for sending certain events."}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDOwner","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OMIDOwner"}],"url":"\/documentation\/tamediaadsframework\/omidowner"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithCreativeType:impressionType:impressionOwner:mediaEventsOwner:isolateVerificationScripts:error:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCreativeType:impressionType:impressionOwner:mediaEventsOwner:isolateVerificationScripts:error:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithCreativeType:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDCreativeType","preciseIdentifier":"c:@E@OMIDCreativeType","text":"OMIDCreativeType"},{"kind":"text","text":")"},{"kind":"internalParam","text":"creativeType"},{"kind":"text","text":" "},{"kind":"identifier","text":"impressionType:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDImpressionType","preciseIdentifier":"c:@E@OMIDImpressionType","text":"OMIDImpressionType"},{"kind":"text","text":")"},{"kind":"internalParam","text":"impressionType"},{"kind":"text","text":" "},{"kind":"identifier","text":"impressionOwner:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDOwner","preciseIdentifier":"c:@E@OMIDOwner","text":"OMIDOwner"},{"kind":"text","text":")"},{"kind":"internalParam","text":"impressionOwner"},{"kind":"text","text":" "},{"kind":"identifier","text":"mediaEventsOwner:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDOwner","preciseIdentifier":"c:@E@OMIDOwner","text":"OMIDOwner"},{"kind":"text","text":")"},{"kind":"internalParam","text":"mediaEventsOwner"},{"kind":"text","text":" "},{"kind":"identifier","text":"isolateVerificationScripts:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":")"},{"kind":"internalParam","text":"isolateVerificationScripts"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" * *)"},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDImpressionType\/title","value":"OMIDImpressionType"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDImpressionType\/fragments","value":[{"kind":"identifier","text":"OMIDImpressionType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDTaiwanmobileAdSessionConfiguration\/title","value":"OMIDTaiwanmobileAdSessionConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDTaiwanmobileAdSessionConfiguration\/fragments","value":[{"kind":"identifier","text":"OMIDTaiwanmobileAdSessionConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDCreativeType\/title","value":"OMIDCreativeType"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDCreativeType\/fragments","value":[{"kind":"identifier","text":"OMIDCreativeType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDTaiwanmobileAdSessionConfiguration~1init(creativeType:impressionType:impressionOwner:mediaEventsOwner:isolateVerificationScripts:)\/title","value":"initWithCreativeType:impressionType:impressionOwner:mediaEventsOwner:isolateVerificationScripts:error:"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDTaiwanmobileAdSessionConfiguration~1init(creativeType:impressionType:impressionOwner:mediaEventsOwner:isolateVerificationScripts:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCreativeType:impressionType:impressionOwner:mediaEventsOwner:isolateVerificationScripts:error:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDOwner\/title","value":"OMIDOwner"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDOwner\/fragments","value":[{"kind":"identifier","text":"OMIDOwner"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}