{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"purpose"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADFriendlyObstructionPurpose","preciseIdentifier":"c:@M@TAMediaAdsFramework@E@TADFriendyObstrucitonPurpose","text":"TADFriendlyObstructionPurpose"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/tamediaadsframework\/tadfriendlyobstruction\/purpose"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/tamediaadsframework\/tadfriendlyobstruction\/purpose"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADFriendlyObstruction\/purpose","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"障礙物類型"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADFriendlyObstructionPurpose"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"purpose"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TADFriendlyObstructionPurpose","preciseIdentifier":"c:@M@TAMediaAdsFramework@E@TADFriendyObstrucitonPurpose"}],"title":"purpose","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@TAMediaAdsFramework@objc(cs)TADFriendlyObstruction(py)purpose","modules":[{"name":"TAMediaAdsFramework"}],"navigatorTitle":[{"kind":"identifier","text":"purpose"}]},"hierarchy":{"paths":[["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADFriendlyObstruction"]]},"references":{"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADFriendlyObstructionPurpose":{"role":"symbol","title":"TADFriendlyObstructionPurpose","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADFriendlyObstructionPurpose"}],"abstract":[{"type":"text","text":"顯示在廣告頁面的障礙物類型"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADFriendlyObstructionPurpose","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TADFriendlyObstructionPurpose"}],"url":"\/documentation\/tamediaadsframework\/tadfriendlyobstructionpurpose"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADFriendlyObstruction":{"role":"symbol","title":"TADFriendlyObstruction","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADFriendlyObstruction"}],"abstract":[{"type":"text","text":"顯示在廣告頁面的障礙物，例如關閉按鈕，影音控制項"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADFriendlyObstruction","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TADFriendlyObstruction"}],"url":"\/documentation\/tamediaadsframework\/tadfriendlyobstruction"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework":{"role":"collection","title":"TAMediaAdsFramework","abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","kind":"symbol","type":"topic","url":"\/documentation\/tamediaadsframework"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADFriendlyObstruction/purpose":{"role":"symbol","title":"purpose","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"purpose"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TADFriendlyObstructionPurpose","preciseIdentifier":"c:@M@TAMediaAdsFramework@E@TADFriendyObstrucitonPurpose"}],"abstract":[{"type":"text","text":"障礙物類型"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADFriendlyObstructionPurpose"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADFriendlyObstruction\/purpose","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"purpose"}],"url":"\/documentation\/tamediaadsframework\/tadfriendlyobstruction\/purpose"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"purpose"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"purpose"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADFriendlyObstructionPurpose","preciseIdentifier":"c:@M@TAMediaAdsFramework@E@TADFriendyObstrucitonPurpose","text":"TADFriendyObstrucitonPurpose"},{"kind":"identifier","text":"purpose"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADFriendlyObstructionPurpose\/title","value":"TADFriendyObstrucitonPurpose"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADFriendlyObstructionPurpose\/fragments","value":[{"kind":"identifier","text":"TADFriendyObstrucitonPurpose"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADFriendlyObstruction\/title","value":"TADFriendlyObstruction"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADFriendlyObstruction\/fragments","value":[{"kind":"identifier","text":"TADFriendlyObstruction"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADFriendlyObstruction~1purpose\/title","value":"purpose"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADFriendlyObstruction~1purpose\/fragments","value":[{"kind":"identifier","text":"purpose"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}