{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"adView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"view"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADBannerView","preciseIdentifier":"c:objc(cs)TADBannerView","text":"TADBannerView"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"didFailToReceiveAdWithError"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADRequestError","preciseIdentifier":"c:objc(cs)TADRequestError","text":"TADRequestError"},{"kind":"text","text":"!)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/tamediaadsframework\/tadbannerviewdelegate\/adview(_:didfailtoreceiveadwitherror:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/tamediaadsframework\/tadbannerviewdelegate\/adview(_:didfailtoreceiveadwitherror:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADBannerViewDelegate\/adView(_:didFailToReceiveAdWithError:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"廣告取得失敗"}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"adView:didFailToReceiveAdWithError:"}],"role":"symbol","title":"adView(_:didFailToReceiveAdWithError:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"adView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"TADBannerView","preciseIdentifier":"c:objc(cs)TADBannerView"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"didFailToReceiveAdWithError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TADRequestError","preciseIdentifier":"c:objc(cs)TADRequestError"},{"kind":"text","text":"!)"}],"symbolKind":"method","externalID":"c:objc(pl)TADBannerViewDelegate(im)adView:didFailToReceiveAdWithError:","required":true,"modules":[{"name":"TAMediaAdsFramework"}]},"hierarchy":{"paths":[["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADBannerViewDelegate"]]},"references":{"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADBannerViewDelegate/adView(_:didFailToReceiveAdWithError:)":{"navigatorTitle":[{"kind":"identifier","text":"adView:didFailToReceiveAdWithError:"}],"role":"symbol","title":"adView(_:didFailToReceiveAdWithError:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"adView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"TADBannerView","preciseIdentifier":"c:objc(cs)TADBannerView"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"didFailToReceiveAdWithError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TADRequestError","preciseIdentifier":"c:objc(cs)TADRequestError"},{"kind":"text","text":"!)"}],"abstract":[{"type":"text","text":"廣告取得失敗"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADBannerViewDelegate\/adView(_:didFailToReceiveAdWithError:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/tamediaadsframework\/tadbannerviewdelegate\/adview(_:didfailtoreceiveadwitherror:)"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADBannerViewDelegate":{"role":"symbol","title":"TADBannerViewDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADBannerViewDelegate"}],"abstract":[{"type":"text","text":"用於從 TADBannerView 接收狀態更改消息的委託，例如廣告請求成功\/失敗或點擊廣告時。"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADBannerViewDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TADBannerViewDelegate"}],"url":"\/documentation\/tamediaadsframework\/tadbannerviewdelegate"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADRequestError":{"role":"symbol","title":"TADRequestError","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADRequestError"}],"abstract":[{"type":"text","text":"Tamedia中定義的NSError資訊"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADRequestError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TADRequestError"}],"url":"\/documentation\/tamediaadsframework\/tadrequesterror"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADBannerView":{"role":"symbol","title":"TADBannerView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADBannerView"}],"abstract":[{"type":"text","text":"顯示橫幅廣告的視圖。"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADBannerView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TADBannerView"}],"url":"\/documentation\/tamediaadsframework\/tadbannerview"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework":{"role":"collection","title":"TAMediaAdsFramework","abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","kind":"symbol","type":"topic","url":"\/documentation\/tamediaadsframework"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"adView:didFailToReceiveAdWithError:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"adView:didFailToReceiveAdWithError:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"adView:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADBannerView","preciseIdentifier":"c:objc(cs)TADBannerView","text":"TADBannerView"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"view"},{"kind":"text","text":" "},{"kind":"identifier","text":"didFailToReceiveAdWithError:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADRequestError","preciseIdentifier":"c:objc(cs)TADRequestError","text":"TADRequestError"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADBannerViewDelegate~1adView(_:didFailToReceiveAdWithError:)\/title","value":"adView:didFailToReceiveAdWithError:"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADBannerViewDelegate~1adView(_:didFailToReceiveAdWithError:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"adView:didFailToReceiveAdWithError:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADBannerViewDelegate\/title","value":"TADBannerViewDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADBannerViewDelegate\/fragments","value":[{"kind":"identifier","text":"TADBannerViewDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADRequestError\/title","value":"TADRequestError"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADRequestError\/fragments","value":[{"kind":"identifier","text":"TADRequestError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADBannerView\/title","value":"TADBannerView"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADBannerView\/fragments","value":[{"kind":"identifier","text":"TADBannerView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}