{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"htmlDisplay"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/tamediaadsframework\/omidcreativetype\/htmldisplay"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/tamediaadsframework\/omidcreativetype\/htmldisplay"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDCreativeType\/htmlDisplay","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Rendered in webview, verification code can be inside creative or in metadata."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"htmlDisplay"}],"title":"OMIDCreativeType.htmlDisplay","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@OMIDCreativeType@OMIDCreativeTypeHtmlDisplay","modules":[{"name":"TAMediaAdsFramework"}],"navigatorTitle":[{"kind":"identifier","text":"OMIDCreativeTypeHtmlDisplay"}]},"hierarchy":{"paths":[["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDCreativeType"]]},"references":{"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/OMIDCreativeType/htmlDisplay":{"role":"symbol","title":"OMIDCreativeType.htmlDisplay","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"htmlDisplay"}],"abstract":[{"type":"text","text":"Rendered in webview, verification code can be inside creative or in metadata."}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDCreativeType\/htmlDisplay","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OMIDCreativeTypeHtmlDisplay"}],"url":"\/documentation\/tamediaadsframework\/omidcreativetype\/htmldisplay"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/OMIDCreativeType":{"role":"symbol","title":"OMIDCreativeType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"OMIDCreativeType"}],"abstract":[{"type":"text","text":"List of supported creative types."}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDCreativeType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OMIDCreativeType"}],"url":"\/documentation\/tamediaadsframework\/omidcreativetype"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework":{"role":"collection","title":"TAMediaAdsFramework","abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","kind":"symbol","type":"topic","url":"\/documentation\/tamediaadsframework"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"OMIDCreativeTypeHtmlDisplay"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"OMIDCreativeTypeHtmlDisplay"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"OMIDCreativeTypeHtmlDisplay"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDCreativeType~1htmlDisplay\/title","value":"OMIDCreativeTypeHtmlDisplay"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDCreativeType~1htmlDisplay\/fragments","value":[{"kind":"identifier","text":"OMIDCreativeTypeHtmlDisplay"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDCreativeType\/title","value":"OMIDCreativeType"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDCreativeType\/fragments","value":[{"kind":"identifier","text":"OMIDCreativeType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}