{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"skipOffset"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"autoPlay"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"position"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDPosition","preciseIdentifier":"c:@E@OMIDPosition","text":"OMIDPosition"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/tamediaadsframework\/omidtaiwanmobilevastproperties\/init(skipoffset:autoplay:position:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/tamediaadsframework\/omidtaiwanmobilevastproperties\/init(skipoffset:autoplay:position:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileVASTProperties\/init(skipOffset:autoPlay:position:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This method enables the media player to create a new VAST properties instance for skippable media ad placement."}],"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"skipOffset"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"autoPlay"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"position"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"OMIDPosition","preciseIdentifier":"c:@E@OMIDPosition"},{"kind":"text","text":")"}],"title":"init(skipOffset:autoPlay:position:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:objc(cs)OMIDTaiwanmobileVASTProperties(im)initWithSkipOffset:autoPlay:position:","modules":[{"name":"TAMediaAdsFramework"}],"navigatorTitle":[{"kind":"identifier","text":"initWithSkipOffset:autoPlay:position:"}]},"hierarchy":{"paths":[["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileVASTProperties"]]},"references":{"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/OMIDPosition":{"role":"symbol","title":"OMIDPosition","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"OMIDPosition"}],"abstract":[{"type":"text","text":"List of supported media player positions."}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDPosition","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OMIDPosition"}],"url":"\/documentation\/tamediaadsframework\/omidposition"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/OMIDTaiwanmobileVASTProperties":{"role":"symbol","title":"OMIDTaiwanmobileVASTProperties","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OMIDTaiwanmobileVASTProperties"}],"abstract":[{"type":"text","text":"This object is used to capture key VAST properties so this can be shared with all registered verification providers."}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileVASTProperties","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OMIDTaiwanmobileVASTProperties"}],"url":"\/documentation\/tamediaadsframework\/omidtaiwanmobilevastproperties"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/OMIDTaiwanmobileVASTProperties/init(skipOffset:autoPlay:position:)":{"role":"symbol","title":"init(skipOffset:autoPlay:position:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"skipOffset"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"autoPlay"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"position"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"OMIDPosition","preciseIdentifier":"c:@E@OMIDPosition"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"This method enables the media player to create a new VAST properties instance for skippable media ad placement."}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileVASTProperties\/init(skipOffset:autoPlay:position:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithSkipOffset:autoPlay:position:"}],"url":"\/documentation\/tamediaadsframework\/omidtaiwanmobilevastproperties\/init(skipoffset:autoplay:position:)"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework":{"role":"collection","title":"TAMediaAdsFramework","abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","kind":"symbol","type":"topic","url":"\/documentation\/tamediaadsframework"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithSkipOffset:autoPlay:position:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithSkipOffset:autoPlay:position:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithSkipOffset:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"c:@T@CGFloat"},{"kind":"text","text":")"},{"kind":"internalParam","text":"skipOffset"},{"kind":"text","text":" "},{"kind":"identifier","text":"autoPlay:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":")"},{"kind":"internalParam","text":"autoPlay"},{"kind":"text","text":" "},{"kind":"identifier","text":"position:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDPosition","preciseIdentifier":"c:@E@OMIDPosition","text":"OMIDPosition"},{"kind":"text","text":")"},{"kind":"internalParam","text":"position"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDPosition\/title","value":"OMIDPosition"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDPosition\/fragments","value":[{"kind":"identifier","text":"OMIDPosition"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDTaiwanmobileVASTProperties\/title","value":"OMIDTaiwanmobileVASTProperties"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDTaiwanmobileVASTProperties\/fragments","value":[{"kind":"identifier","text":"OMIDTaiwanmobileVASTProperties"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDTaiwanmobileVASTProperties~1init(skipOffset:autoPlay:position:)\/title","value":"initWithSkipOffset:autoPlay:position:"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDTaiwanmobileVASTProperties~1init(skipOffset:autoPlay:position:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithSkipOffset:autoPlay:position:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}