{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"nativeDisplay"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/tamediaadsframework\/omidcreativetype\/nativedisplay"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/tamediaadsframework\/omidcreativetype\/nativedisplay"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDCreativeType\/nativeDisplay","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Rendered by native, verification code provided in metadata only."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"nativeDisplay"}],"title":"OMIDCreativeType.nativeDisplay","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@OMIDCreativeType@OMIDCreativeTypeNativeDisplay","modules":[{"name":"TAMediaAdsFramework"}],"navigatorTitle":[{"kind":"identifier","text":"OMIDCreativeTypeNativeDisplay"}]},"hierarchy":{"paths":[["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDCreativeType"]]},"references":{"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/OMIDCreativeType":{"role":"symbol","title":"OMIDCreativeType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"OMIDCreativeType"}],"abstract":[{"type":"text","text":"List of supported creative types."}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDCreativeType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OMIDCreativeType"}],"url":"\/documentation\/tamediaadsframework\/omidcreativetype"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/OMIDCreativeType/nativeDisplay":{"role":"symbol","title":"OMIDCreativeType.nativeDisplay","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"nativeDisplay"}],"abstract":[{"type":"text","text":"Rendered by native, verification code provided in metadata only."}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDCreativeType\/nativeDisplay","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OMIDCreativeTypeNativeDisplay"}],"url":"\/documentation\/tamediaadsframework\/omidcreativetype\/nativedisplay"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework":{"role":"collection","title":"TAMediaAdsFramework","abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","kind":"symbol","type":"topic","url":"\/documentation\/tamediaadsframework"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"OMIDCreativeTypeNativeDisplay"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"OMIDCreativeTypeNativeDisplay"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"OMIDCreativeTypeNativeDisplay"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDCreativeType\/title","value":"OMIDCreativeType"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDCreativeType\/fragments","value":[{"kind":"identifier","text":"OMIDCreativeType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDCreativeType~1nativeDisplay\/title","value":"OMIDCreativeTypeNativeDisplay"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDCreativeType~1nativeDisplay\/fragments","value":[{"kind":"identifier","text":"OMIDCreativeTypeNativeDisplay"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}