{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"closeAd"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/tamediaadsframework\/tadfriendlyobstructionpurpose\/closead"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/tamediaadsframework\/tadfriendlyobstructionpurpose\/closead"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADFriendlyObstructionPurpose\/closeAd","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"關閉廣告的障礙物（例如關閉按鈕）。"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"closeAd"}],"title":"TADFriendlyObstructionPurpose.closeAd","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@TAMediaAdsFramework@E@TADFriendyObstrucitonPurpose@TADFriendyObstrucitonPurposeCloseAd","modules":[{"name":"TAMediaAdsFramework"}],"navigatorTitle":[{"kind":"identifier","text":"TADFriendyObstrucitonPurposeCloseAd"}]},"hierarchy":{"paths":[["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADFriendlyObstructionPurpose"]]},"references":{"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADFriendlyObstructionPurpose/closeAd":{"role":"symbol","title":"TADFriendlyObstructionPurpose.closeAd","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"closeAd"}],"abstract":[{"type":"text","text":"關閉廣告的障礙物（例如關閉按鈕）。"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADFriendlyObstructionPurpose\/closeAd","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TADFriendyObstrucitonPurposeCloseAd"}],"url":"\/documentation\/tamediaadsframework\/tadfriendlyobstructionpurpose\/closead"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADFriendlyObstructionPurpose":{"role":"symbol","title":"TADFriendlyObstructionPurpose","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADFriendlyObstructionPurpose"}],"abstract":[{"type":"text","text":"顯示在廣告頁面的障礙物類型"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADFriendlyObstructionPurpose","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TADFriendlyObstructionPurpose"}],"url":"\/documentation\/tamediaadsframework\/tadfriendlyobstructionpurpose"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework":{"role":"collection","title":"TAMediaAdsFramework","abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","kind":"symbol","type":"topic","url":"\/documentation\/tamediaadsframework"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"TADFriendyObstrucitonPurposeCloseAd"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"TADFriendyObstrucitonPurposeCloseAd"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"TADFriendyObstrucitonPurposeCloseAd"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADFriendlyObstructionPurpose~1closeAd\/title","value":"TADFriendyObstrucitonPurposeCloseAd"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADFriendlyObstructionPurpose~1closeAd\/fragments","value":[{"kind":"identifier","text":"TADFriendyObstrucitonPurposeCloseAd"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADFriendlyObstructionPurpose\/title","value":"TADFriendyObstrucitonPurpose"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADFriendlyObstructionPurpose\/fragments","value":[{"kind":"identifier","text":"TADFriendyObstrucitonPurpose"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}