{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"other"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/tamediaadsframework\/tadfriendlyobstructionpurpose\/other"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/tamediaadsframework\/tadfriendlyobstructionpurpose\/other"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADFriendlyObstructionPurpose\/other","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"出於尚未描述的任何目的而進行的障礙物。"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"other"}],"title":"TADFriendlyObstructionPurpose.other","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@TAMediaAdsFramework@E@TADFriendyObstrucitonPurpose@TADFriendyObstrucitonPurposeOther","modules":[{"name":"TAMediaAdsFramework"}],"navigatorTitle":[{"kind":"identifier","text":"TADFriendyObstrucitonPurposeOther"}]},"hierarchy":{"paths":[["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADFriendlyObstructionPurpose"]]},"references":{"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADFriendlyObstructionPurpose":{"role":"symbol","title":"TADFriendlyObstructionPurpose","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADFriendlyObstructionPurpose"}],"abstract":[{"type":"text","text":"顯示在廣告頁面的障礙物類型"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADFriendlyObstructionPurpose","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TADFriendlyObstructionPurpose"}],"url":"\/documentation\/tamediaadsframework\/tadfriendlyobstructionpurpose"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework":{"role":"collection","title":"TAMediaAdsFramework","abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","kind":"symbol","type":"topic","url":"\/documentation\/tamediaadsframework"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADFriendlyObstructionPurpose/other":{"role":"symbol","title":"TADFriendlyObstructionPurpose.other","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"other"}],"abstract":[{"type":"text","text":"出於尚未描述的任何目的而進行的障礙物。"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADFriendlyObstructionPurpose\/other","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TADFriendyObstrucitonPurposeOther"}],"url":"\/documentation\/tamediaadsframework\/tadfriendlyobstructionpurpose\/other"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"TADFriendyObstrucitonPurposeOther"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"TADFriendyObstrucitonPurposeOther"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"TADFriendyObstrucitonPurposeOther"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADFriendlyObstructionPurpose\/title","value":"TADFriendyObstrucitonPurpose"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADFriendlyObstructionPurpose\/fragments","value":[{"kind":"identifier","text":"TADFriendyObstrucitonPurpose"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADFriendlyObstructionPurpose~1other\/title","value":"TADFriendyObstrucitonPurposeOther"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADFriendlyObstructionPurpose~1other\/fragments","value":[{"kind":"identifier","text":"TADFriendyObstrucitonPurposeOther"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}