{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"disableImageLoading"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/tamediaadsframework\/tadnativeadoptions\/disableimageloading"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/tamediaadsframework\/tadnativeadoptions\/disableimageloading"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdOptions\/disableImageLoading","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"SDK 將自動下載原生廣告中的圖片內容，"},{"type":"text","text":" "},{"type":"text","text":"將此屬性設置為true，則SDK不會下載圖片，TADNativeAdImage中的圖片將為nil。"},{"type":"text","text":" "},{"type":"text","text":"默認值為false。"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"disableImageLoading"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"disableImageLoading","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@TAMediaAdsFramework@objc(cs)TADNativeAdOptions(py)disableImageLoading","modules":[{"name":"TAMediaAdsFramework"}],"navigatorTitle":[{"kind":"identifier","text":"disableImageLoading"}]},"hierarchy":{"paths":[["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdOptions"]]},"references":{"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADNativeAdOptions/disableImageLoading":{"role":"symbol","title":"disableImageLoading","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"disableImageLoading"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"SDK 將自動下載原生廣告中的圖片內容，"},{"type":"text","text":" "},{"type":"text","text":"將此屬性設置為true，則SDK不會下載圖片，TADNativeAdImage中的圖片將為nil。"},{"type":"text","text":" "},{"type":"text","text":"默認值為false。"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdOptions\/disableImageLoading","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"disableImageLoading"}],"url":"\/documentation\/tamediaadsframework\/tadnativeadoptions\/disableimageloading"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADNativeAdOptions":{"role":"symbol","title":"TADNativeAdOptions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADNativeAdOptions"}],"abstract":[{"type":"text","text":"用於 NativeAd 的可選控制項"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdOptions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TADNativeAdOptions"}],"url":"\/documentation\/tamediaadsframework\/tadnativeadoptions"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework":{"role":"collection","title":"TAMediaAdsFramework","abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","kind":"symbol","type":"topic","url":"\/documentation\/tamediaadsframework"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"disableImageLoading"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"disableImageLoading"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"identifier","text":"disableImageLoading"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAdOptions~1disableImageLoading\/title","value":"disableImageLoading"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAdOptions~1disableImageLoading\/fragments","value":[{"kind":"identifier","text":"disableImageLoading"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAdOptions\/title","value":"TADNativeAdOptions"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAdOptions\/fragments","value":[{"kind":"identifier","text":"TADNativeAdOptions"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}