{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"playerStateChange"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"kind":"text","text":" "},{"kind":"internalParam","text":"playerState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDPlayerState","preciseIdentifier":"c:@E@OMIDPlayerState","text":"OMIDPlayerState"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/tamediaadsframework\/omidtaiwanmobilemediaevents\/playerstatechange(to:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/tamediaadsframework\/omidtaiwanmobilemediaevents\/playerstatechange(to:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileMediaEvents\/playerStateChange(to:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Notifies all media listeners that media player state has changed."},{"type":"text","text":" "},{"type":"text","text":"See "},{"type":"codeVoice","code":"OMIDPlayerState"},{"type":"text","text":" for list of supported states."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"playerStateChange"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"OMIDPlayerState","preciseIdentifier":"c:@E@OMIDPlayerState"},{"kind":"text","text":")"}],"title":"playerStateChange(to:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)OMIDTaiwanmobileMediaEvents(im)playerStateChangeTo:","modules":[{"name":"TAMediaAdsFramework"}],"navigatorTitle":[{"kind":"identifier","text":"playerStateChangeTo:"}]},"hierarchy":{"paths":[["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileMediaEvents"]]},"references":{"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/OMIDTaiwanmobileMediaEvents":{"role":"symbol","title":"OMIDTaiwanmobileMediaEvents","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OMIDTaiwanmobileMediaEvents"}],"abstract":[{"type":"text","text":"This provides a complete list of native media events supported by OMID."},{"type":"text","text":" "},{"type":"text","text":"Using this event API assumes the media player is fully responsible for communicating all media events at the appropriate times."},{"type":"text","text":" "},{"type":"text","text":"Only one media events implementation can be associated with the ad session and any attempt to create multiple instances will result in an error."}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileMediaEvents","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OMIDTaiwanmobileMediaEvents"}],"url":"\/documentation\/tamediaadsframework\/omidtaiwanmobilemediaevents"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/OMIDPlayerState":{"role":"symbol","title":"OMIDPlayerState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"OMIDPlayerState"}],"abstract":[{"type":"text","text":"List of supported media event player states."}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDPlayerState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OMIDPlayerState"}],"url":"\/documentation\/tamediaadsframework\/omidplayerstate"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework":{"role":"collection","title":"TAMediaAdsFramework","abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","kind":"symbol","type":"topic","url":"\/documentation\/tamediaadsframework"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/OMIDTaiwanmobileMediaEvents/playerStateChange(to:)":{"role":"symbol","title":"playerStateChange(to:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"playerStateChange"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"OMIDPlayerState","preciseIdentifier":"c:@E@OMIDPlayerState"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Notifies all media listeners that media player state has changed."},{"type":"text","text":" "},{"type":"text","text":"See "},{"type":"codeVoice","code":"OMIDPlayerState"},{"type":"text","text":" for list of supported states."}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileMediaEvents\/playerStateChange(to:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"playerStateChangeTo:"}],"url":"\/documentation\/tamediaadsframework\/omidtaiwanmobilemediaevents\/playerstatechange(to:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"playerStateChangeTo:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"playerStateChangeTo:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"playerStateChangeTo:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDPlayerState","preciseIdentifier":"c:@E@OMIDPlayerState","text":"OMIDPlayerState"},{"kind":"text","text":")"},{"kind":"internalParam","text":"playerState"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDTaiwanmobileMediaEvents\/title","value":"OMIDTaiwanmobileMediaEvents"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDTaiwanmobileMediaEvents\/fragments","value":[{"kind":"identifier","text":"OMIDTaiwanmobileMediaEvents"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDPlayerState\/title","value":"OMIDPlayerState"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDPlayerState\/fragments","value":[{"kind":"identifier","text":"OMIDPlayerState"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDTaiwanmobileMediaEvents~1playerStateChange(to:)\/title","value":"playerStateChangeTo:"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDTaiwanmobileMediaEvents~1playerStateChange(to:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"playerStateChangeTo:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}