{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"adUserInteraction"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withType"},{"kind":"text","text":" "},{"kind":"internalParam","text":"interactionType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDInteractionType","preciseIdentifier":"c:@E@OMIDInteractionType","text":"OMIDInteractionType"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/tamediaadsframework\/omidtaiwanmobilemediaevents\/aduserinteraction(withtype:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/tamediaadsframework\/omidtaiwanmobilemediaevents\/aduserinteraction(withtype:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileMediaEvents\/adUserInteraction(withType:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Notifies all media listeners that the user has performed an ad interaction."},{"type":"text","text":" "},{"type":"text","text":"See "},{"type":"codeVoice","code":"OMIDInteractionType"},{"type":"text","text":" for a list of supported types."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"adUserInteraction"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"OMIDInteractionType","preciseIdentifier":"c:@E@OMIDInteractionType"},{"kind":"text","text":")"}],"title":"adUserInteraction(withType:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)OMIDTaiwanmobileMediaEvents(im)adUserInteractionWithType:","modules":[{"name":"TAMediaAdsFramework"}],"navigatorTitle":[{"kind":"identifier","text":"adUserInteractionWithType:"}]},"hierarchy":{"paths":[["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileMediaEvents"]]},"references":{"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/OMIDTaiwanmobileMediaEvents/adUserInteraction(withType:)":{"role":"symbol","title":"adUserInteraction(withType:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"adUserInteraction"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"OMIDInteractionType","preciseIdentifier":"c:@E@OMIDInteractionType"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Notifies all media listeners that the user has performed an ad interaction."},{"type":"text","text":" "},{"type":"text","text":"See "},{"type":"codeVoice","code":"OMIDInteractionType"},{"type":"text","text":" for a list of supported types."}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileMediaEvents\/adUserInteraction(withType:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"adUserInteractionWithType:"}],"url":"\/documentation\/tamediaadsframework\/omidtaiwanmobilemediaevents\/aduserinteraction(withtype:)"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/OMIDTaiwanmobileMediaEvents":{"role":"symbol","title":"OMIDTaiwanmobileMediaEvents","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OMIDTaiwanmobileMediaEvents"}],"abstract":[{"type":"text","text":"This provides a complete list of native media events supported by OMID."},{"type":"text","text":" "},{"type":"text","text":"Using this event API assumes the media player is fully responsible for communicating all media events at the appropriate times."},{"type":"text","text":" "},{"type":"text","text":"Only one media events implementation can be associated with the ad session and any attempt to create multiple instances will result in an error."}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileMediaEvents","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OMIDTaiwanmobileMediaEvents"}],"url":"\/documentation\/tamediaadsframework\/omidtaiwanmobilemediaevents"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/OMIDInteractionType":{"role":"symbol","title":"OMIDInteractionType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"OMIDInteractionType"}],"abstract":[{"type":"text","text":"List of supported media event user interaction types."}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDInteractionType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OMIDInteractionType"}],"url":"\/documentation\/tamediaadsframework\/omidinteractiontype"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework":{"role":"collection","title":"TAMediaAdsFramework","abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","kind":"symbol","type":"topic","url":"\/documentation\/tamediaadsframework"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"adUserInteractionWithType:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"adUserInteractionWithType:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"adUserInteractionWithType:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDInteractionType","preciseIdentifier":"c:@E@OMIDInteractionType","text":"OMIDInteractionType"},{"kind":"text","text":")"},{"kind":"internalParam","text":"interactionType"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDTaiwanmobileMediaEvents~1adUserInteraction(withType:)\/title","value":"adUserInteractionWithType:"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDTaiwanmobileMediaEvents~1adUserInteraction(withType:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"adUserInteractionWithType:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDTaiwanmobileMediaEvents\/title","value":"OMIDTaiwanmobileMediaEvents"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDTaiwanmobileMediaEvents\/fragments","value":[{"kind":"identifier","text":"OMIDTaiwanmobileMediaEvents"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDInteractionType\/title","value":"OMIDInteractionType"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDInteractionType\/fragments","value":[{"kind":"identifier","text":"OMIDInteractionType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}