{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewable"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/tamediaadsframework\/omidimpressiontype\/viewable"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/tamediaadsframework\/omidimpressiontype\/viewable"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDImpressionType\/viewable","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The integration is using viewable criteria (1 second for display, 2 seconds while playing for"},{"type":"text","text":" "},{"type":"text","text":"video, and at least 50% of the creative is visible) for the OMID impression."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewable"}],"title":"OMIDImpressionType.viewable","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@OMIDImpressionType@OMIDImpressionTypeViewable","modules":[{"name":"TAMediaAdsFramework"}],"navigatorTitle":[{"kind":"identifier","text":"OMIDImpressionTypeViewable"}]},"hierarchy":{"paths":[["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDImpressionType"]]},"references":{"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/OMIDImpressionType":{"role":"symbol","title":"OMIDImpressionType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"OMIDImpressionType"}],"abstract":[{"type":"text","text":"The criterion for an ad session’s OMID impression event."},{"type":"text","text":" "},{"type":"text","text":"Declaring an impression type makes it easier to understand discrepancies between measurers"},{"type":"text","text":" "},{"type":"text","text":"of the ad session, since many metrics depend on impressions."}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDImpressionType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OMIDImpressionType"}],"url":"\/documentation\/tamediaadsframework\/omidimpressiontype"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/OMIDImpressionType/viewable":{"role":"symbol","title":"OMIDImpressionType.viewable","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewable"}],"abstract":[{"type":"text","text":"The integration is using viewable criteria (1 second for display, 2 seconds while playing for"},{"type":"text","text":" "},{"type":"text","text":"video, and at least 50% of the creative is visible) for the OMID impression."}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDImpressionType\/viewable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OMIDImpressionTypeViewable"}],"url":"\/documentation\/tamediaadsframework\/omidimpressiontype\/viewable"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework":{"role":"collection","title":"TAMediaAdsFramework","abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","kind":"symbol","type":"topic","url":"\/documentation\/tamediaadsframework"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"OMIDImpressionTypeViewable"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"OMIDImpressionTypeViewable"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"OMIDImpressionTypeViewable"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDImpressionType\/title","value":"OMIDImpressionType"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDImpressionType\/fragments","value":[{"kind":"identifier","text":"OMIDImpressionType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDImpressionType~1viewable\/title","value":"OMIDImpressionTypeViewable"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDImpressionType~1viewable\/fragments","value":[{"kind":"identifier","text":"OMIDImpressionTypeViewable"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}