{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createTADRequestError"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"kind":"internalParam","text":"errorCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADErrorCode","preciseIdentifier":"c:@E@TADErrorCode","text":"TADErrorCode"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADRequestError","preciseIdentifier":"c:objc(cs)TADRequestError","text":"TADRequestError"},{"kind":"text","text":"!"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/tamediaadsframework\/tadrequesterror\/createtadrequesterror(with:)-4pocy"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/tamediaadsframework\/tadrequesterror\/createtadrequesterror(with:)-4pocy"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADRequestError\/createTADRequestError(with:)-4pocy","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createTADRequestError"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TADErrorCode","preciseIdentifier":"c:@E@TADErrorCode"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"TADRequestError","preciseIdentifier":"c:objc(cs)TADRequestError"},{"kind":"text","text":"!"}],"title":"createTADRequestError(with:)","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)TADRequestError(cm)createTADRequestErrorWithTADErrorCode:","modules":[{"name":"TAMediaAdsFramework"}],"navigatorTitle":[{"kind":"identifier","text":"createTADRequestErrorWithTADErrorCode:"}]},"hierarchy":{"paths":[["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADRequestError"]]},"references":{"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADErrorCode":{"role":"symbol","title":"TADErrorCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADErrorCode"}],"abstract":[{"type":"text","text":"TAmedia中定義的NSError資訊"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADErrorCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TADErrorCode"}],"url":"\/documentation\/tamediaadsframework\/taderrorcode"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADRequestError/createTADRequestError(with:)-4pocy":{"role":"symbol","title":"createTADRequestError(with:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createTADRequestError"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TADErrorCode","preciseIdentifier":"c:@E@TADErrorCode"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"TADRequestError","preciseIdentifier":"c:objc(cs)TADRequestError"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADRequestError\/createTADRequestError(with:)-4pocy","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"createTADRequestErrorWithTADErrorCode:"}],"url":"\/documentation\/tamediaadsframework\/tadrequesterror\/createtadrequesterror(with:)-4pocy"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework":{"role":"collection","title":"TAMediaAdsFramework","abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","kind":"symbol","type":"topic","url":"\/documentation\/tamediaadsframework"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADRequestError":{"role":"symbol","title":"TADRequestError","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADRequestError"}],"abstract":[{"type":"text","text":"Tamedia中定義的NSError資訊"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADRequestError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TADRequestError"}],"url":"\/documentation\/tamediaadsframework\/tadrequesterror"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"createTADRequestErrorWithTADErrorCode:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createTADRequestErrorWithTADErrorCode:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADRequestError","preciseIdentifier":"c:objc(cs)TADRequestError","text":"TADRequestError"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"createTADRequestErrorWithTADErrorCode:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADErrorCode","preciseIdentifier":"c:@E@TADErrorCode","text":"TADErrorCode"},{"kind":"text","text":")"},{"kind":"internalParam","text":"errorCode"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADErrorCode\/title","value":"TADErrorCode"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADErrorCode\/fragments","value":[{"kind":"identifier","text":"TADErrorCode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADRequestError~1createTADRequestError(with:)-4pocy\/title","value":"createTADRequestErrorWithTADErrorCode:"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADRequestError~1createTADRequestError(with:)-4pocy\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createTADRequestErrorWithTADErrorCode:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADRequestError\/title","value":"TADRequestError"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADRequestError\/fragments","value":[{"kind":"identifier","text":"TADRequestError"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}