{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"mediaControls"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/tamediaadsframework\/omidfriendlyobstructiontype\/mediacontrols"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/tamediaadsframework\/omidfriendlyobstructiontype\/mediacontrols"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDFriendlyObstructionType\/mediaControls","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The friendly obstruction relates to interacting with a video (such as play\/pause buttons)."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"mediaControls"}],"title":"OMIDFriendlyObstructionType.mediaControls","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@OMIDFriendlyObstructionType@OMIDFriendlyObstructionMediaControls","modules":[{"name":"TAMediaAdsFramework"}],"navigatorTitle":[{"kind":"identifier","text":"OMIDFriendlyObstructionMediaControls"}]},"hierarchy":{"paths":[["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDFriendlyObstructionType"]]},"references":{"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/OMIDFriendlyObstructionType":{"role":"symbol","title":"OMIDFriendlyObstructionType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"OMIDFriendlyObstructionType"}],"abstract":[{"type":"text","text":"List of allowed friendly obstruction purposes."}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDFriendlyObstructionType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OMIDFriendlyObstructionType"}],"url":"\/documentation\/tamediaadsframework\/omidfriendlyobstructiontype"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/OMIDFriendlyObstructionType/mediaControls":{"role":"symbol","title":"OMIDFriendlyObstructionType.mediaControls","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"mediaControls"}],"abstract":[{"type":"text","text":"The friendly obstruction relates to interacting with a video (such as play\/pause buttons)."}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDFriendlyObstructionType\/mediaControls","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OMIDFriendlyObstructionMediaControls"}],"url":"\/documentation\/tamediaadsframework\/omidfriendlyobstructiontype\/mediacontrols"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework":{"role":"collection","title":"TAMediaAdsFramework","abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","kind":"symbol","type":"topic","url":"\/documentation\/tamediaadsframework"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"OMIDFriendlyObstructionMediaControls"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"OMIDFriendlyObstructionMediaControls"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"OMIDFriendlyObstructionMediaControls"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDFriendlyObstructionType\/title","value":"OMIDFriendlyObstructionType"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDFriendlyObstructionType\/fragments","value":[{"kind":"identifier","text":"OMIDFriendlyObstructionType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDFriendlyObstructionType~1mediaControls\/title","value":"OMIDFriendlyObstructionMediaControls"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDFriendlyObstructionType~1mediaControls\/fragments","value":[{"kind":"identifier","text":"OMIDFriendlyObstructionMediaControls"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}