{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"other"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/tamediaadsframework\/omidfriendlyobstructiontype\/other"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/tamediaadsframework\/omidfriendlyobstructiontype\/other"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDFriendlyObstructionType\/other","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The friendly obstruction is obstructing for any purpose not already described."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"other"}],"title":"OMIDFriendlyObstructionType.other","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@OMIDFriendlyObstructionType@OMIDFriendlyObstructionOther","modules":[{"name":"TAMediaAdsFramework"}],"navigatorTitle":[{"kind":"identifier","text":"OMIDFriendlyObstructionOther"}]},"hierarchy":{"paths":[["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDFriendlyObstructionType"]]},"references":{"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework":{"role":"collection","title":"TAMediaAdsFramework","abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","kind":"symbol","type":"topic","url":"\/documentation\/tamediaadsframework"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/OMIDFriendlyObstructionType/other":{"role":"symbol","title":"OMIDFriendlyObstructionType.other","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"other"}],"abstract":[{"type":"text","text":"The friendly obstruction is obstructing for any purpose not already described."}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDFriendlyObstructionType\/other","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OMIDFriendlyObstructionOther"}],"url":"\/documentation\/tamediaadsframework\/omidfriendlyobstructiontype\/other"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/OMIDFriendlyObstructionType":{"role":"symbol","title":"OMIDFriendlyObstructionType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"OMIDFriendlyObstructionType"}],"abstract":[{"type":"text","text":"List of allowed friendly obstruction purposes."}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDFriendlyObstructionType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OMIDFriendlyObstructionType"}],"url":"\/documentation\/tamediaadsframework\/omidfriendlyobstructiontype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"OMIDFriendlyObstructionOther"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"OMIDFriendlyObstructionOther"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"OMIDFriendlyObstructionOther"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDFriendlyObstructionType~1other\/title","value":"OMIDFriendlyObstructionOther"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDFriendlyObstructionType~1other\/fragments","value":[{"kind":"identifier","text":"OMIDFriendlyObstructionOther"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDFriendlyObstructionType\/title","value":"OMIDFriendlyObstructionType"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDFriendlyObstructionType\/fragments","value":[{"kind":"identifier","text":"OMIDFriendlyObstructionType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}