{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"adSession"},{"kind":"text","text":" "},{"kind":"internalParam","text":"session"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileAdSession","preciseIdentifier":"c:objc(cs)OMIDTaiwanmobileAdSession","text":"OMIDTaiwanmobileAdSession"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/tamediaadsframework\/omidtaiwanmobilemediaevents\/init(adsession:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/tamediaadsframework\/omidtaiwanmobilemediaevents\/init(adsession:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileMediaEvents\/init(adSession:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Initializes media events instance for the associated ad session."},{"type":"text","text":" "},{"type":"text","text":"Any attempt to create a media events instance will fail if the supplied ad session has already started."}],"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"adSession"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"OMIDTaiwanmobileAdSession","preciseIdentifier":"c:objc(cs)OMIDTaiwanmobileAdSession"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"title":"init(adSession:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:objc(cs)OMIDTaiwanmobileMediaEvents(im)initWithAdSession:error:","modules":[{"name":"TAMediaAdsFramework"}],"navigatorTitle":[{"kind":"identifier","text":"initWithAdSession:error:"}]},"hierarchy":{"paths":[["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileMediaEvents"]]},"references":{"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/OMIDTaiwanmobileMediaEvents":{"role":"symbol","title":"OMIDTaiwanmobileMediaEvents","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OMIDTaiwanmobileMediaEvents"}],"abstract":[{"type":"text","text":"This provides a complete list of native media events supported by OMID."},{"type":"text","text":" "},{"type":"text","text":"Using this event API assumes the media player is fully responsible for communicating all media events at the appropriate times."},{"type":"text","text":" "},{"type":"text","text":"Only one media events implementation can be associated with the ad session and any attempt to create multiple instances will result in an error."}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileMediaEvents","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OMIDTaiwanmobileMediaEvents"}],"url":"\/documentation\/tamediaadsframework\/omidtaiwanmobilemediaevents"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/OMIDTaiwanmobileAdSession":{"role":"symbol","title":"OMIDTaiwanmobileAdSession","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OMIDTaiwanmobileAdSession"}],"abstract":[{"type":"text","text":"Ad session API enabling the integration partner to notify OMID of key state relating to viewability calculations."},{"type":"text","text":" "},{"type":"text","text":"In addition to viewability this API will also notify all verification providers of key ad session lifecycle events."}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileAdSession","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OMIDTaiwanmobileAdSession"}],"url":"\/documentation\/tamediaadsframework\/omidtaiwanmobileadsession"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework":{"role":"collection","title":"TAMediaAdsFramework","abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","kind":"symbol","type":"topic","url":"\/documentation\/tamediaadsframework"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/OMIDTaiwanmobileMediaEvents/init(adSession:)":{"role":"symbol","title":"init(adSession:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"adSession"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"OMIDTaiwanmobileAdSession","preciseIdentifier":"c:objc(cs)OMIDTaiwanmobileAdSession"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[{"type":"text","text":"Initializes media events instance for the associated ad session."},{"type":"text","text":" "},{"type":"text","text":"Any attempt to create a media events instance will fail if the supplied ad session has already started."}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileMediaEvents\/init(adSession:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithAdSession:error:"}],"url":"\/documentation\/tamediaadsframework\/omidtaiwanmobilemediaevents\/init(adsession:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithAdSession:error:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithAdSession:error:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithAdSession:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDTaiwanmobileAdSession","preciseIdentifier":"c:objc(cs)OMIDTaiwanmobileAdSession","text":"OMIDTaiwanmobileAdSession"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"session"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" * *)"},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDTaiwanmobileMediaEvents\/title","value":"OMIDTaiwanmobileMediaEvents"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDTaiwanmobileMediaEvents\/fragments","value":[{"kind":"identifier","text":"OMIDTaiwanmobileMediaEvents"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDTaiwanmobileAdSession\/title","value":"OMIDTaiwanmobileAdSession"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDTaiwanmobileAdSession\/fragments","value":[{"kind":"identifier","text":"OMIDTaiwanmobileAdSession"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDTaiwanmobileMediaEvents~1init(adSession:)\/title","value":"initWithAdSession:error:"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDTaiwanmobileMediaEvents~1init(adSession:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithAdSession:error:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}