{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADAdSizeEqualToSize"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"size1"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADAdSize","preciseIdentifier":"c:@S@TADAdSize","text":"TADAdSize"},{"kind":"text","text":", "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"size2"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADAdSize","preciseIdentifier":"c:@S@TADAdSize","text":"TADAdSize"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/tamediaadsframework\/tadadsizeequaltosize(_:_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/tamediaadsframework\/tadadsizeequaltosize(_:_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADAdSizeEqualToSize(_:_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"檢查兩個 TADAdSize 是否相等。"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADAdSizeEqualToSize"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"TADAdSize","preciseIdentifier":"c:@S@TADAdSize"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"TADAdSize","preciseIdentifier":"c:@S@TADAdSize"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"TADAdSizeEqualToSize(_:_:)","roleHeading":"Function","role":"symbol","symbolKind":"func","externalID":"c:@F@TADAdSizeEqualToSize","modules":[{"name":"TAMediaAdsFramework"}],"navigatorTitle":[{"kind":"identifier","text":"TADAdSizeEqualToSize"}]},"hierarchy":{"paths":[["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework"]]},"references":{"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADAdSizeEqualToSize(_:_:)":{"role":"symbol","title":"TADAdSizeEqualToSize(_:_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADAdSizeEqualToSize"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"TADAdSize","preciseIdentifier":"c:@S@TADAdSize"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"TADAdSize","preciseIdentifier":"c:@S@TADAdSize"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"檢查兩個 TADAdSize 是否相等。"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADAdSizeEqualToSize(_:_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TADAdSizeEqualToSize"}],"url":"\/documentation\/tamediaadsframework\/tadadsizeequaltosize(_:_:)"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework":{"role":"collection","title":"TAMediaAdsFramework","abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","kind":"symbol","type":"topic","url":"\/documentation\/tamediaadsframework"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADAdSize":{"role":"symbol","title":"TADAdSize","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADAdSize"}],"abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADAdSize","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TADAdSize"}],"url":"\/documentation\/tamediaadsframework\/tadadsize"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Function"},{"op":"replace","path":"\/metadata\/title","value":"TADAdSizeEqualToSize"},{"op":"replace","path":"\/metadata\/symbolKind","value":"func"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"TADAdSizeEqualToSize"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADAdSizeEqualToSize"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADAdSize","preciseIdentifier":"c:@S@TADAdSize","text":"TADAdSize"},{"kind":"text","text":" "},{"kind":"internalParam","text":"size1"},{"kind":"text","text":", "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADAdSize","preciseIdentifier":"c:@S@TADAdSize","text":"TADAdSize"},{"kind":"text","text":" "},{"kind":"internalParam","text":"size2"},{"kind":"text","text":")"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADAdSizeEqualToSize(_:_:)\/title","value":"TADAdSizeEqualToSize"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADAdSizeEqualToSize(_:_:)\/fragments","value":[{"kind":"identifier","text":"TADAdSizeEqualToSize"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADAdSize\/title","value":"TADAdSize"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADAdSize\/fragments","value":[{"kind":"identifier","text":"TADAdSize"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}