{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADInterstitial"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/tamediaadsframework\/tadinterstitial"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/tamediaadsframework\/tadinterstitial"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)NSObject","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/s7CVarArgP","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/s28CustomDebugStringConvertibleP","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/s23CustomStringConvertibleP","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/SQ","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInterstitial","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"顯示插頁式廣告。 這是一個全屏廣告，顯示在您的應用程序中，例如遊戲關卡或新聞故事之間。"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADInterstitial"}],"title":"TADInterstitial","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)TADInterstitial","modules":[{"name":"TAMediaAdsFramework"}],"navigatorTitle":[{"kind":"identifier","text":"TADInterstitial"}]},"hierarchy":{"paths":[["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInterstitial\/adUnitID","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInterstitial\/allowAudioSessionControl","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInterstitial\/delegate","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInterstitial\/hasBeenUsed","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInterstitial\/isReady","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInterstitial\/turnOnMicrophone"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInterstitial\/load(_:)","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInterstitial\/present(fromRootViewController:)"]}],"references":{"doc://com.taiwanmobile.TAMediaAdsFramework/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/SQ"},"doc://com.taiwanmobile.TAMediaAdsFramework/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/s7CVarArgP"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADInterstitial/isReady":{"role":"symbol","title":"isReady","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isReady"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"如果插頁式廣告準備好顯示，則返回 YES。 代表的interstitialAdDidReceiveAd：當它從 NO 切換到 YES 時將被調用。"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInterstitial\/isReady","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isReady"}],"url":"\/documentation\/tamediaadsframework\/tadinterstitial\/isready"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADInterstitial/adUnitID":{"role":"symbol","title":"adUnitID","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"adUnitID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"在 TAMedia 網站中創建的必需值。創建一個新的廣告單元"},{"type":"text","text":" "},{"type":"text","text":"廣告在您的應用程序中的每個獨特位置。將此設置為ID分配給這個展示位置。"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInterstitial\/adUnitID","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"adUnitID"}],"url":"\/documentation\/tamediaadsframework\/tadinterstitial\/adunitid"},"doc://com.taiwanmobile.TAMediaAdsFramework/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/SH"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADInterstitial/load(_:)":{"role":"symbol","title":"load(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"load"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"TADRequest","preciseIdentifier":"c:objc(cs)TADRequest"},{"kind":"text","text":"!)"}],"abstract":[{"type":"text","text":"發出插頁式廣告請求。 一次僅允許一個插頁式請求。"},{"type":"text","text":" "},{"type":"text","text":"這個最好在需要插頁前幾秒做預加載其內容。 然後在視圖控制器之間轉換時用presentFromViewController顯示。"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInterstitial\/load(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"loadRequest:"}],"url":"\/documentation\/tamediaadsframework\/tadinterstitial\/load(_:)"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADInterstitial/turnOnMicrophone":{"role":"symbol","title":"turnOnMicrophone","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"turnOnMicrophone"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"如果設置為 NO，則用戶無法與麥克風廣告互動，預設為 YES"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInterstitial\/turnOnMicrophone","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"turnOnMicrophone"}],"url":"\/documentation\/tamediaadsframework\/tadinterstitial\/turnonmicrophone"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADInterstitial/hasBeenUsed":{"role":"symbol","title":"hasBeenUsed","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hasBeenUsed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"如果插頁式對像已顯示插頁式廣告，則返回 YES。"},{"type":"text","text":" "},{"type":"text","text":"請注意，一個插頁式對象即使使用不同的對像也只能使用一次要求。"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInterstitial\/hasBeenUsed","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"hasBeenUsed"}],"url":"\/documentation\/tamediaadsframework\/tadinterstitial\/hasbeenused"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADInterstitial/present(fromRootViewController:)":{"role":"symbol","title":"present(fromRootViewController:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"present"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fromRootViewController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":"!)"}],"abstract":[{"type":"text","text":"展示佔據整個屏幕的插頁式廣告，直到用戶關閉它。 除非 isReady 返回 YES 或 委託的 interstitialDidReceiveAd: 已收到。"},{"type":"text","text":" "},{"type":"text","text":"請設置rootViewController為當前ViewController"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInterstitial\/present(fromRootViewController:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"presentFromRootViewController:"}],"url":"\/documentation\/tamediaadsframework\/tadinterstitial\/present(fromrootviewcontroller:)"},"doc://com.taiwanmobile.TAMediaAdsFramework/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/s23CustomStringConvertibleP"},"doc://com.taiwanmobile.TAMediaAdsFramework/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)NSObject"},"doc://com.taiwanmobile.TAMediaAdsFramework/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/s28CustomDebugStringConvertibleP"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework":{"role":"collection","title":"TAMediaAdsFramework","abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","kind":"symbol","type":"topic","url":"\/documentation\/tamediaadsframework"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADInterstitial/allowAudioSessionControl":{"role":"symbol","title":"allowAudioSessionControl","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowAudioSessionControl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"默認為是。"},{"type":"text","text":" "},{"type":"text","text":"當影音廣告顯示\/不顯示時，SDK 會將 AVAudioSession 更改為 active。"},{"type":"text","text":" "},{"type":"text","text":"如果您的應用程序使用AVAudioSession，則將此屬性設置為NO。"},{"type":"text","text":" "},{"type":"text","text":"並自行控制AVAudioSession。"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInterstitial\/allowAudioSessionControl","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"allowAudioSessionControl"}],"url":"\/documentation\/tamediaadsframework\/tadinterstitial\/allowaudiosessioncontrol"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADInterstitial":{"role":"symbol","title":"TADInterstitial","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADInterstitial"}],"abstract":[{"type":"text","text":"顯示插頁式廣告。 這是一個全屏廣告，顯示在您的應用程序中，例如遊戲關卡或新聞故事之間。"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInterstitial","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TADInterstitial"}],"url":"\/documentation\/tamediaadsframework\/tadinterstitial"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADInterstitial/delegate":{"role":"symbol","title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TADInterstitialDelegate","preciseIdentifier":"c:objc(pl)TADInterstitialDelegate"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"從TADInterstitalAd 接收狀態更改通知的可選委託對象。 請記住不使用此對象之前將委託設為 nil。"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInterstitial\/delegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"delegate"}],"url":"\/documentation\/tamediaadsframework\/tadinterstitial\/delegate"},"doc://com.taiwanmobile.TAMediaAdsFramework/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(cs)NSObject"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"TADInterstitial"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"TADInterstitial"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"TADInterstitial"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInterstitial\/adUnitID","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInterstitial\/allowAudioSessionControl","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInterstitial\/delegate","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInterstitial\/hasBeenUsed","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInterstitial\/isReady","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInterstitial\/turnOnMicrophone"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInterstitial\/load(_:)","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInterstitial\/present(fromRootViewController:)"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADInterstitial"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADInterstitial~1isReady\/title","value":"isReady"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADInterstitial~1isReady\/fragments","value":[{"kind":"identifier","text":"isReady"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADInterstitial~1adUnitID\/title","value":"adUnitID"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADInterstitial~1adUnitID\/fragments","value":[{"kind":"identifier","text":"adUnitID"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADInterstitial~1load(_:)\/title","value":"loadRequest:"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADInterstitial~1load(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"loadRequest:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADInterstitial~1turnOnMicrophone\/title","value":"turnOnMicrophone"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADInterstitial~1turnOnMicrophone\/fragments","value":[{"kind":"identifier","text":"turnOnMicrophone"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADInterstitial~1hasBeenUsed\/title","value":"hasBeenUsed"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADInterstitial~1hasBeenUsed\/fragments","value":[{"kind":"identifier","text":"hasBeenUsed"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADInterstitial~1present(fromRootViewController:)\/title","value":"presentFromRootViewController:"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADInterstitial~1present(fromRootViewController:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"presentFromRootViewController:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADInterstitial~1allowAudioSessionControl\/title","value":"allowAudioSessionControl"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADInterstitial~1allowAudioSessionControl\/fragments","value":[{"kind":"identifier","text":"allowAudioSessionControl"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADInterstitial\/title","value":"TADInterstitial"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADInterstitial\/fragments","value":[{"kind":"identifier","text":"TADInterstitial"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADInterstitial~1delegate\/title","value":"delegate"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADInterstitial~1delegate\/fragments","value":[{"kind":"identifier","text":"delegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}