{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADInReadAnchor"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/tamediaadsframework\/tadinreadanchor"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/tamediaadsframework\/tadinreadanchor"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)NSCoding","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)NSObject","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)CALayerDelegate","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/s7CVarArgP","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/s28CustomDebugStringConvertibleP","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/s23CustomStringConvertibleP","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/SQ","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/SH","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/s8SendableP","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UIAccessibilityIdentification","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UIAppearance","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UIAppearanceContainer","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UICoordinateSpace","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UIDynamicItem","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UIFocusEnvironment","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UIFocusItem","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UIFocusItemContainer","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UILargeContentViewerItem","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UITraitEnvironment","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInReadAnchor","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"顯示 InReadAnchor 廣告的視圖。"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADInReadAnchor"}],"title":"TADInReadAnchor","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)TADInReadAnchor","modules":[{"name":"TAMediaAdsFramework"}],"navigatorTitle":[{"kind":"identifier","text":"TADInReadAnchor"}]},"hierarchy":{"paths":[["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInReadAnchor\/init(anchorWithViewController:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInReadAnchor\/adUnitID","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInReadAnchor\/allowAudioSessionControl","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInReadAnchor\/delegate","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInReadAnchor\/turnOnMicrophone"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInReadAnchor\/load(_:)","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInReadAnchor\/viewWillAppear()","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInReadAnchor\/viewWillDisappear()"]}],"references":{"doc://com.taiwanmobile.TAMediaAdsFramework/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UICoordinateSpace"},"doc://com.taiwanmobile.TAMediaAdsFramework/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UIAppearance"},"doc://com.taiwanmobile.TAMediaAdsFramework/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UIFocusItem"},"doc://com.taiwanmobile.TAMediaAdsFramework/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/SQ"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADInReadAnchor/turnOnMicrophone":{"role":"symbol","title":"turnOnMicrophone","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"turnOnMicrophone"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"如果設置為 NO，則用戶無法與麥克風廣告互動，預設為 YES"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInReadAnchor\/turnOnMicrophone","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"turnOnMicrophone"}],"url":"\/documentation\/tamediaadsframework\/tadinreadanchor\/turnonmicrophone"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADInReadAnchor/adUnitID":{"role":"symbol","title":"adUnitID","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"adUnitID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"由 TAMedia 提供的廣告 ID。"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInReadAnchor\/adUnitID","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"adUnitID"}],"url":"\/documentation\/tamediaadsframework\/tadinreadanchor\/adunitid"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADInReadAnchor/allowAudioSessionControl":{"role":"symbol","title":"allowAudioSessionControl","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowAudioSessionControl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"默認為是。"},{"type":"text","text":" "},{"type":"text","text":"當影音廣告顯示\/不顯示時，SDK 會將 AVAudioSession 更改為 active。"},{"type":"text","text":" "},{"type":"text","text":"如果您的應用程序使用AVAudioSession，則將此屬性設置為NO。"},{"type":"text","text":" "},{"type":"text","text":"並自行控制AVAudioSession。"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInReadAnchor\/allowAudioSessionControl","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"allowAudioSessionControl"}],"url":"\/documentation\/tamediaadsframework\/tadinreadanchor\/allowaudiosessioncontrol"},"doc://com.taiwanmobile.TAMediaAdsFramework/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/s28CustomDebugStringConvertibleP"},"doc://com.taiwanmobile.TAMediaAdsFramework/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UITraitEnvironment"},"doc://com.taiwanmobile.TAMediaAdsFramework/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UIFocusItemContainer"},"doc://com.taiwanmobile.TAMediaAdsFramework/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UIFocusEnvironment"},"doc://com.taiwanmobile.TAMediaAdsFramework/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UIAccessibilityIdentification"},"doc://com.taiwanmobile.TAMediaAdsFramework/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADInReadAnchor/load(_:)":{"role":"symbol","title":"load(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"load"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"TADRequest","preciseIdentifier":"c:objc(cs)TADRequest"},{"kind":"text","text":"!)"}],"abstract":[{"type":"text","text":"發出廣告請求。"},{"type":"text","text":" "},{"type":"text","text":"刷新廣告可通過再次調用此方法。"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInReadAnchor\/load(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"loadRequest:"}],"url":"\/documentation\/tamediaadsframework\/tadinreadanchor\/load(_:)"},"doc://com.taiwanmobile.TAMediaAdsFramework/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)NSObject"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADInReadAnchor/viewWillAppear()":{"role":"symbol","title":"viewWillAppear()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewWillAppear"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"該畫面即將顯示"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInReadAnchor\/viewWillAppear()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewWillAppear"}],"url":"\/documentation\/tamediaadsframework\/tadinreadanchor\/viewwillappear()"},"doc://com.taiwanmobile.TAMediaAdsFramework/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UIUserActivityRestoring"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADInReadAnchor/delegate":{"role":"symbol","title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TADInReadAnchorDelegate","preciseIdentifier":"c:objc(pl)TADInReadAnchorDelegate"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"從 TADNativeAd 接收狀態更改通知的可選委託對象。 請記住不使用此對象之前將委託設為 nil。"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInReadAnchor\/delegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"delegate"}],"url":"\/documentation\/tamediaadsframework\/tadinreadanchor\/delegate"},"doc://com.taiwanmobile.TAMediaAdsFramework/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UILargeContentViewerItem"},"doc://com.taiwanmobile.TAMediaAdsFramework/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://com.taiwanmobile.TAMediaAdsFramework/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.taiwanmobile.TAMediaAdsFramework/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)NSCoding"},"doc://com.taiwanmobile.TAMediaAdsFramework/objc(cs)UIView":{"type":"unresolvable","title":"UIView","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(cs)UIView"},"doc://com.taiwanmobile.TAMediaAdsFramework/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/s23CustomStringConvertibleP"},"doc://com.taiwanmobile.TAMediaAdsFramework/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/SH"},"doc://com.taiwanmobile.TAMediaAdsFramework/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/s8SendableP"},"doc://com.taiwanmobile.TAMediaAdsFramework/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UIResponderStandardEditActions"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADInReadAnchor":{"role":"symbol","title":"TADInReadAnchor","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADInReadAnchor"}],"abstract":[{"type":"text","text":"顯示 InReadAnchor 廣告的視圖。"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInReadAnchor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TADInReadAnchor"}],"url":"\/documentation\/tamediaadsframework\/tadinreadanchor"},"doc://com.taiwanmobile.TAMediaAdsFramework/objc(pl)CALayerDelegate":{"type":"unresolvable","title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)CALayerDelegate"},"doc://com.taiwanmobile.TAMediaAdsFramework/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/s7CVarArgP"},"doc://com.taiwanmobile.TAMediaAdsFramework/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UIAppearanceContainer"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework":{"role":"collection","title":"TAMediaAdsFramework","abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","kind":"symbol","type":"topic","url":"\/documentation\/tamediaadsframework"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADInReadAnchor/init(anchorWithViewController:)":{"role":"symbol","title":"init(anchorWithViewController:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"!("},{"kind":"externalParam","text":"anchorWithViewController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":"!)"}],"abstract":[{"type":"text","text":"對 ViewController 初始化 Anchor 廣告版位"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInReadAnchor\/init(anchorWithViewController:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initAnchorWithViewController:"}],"url":"\/documentation\/tamediaadsframework\/tadinreadanchor\/init(anchorwithviewcontroller:)"},"doc://com.taiwanmobile.TAMediaAdsFramework/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UIDynamicItem"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADInReadAnchor/viewWillDisappear()":{"role":"symbol","title":"viewWillDisappear()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewWillDisappear"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"該畫面即將離開"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInReadAnchor\/viewWillDisappear()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewWillDisappear"}],"url":"\/documentation\/tamediaadsframework\/tadinreadanchor\/viewwilldisappear()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"TADInReadAnchor"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"TADInReadAnchor"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"TADInReadAnchor"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInReadAnchor\/adUnitID","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInReadAnchor\/allowAudioSessionControl","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInReadAnchor\/delegate","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInReadAnchor\/turnOnMicrophone"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInReadAnchor\/init(anchorWithViewController:)","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInReadAnchor\/load(_:)","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInReadAnchor\/viewWillAppear()","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInReadAnchor\/viewWillDisappear()"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADInReadAnchor"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADInReadAnchor~1turnOnMicrophone\/title","value":"turnOnMicrophone"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADInReadAnchor~1turnOnMicrophone\/fragments","value":[{"kind":"identifier","text":"turnOnMicrophone"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADInReadAnchor~1adUnitID\/title","value":"adUnitID"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADInReadAnchor~1adUnitID\/fragments","value":[{"kind":"identifier","text":"adUnitID"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADInReadAnchor~1allowAudioSessionControl\/title","value":"allowAudioSessionControl"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADInReadAnchor~1allowAudioSessionControl\/fragments","value":[{"kind":"identifier","text":"allowAudioSessionControl"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADInReadAnchor~1load(_:)\/title","value":"loadRequest:"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADInReadAnchor~1load(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"loadRequest:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADInReadAnchor~1viewWillAppear()\/title","value":"viewWillAppear"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADInReadAnchor~1viewWillAppear()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewWillAppear"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADInReadAnchor~1delegate\/title","value":"delegate"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADInReadAnchor~1delegate\/fragments","value":[{"kind":"identifier","text":"delegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADInReadAnchor\/title","value":"TADInReadAnchor"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADInReadAnchor\/fragments","value":[{"kind":"identifier","text":"TADInReadAnchor"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADInReadAnchor~1init(anchorWithViewController:)\/title","value":"initAnchorWithViewController:"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADInReadAnchor~1init(anchorWithViewController:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initAnchorWithViewController:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADInReadAnchor~1viewWillDisappear()\/title","value":"viewWillDisappear"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADInReadAnchor~1viewWillDisappear()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewWillDisappear"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}