{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADNativeAdOptions"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/tamediaadsframework\/tadnativeadoptions"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/tamediaadsframework\/tadnativeadoptions"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADAdOptions"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)NSObject","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/s7CVarArgP","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/s28CustomDebugStringConvertibleP","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/s23CustomStringConvertibleP","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/SQ","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdOptions","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"用於 NativeAd 的可選控制項"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADNativeAdOptions"}],"title":"TADNativeAdOptions","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@TAMediaAdsFramework@objc(cs)TADNativeAdOptions","modules":[{"name":"TAMediaAdsFramework"}],"navigatorTitle":[{"kind":"identifier","text":"TADNativeAdOptions"}]},"hierarchy":{"paths":[["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdOptions\/allowAudioSessionControl","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdOptions\/customControlsRequested","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdOptions\/disableImageLoading","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdOptions\/mediaPreferImage","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdOptions\/startUnmuted"]}],"references":{"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADNativeAdOptions":{"role":"symbol","title":"TADNativeAdOptions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADNativeAdOptions"}],"abstract":[{"type":"text","text":"用於 NativeAd 的可選控制項"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdOptions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TADNativeAdOptions"}],"url":"\/documentation\/tamediaadsframework\/tadnativeadoptions"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework":{"role":"collection","title":"TAMediaAdsFramework","abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","kind":"symbol","type":"topic","url":"\/documentation\/tamediaadsframework"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADNativeAdOptions/allowAudioSessionControl":{"role":"symbol","title":"allowAudioSessionControl","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowAudioSessionControl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"預設為 true，播放影音廣告時，SDK 將會將 AVAudioSession 設為 mixWithOthers"},{"type":"text","text":" "},{"type":"text","text":"如果您的應用程序使用 AVAudioSession，則將此屬性設置為 false"},{"type":"text","text":" "},{"type":"text","text":"並自行控制AVAudioSession。"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdOptions\/allowAudioSessionControl","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"allowAudioSessionControl"}],"url":"\/documentation\/tamediaadsframework\/tadnativeadoptions\/allowaudiosessioncontrol"},"doc://com.taiwanmobile.TAMediaAdsFramework/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/s7CVarArgP"},"doc://com.taiwanmobile.TAMediaAdsFramework/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/s23CustomStringConvertibleP"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADAdOptions":{"role":"symbol","title":"TADAdOptions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADAdOptions"}],"abstract":[{"type":"text","text":"Ad options base class."},{"type":"text","text":" "},{"type":"text","text":"廣告客製化選項基礎類別，可參見 TADNativeAdOptions"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADAdOptions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TADAdOptions"}],"url":"\/documentation\/tamediaadsframework\/tadadoptions"},"doc://com.taiwanmobile.TAMediaAdsFramework/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)NSObject"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADNativeAdOptions/customControlsRequested":{"role":"symbol","title":"customControlsRequested","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"customControlsRequested"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"指示請求的影音是否應啟用靜音\/取消靜音、倒計時標籤和了解更多信息的自定義控件。"},{"type":"text","text":" "},{"type":"text","text":"默認值為false"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdOptions\/customControlsRequested","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"customControlsRequested"}],"url":"\/documentation\/tamediaadsframework\/tadnativeadoptions\/customcontrolsrequested"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADNativeAdOptions/disableImageLoading":{"role":"symbol","title":"disableImageLoading","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"disableImageLoading"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"SDK 將自動下載原生廣告中的圖片內容，"},{"type":"text","text":" "},{"type":"text","text":"將此屬性設置為true，則SDK不會下載圖片，TADNativeAdImage中的圖片將為nil。"},{"type":"text","text":" "},{"type":"text","text":"默認值為false。"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdOptions\/disableImageLoading","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"disableImageLoading"}],"url":"\/documentation\/tamediaadsframework\/tadnativeadoptions\/disableimageloading"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADNativeAdOptions/init":{"role":"symbol","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdOptions\/init","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/tamediaadsframework\/tadnativeadoptions\/init"},"doc://com.taiwanmobile.TAMediaAdsFramework/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/s28CustomDebugStringConvertibleP"},"doc://com.taiwanmobile.TAMediaAdsFramework/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/SH"},"doc://com.taiwanmobile.TAMediaAdsFramework/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/SQ"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADNativeAdOptions/mediaPreferImage":{"role":"symbol","title":"mediaPreferImage","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mediaPreferImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"如果原生廣告內容是影音和圖片，SDK 將使用影音來展示廣告。"},{"type":"text","text":" "},{"type":"text","text":"將此屬性設置為 true，則 SDK 將始終使用圖片來展示廣告。"},{"type":"text","text":" "},{"type":"text","text":"默認值為false。"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdOptions\/mediaPreferImage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"mediaPreferImage"}],"url":"\/documentation\/tamediaadsframework\/tadnativeadoptions\/mediapreferimage"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADNativeAdOptions/startUnmuted":{"role":"symbol","title":"startUnmuted","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"startUnmuted"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"此布林值指示原生影音廣告是否應在未靜音狀態下開始播放。"},{"type":"text","text":" "},{"type":"text","text":"默認值為false。"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdOptions\/startUnmuted","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startUnmuted"}],"url":"\/documentation\/tamediaadsframework\/tadnativeadoptions\/startunmuted"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"TADNativeAdOptions"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"TADNativeAdOptions"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"TADNativeAdOptions"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdOptions\/allowAudioSessionControl","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdOptions\/customControlsRequested","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdOptions\/disableImageLoading","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdOptions\/mediaPreferImage","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdOptions\/startUnmuted"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdOptions\/init"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADNativeAdOptions"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADAdOptions","preciseIdentifier":"c:@M@TAMediaAdsFramework@objc(cs)TADAdOptions","text":"TADAdOptions"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAdOptions\/title","value":"TADNativeAdOptions"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAdOptions\/fragments","value":[{"kind":"identifier","text":"TADNativeAdOptions"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAdOptions~1allowAudioSessionControl\/title","value":"allowAudioSessionControl"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAdOptions~1allowAudioSessionControl\/fragments","value":[{"kind":"identifier","text":"allowAudioSessionControl"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADAdOptions\/title","value":"TADAdOptions"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADAdOptions\/fragments","value":[{"kind":"identifier","text":"TADAdOptions"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAdOptions~1customControlsRequested\/title","value":"customControlsRequested"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAdOptions~1customControlsRequested\/fragments","value":[{"kind":"identifier","text":"customControlsRequested"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAdOptions~1disableImageLoading\/title","value":"disableImageLoading"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAdOptions~1disableImageLoading\/fragments","value":[{"kind":"identifier","text":"disableImageLoading"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAdOptions~1mediaPreferImage\/title","value":"mediaPreferImage"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAdOptions~1mediaPreferImage\/fragments","value":[{"kind":"identifier","text":"mediaPreferImage"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAdOptions~1startUnmuted\/title","value":"startUnmuted"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAdOptions~1startUnmuted\/fragments","value":[{"kind":"identifier","text":"startUnmuted"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}