{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADNativeMediaView"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/tamediaadsframework\/tadnativemediaview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/tamediaadsframework\/tadnativemediaview"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)NSCoding","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)NSObject","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)CALayerDelegate","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/s7CVarArgP","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/s28CustomDebugStringConvertibleP","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/s23CustomStringConvertibleP","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/SQ","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/SH","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/s8SendableP","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UIAccessibilityIdentification","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UIAppearance","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UIAppearanceContainer","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UICoordinateSpace","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UIDynamicItem","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UIFocusEnvironment","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UIFocusItem","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UIFocusItemContainer","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UILargeContentViewerItem","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UITraitEnvironment","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeMediaView","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Native 廣告需要顯示 media 內容(圖片或影片) 的 view"},{"type":"text","text":" "},{"type":"text","text":"需代入 "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdMediaContent"},{"type":"text","text":" 才能正確顯示內容"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADNativeMediaView"}],"title":"TADNativeMediaView","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@TAMediaAdsFramework@objc(cs)TADNativeMediaView","modules":[{"name":"TAMediaAdsFramework"}],"navigatorTitle":[{"kind":"identifier","text":"TADNativeMediaView"}]},"hierarchy":{"paths":[["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeMediaView\/init(coder:)","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeMediaView\/init(frame:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeMediaView\/mediaContent","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeMediaView\/statusDelegate"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeMediaView\/setCallToActionTextSize(_:)","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeMediaView\/setCallToActionVisible(_:)","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeMediaView\/setMainImage(contentMode:)","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeMediaView\/setMainImage(image:)","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeMediaView\/setMainImage(with:)","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeMediaView\/setVideoCountdownTextSize(_:)","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeMediaView\/setVolumeImageSize(_:)"]}],"references":{"doc://com.taiwanmobile.TAMediaAdsFramework/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UIAccessibilityIdentification"},"doc://com.taiwanmobile.TAMediaAdsFramework/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UIDynamicItem"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADNativeMediaView/setMainImage(image:)":{"role":"symbol","title":"setMainImage(image:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setMainImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"image"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"使用 UIImage 設定 main image"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeMediaView\/setMainImage(image:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setMainImageWithImage:"}],"url":"\/documentation\/tamediaadsframework\/tadnativemediaview\/setmainimage(image:)"},"doc://com.taiwanmobile.TAMediaAdsFramework/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://com.taiwanmobile.TAMediaAdsFramework/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.taiwanmobile.TAMediaAdsFramework/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/SH"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADNativeMediaView/setVolumeImageSize(_:)":{"role":"symbol","title":"setVolumeImageSize(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setVolumeImageSize"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"自定義靜音按鈕圖片大小，預設為24"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeMediaView\/setVolumeImageSize(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setVolumeImageSize:"}],"url":"\/documentation\/tamediaadsframework\/tadnativemediaview\/setvolumeimagesize(_:)"},"doc://com.taiwanmobile.TAMediaAdsFramework/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UITraitEnvironment"},"doc://com.taiwanmobile.TAMediaAdsFramework/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/s8SendableP"},"doc://com.taiwanmobile.TAMediaAdsFramework/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/SQ"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADNativeMediaView/setVideoCountdownTextSize(_:)":{"role":"symbol","title":"setVideoCountdownTextSize(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setVideoCountdownTextSize"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"自定義影音倒數文字大小，預設為17.0"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeMediaView\/setVideoCountdownTextSize(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setVideoCountdownTextSize:"}],"url":"\/documentation\/tamediaadsframework\/tadnativemediaview\/setvideocountdowntextsize(_:)"},"doc://com.taiwanmobile.TAMediaAdsFramework/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/s28CustomDebugStringConvertibleP"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADNativeMediaView/setCallToActionVisible(_:)":{"role":"symbol","title":"setCallToActionVisible(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setCallToActionVisible"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"設定外開網頁按鈕是否顯示，預設為顯示"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeMediaView\/setCallToActionVisible(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setCallToActionVisible:"}],"url":"\/documentation\/tamediaadsframework\/tadnativemediaview\/setcalltoactionvisible(_:)"},"doc://com.taiwanmobile.TAMediaAdsFramework/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UIAppearanceContainer"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADNativeAdMediaContent":{"role":"symbol","title":"TADNativeAdMediaContent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADNativeAdMediaContent"}],"abstract":[{"type":"text","text":"封裝原生廣告的 media 物件, 其中包含圖片和影片"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdMediaContent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TADNativeAdMediaContent"}],"url":"\/documentation\/tamediaadsframework\/tadnativeadmediacontent"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADNativeMediaView/setCallToActionTextSize(_:)":{"role":"symbol","title":"setCallToActionTextSize(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setCallToActionTextSize"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"自定義外開網頁文字大小，預設為12.0"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeMediaView\/setCallToActionTextSize(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setCallToActionTextSize:"}],"url":"\/documentation\/tamediaadsframework\/tadnativemediaview\/setcalltoactiontextsize(_:)"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADNativeMediaView/setMainImage(contentMode:)":{"role":"symbol","title":"setMainImage(contentMode:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setMainImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"contentMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"ContentMode","preciseIdentifier":"c:@E@UIViewContentMode"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"設定 main image 的圖片顯示方式"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeMediaView\/setMainImage(contentMode:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setMainImageWithContentMode:"}],"url":"\/documentation\/tamediaadsframework\/tadnativemediaview\/setmainimage(contentmode:)"},"doc://com.taiwanmobile.TAMediaAdsFramework/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UICoordinateSpace"},"doc://com.taiwanmobile.TAMediaAdsFramework/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)NSObject"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework":{"role":"collection","title":"TAMediaAdsFramework","abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","kind":"symbol","type":"topic","url":"\/documentation\/tamediaadsframework"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADNativeMediaView/mediaContent":{"role":"symbol","title":"mediaContent","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mediaContent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TADNativeAdMediaContent","preciseIdentifier":"c:@M@TAMediaAdsFramework@objc(cs)TADNativeAdMediaContent"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"原生廣告的 media 物件, 其中包含圖片和影片"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeMediaView\/mediaContent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"mediaContent"}],"url":"\/documentation\/tamediaadsframework\/tadnativemediaview\/mediacontent"},"doc://com.taiwanmobile.TAMediaAdsFramework/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/s7CVarArgP"},"doc://com.taiwanmobile.TAMediaAdsFramework/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UIAppearance"},"doc://com.taiwanmobile.TAMediaAdsFramework/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.taiwanmobile.TAMediaAdsFramework/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UIResponderStandardEditActions"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADNativeMediaView/init(frame:)":{"role":"symbol","title":"init(frame:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"frame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"初始化物件"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeMediaView\/init(frame:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithFrame:"}],"url":"\/documentation\/tamediaadsframework\/tadnativemediaview\/init(frame:)"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADNativeMediaView/statusDelegate":{"role":"symbol","title":"statusDelegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"statusDelegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TADVideoStatusDelegate","preciseIdentifier":"c:@M@TAMediaAdsFramework@objc(pl)TADVideoStatusDelegate"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"native 廣告顯示影片時, 實作此 Delegate 可取得影片的狀態回報"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeMediaView\/statusDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"statusDelegate"}],"url":"\/documentation\/tamediaadsframework\/tadnativemediaview\/statusdelegate"},"doc://com.taiwanmobile.TAMediaAdsFramework/objc(cs)UIView":{"type":"unresolvable","title":"UIView","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(cs)UIView"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADNativeMediaView/setMainImage(with:)":{"role":"symbol","title":"setMainImage(with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setMainImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"使用 URL string 設定 main image"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeMediaView\/setMainImage(with:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setMainImageWith:"}],"url":"\/documentation\/tamediaadsframework\/tadnativemediaview\/setmainimage(with:)"},"doc://com.taiwanmobile.TAMediaAdsFramework/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UILargeContentViewerItem"},"doc://com.taiwanmobile.TAMediaAdsFramework/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UIFocusItemContainer"},"doc://com.taiwanmobile.TAMediaAdsFramework/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/s23CustomStringConvertibleP"},"doc://com.taiwanmobile.TAMediaAdsFramework/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)NSCoding"},"doc://com.taiwanmobile.TAMediaAdsFramework/objc(pl)CALayerDelegate":{"type":"unresolvable","title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)CALayerDelegate"},"doc://com.taiwanmobile.TAMediaAdsFramework/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UIFocusEnvironment"},"doc://com.taiwanmobile.TAMediaAdsFramework/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UIFocusItem"},"doc://com.taiwanmobile.TAMediaAdsFramework/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UIUserActivityRestoring"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADNativeMediaView":{"role":"symbol","title":"TADNativeMediaView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADNativeMediaView"}],"abstract":[{"type":"text","text":"Native 廣告需要顯示 media 內容(圖片或影片) 的 view"},{"type":"text","text":" "},{"type":"text","text":"需代入 "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdMediaContent"},{"type":"text","text":" 才能正確顯示內容"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeMediaView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TADNativeMediaView"}],"url":"\/documentation\/tamediaadsframework\/tadnativemediaview"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADNativeMediaView/init(coder:)":{"role":"symbol","title":"init(coder:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"初始化物件"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeMediaView\/init(coder:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/tamediaadsframework\/tadnativemediaview\/init(coder:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"TADNativeMediaView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"TADNativeMediaView"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"TADNativeMediaView"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeMediaView\/mediaContent","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeMediaView\/statusDelegate"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeMediaView\/init(coder:)","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeMediaView\/init(frame:)","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeMediaView\/setCallToActionTextSize(_:)","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeMediaView\/setCallToActionVisible(_:)","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeMediaView\/setMainImage(contentMode:)","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeMediaView\/setMainImage(image:)","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeMediaView\/setMainImage(with:)","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeMediaView\/setVideoCountdownTextSize(_:)","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeMediaView\/setVolumeImageSize(_:)"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADNativeMediaView"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeMediaView~1setMainImage(image:)\/title","value":"setMainImageWithImage:"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeMediaView~1setMainImage(image:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setMainImageWithImage:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeMediaView~1setVolumeImageSize(_:)\/title","value":"setVolumeImageSize:"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeMediaView~1setVolumeImageSize(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setVolumeImageSize:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeMediaView~1setVideoCountdownTextSize(_:)\/title","value":"setVideoCountdownTextSize:"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeMediaView~1setVideoCountdownTextSize(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setVideoCountdownTextSize:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeMediaView~1setCallToActionVisible(_:)\/title","value":"setCallToActionVisible:"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeMediaView~1setCallToActionVisible(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setCallToActionVisible:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAdMediaContent\/title","value":"TADNativeAdMediaContent"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAdMediaContent\/fragments","value":[{"kind":"identifier","text":"TADNativeAdMediaContent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeMediaView~1setCallToActionTextSize(_:)\/title","value":"setCallToActionTextSize:"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeMediaView~1setCallToActionTextSize(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setCallToActionTextSize:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeMediaView~1setMainImage(contentMode:)\/title","value":"setMainImageWithContentMode:"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeMediaView~1setMainImage(contentMode:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setMainImageWithContentMode:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeMediaView~1mediaContent\/title","value":"mediaContent"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeMediaView~1mediaContent\/fragments","value":[{"kind":"identifier","text":"mediaContent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeMediaView~1init(frame:)\/title","value":"initWithFrame:"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeMediaView~1init(frame:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFrame:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeMediaView~1statusDelegate\/title","value":"statusDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeMediaView~1statusDelegate\/fragments","value":[{"kind":"identifier","text":"statusDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeMediaView~1setMainImage(with:)\/title","value":"setMainImageWith:"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeMediaView~1setMainImage(with:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setMainImageWith:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeMediaView\/title","value":"TADNativeMediaView"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeMediaView\/fragments","value":[{"kind":"identifier","text":"TADNativeMediaView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeMediaView~1init(coder:)\/title","value":"initWithCoder:"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeMediaView~1init(coder:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}