{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"javaScriptOwner"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/tamediaadsframework\/omidowner\/javascriptowner"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/tamediaadsframework\/omidowner\/javascriptowner"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDOwner\/javaScriptOwner","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The integration will send the event from a JavaScript session script."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"javaScriptOwner"}],"title":"OMIDOwner.javaScriptOwner","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@OMIDOwner@OMIDJavaScriptOwner","modules":[{"name":"TAMediaAdsFramework"}],"navigatorTitle":[{"kind":"identifier","text":"OMIDJavaScriptOwner"}]},"hierarchy":{"paths":[["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDOwner"]]},"references":{"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/OMIDOwner":{"role":"symbol","title":"OMIDOwner","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"OMIDOwner"}],"abstract":[{"type":"text","text":"Identifies which integration layer is responsible for sending certain events."}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDOwner","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OMIDOwner"}],"url":"\/documentation\/tamediaadsframework\/omidowner"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework":{"role":"collection","title":"TAMediaAdsFramework","abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","kind":"symbol","type":"topic","url":"\/documentation\/tamediaadsframework"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/OMIDOwner/javaScriptOwner":{"role":"symbol","title":"OMIDOwner.javaScriptOwner","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"javaScriptOwner"}],"abstract":[{"type":"text","text":"The integration will send the event from a JavaScript session script."}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDOwner\/javaScriptOwner","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OMIDJavaScriptOwner"}],"url":"\/documentation\/tamediaadsframework\/omidowner\/javascriptowner"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"OMIDJavaScriptOwner"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"OMIDJavaScriptOwner"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"OMIDJavaScriptOwner"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDOwner\/title","value":"OMIDOwner"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDOwner\/fragments","value":[{"kind":"identifier","text":"OMIDOwner"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDOwner~1javaScriptOwner\/title","value":"OMIDJavaScriptOwner"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDOwner~1javaScriptOwner\/fragments","value":[{"kind":"identifier","text":"OMIDJavaScriptOwner"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}