{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"!("},{"kind":"externalParam","text":"anchorWithViewController"},{"kind":"text","text":" "},{"kind":"internalParam","text":"viewController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":"!)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/tamediaadsframework\/tadinreadanchor\/init(anchorwithviewcontroller:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/tamediaadsframework\/tadinreadanchor\/init(anchorwithviewcontroller:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInReadAnchor\/init(anchorWithViewController:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"對 ViewController 初始化 Anchor 廣告版位"}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"initAnchorWithViewController:"}],"role":"symbol","title":"init(anchorWithViewController:)","roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"!("},{"kind":"externalParam","text":"anchorWithViewController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":"!)"}],"symbolKind":"init","externalID":"c:objc(cs)TADInReadAnchor(im)initAnchorWithViewController:","modules":[{"name":"TAMediaAdsFramework"}],"platforms":[]},"hierarchy":{"paths":[["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInReadAnchor"]]},"references":{"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework":{"role":"collection","title":"TAMediaAdsFramework","abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","kind":"symbol","type":"topic","url":"\/documentation\/tamediaadsframework"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADInReadAnchor/init(anchorWithViewController:)":{"role":"symbol","title":"init(anchorWithViewController:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"!("},{"kind":"externalParam","text":"anchorWithViewController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":"!)"}],"abstract":[{"type":"text","text":"對 ViewController 初始化 Anchor 廣告版位"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInReadAnchor\/init(anchorWithViewController:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initAnchorWithViewController:"}],"url":"\/documentation\/tamediaadsframework\/tadinreadanchor\/init(anchorwithviewcontroller:)"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADInReadAnchor":{"role":"symbol","title":"TADInReadAnchor","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADInReadAnchor"}],"abstract":[{"type":"text","text":"顯示 InReadAnchor 廣告的視圖。"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInReadAnchor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TADInReadAnchor"}],"url":"\/documentation\/tamediaadsframework\/tadinreadanchor"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initAnchorWithViewController:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initAnchorWithViewController:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initAnchorWithViewController:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"viewController"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADInReadAnchor~1init(anchorWithViewController:)\/title","value":"initAnchorWithViewController:"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADInReadAnchor~1init(anchorWithViewController:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initAnchorWithViewController:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADInReadAnchor\/title","value":"TADInReadAnchor"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADInReadAnchor\/fragments","value":[{"kind":"identifier","text":"TADInReadAnchor"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}