{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"nativeAdDidImpression"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"ad"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAd","preciseIdentifier":"c:objc(cs)TADNativeAd","text":"TADNativeAd"},{"kind":"text","text":"!)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/tamediaadsframework\/tadnativeaddelegate\/nativeaddidimpression(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/tamediaadsframework\/tadnativeaddelegate\/nativeaddidimpression(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdDelegate\/nativeAdDidImpression(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"廣告有效曝光時觸發"}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"nativeAdDidImpression:"}],"role":"symbol","title":"nativeAdDidImpression(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"nativeAdDidImpression"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"TADNativeAd","preciseIdentifier":"c:objc(cs)TADNativeAd"},{"kind":"text","text":"!)"}],"symbolKind":"method","externalID":"c:objc(pl)TADNativeAdDelegate(im)nativeAdDidImpression:","required":true,"modules":[{"name":"TAMediaAdsFramework"}]},"hierarchy":{"paths":[["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdDelegate"]]},"references":{"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework":{"role":"collection","title":"TAMediaAdsFramework","abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","kind":"symbol","type":"topic","url":"\/documentation\/tamediaadsframework"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADNativeAdDelegate/nativeAdDidImpression(_:)":{"navigatorTitle":[{"kind":"identifier","text":"nativeAdDidImpression:"}],"role":"symbol","title":"nativeAdDidImpression(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"nativeAdDidImpression"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"TADNativeAd","preciseIdentifier":"c:objc(cs)TADNativeAd"},{"kind":"text","text":"!)"}],"abstract":[{"type":"text","text":"廣告有效曝光時觸發"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdDelegate\/nativeAdDidImpression(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/tamediaadsframework\/tadnativeaddelegate\/nativeaddidimpression(_:)"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADNativeAdDelegate":{"role":"symbol","title":"TADNativeAdDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADNativeAdDelegate"}],"abstract":[{"type":"text","text":"用於從 TADNativeAdDelegate 接收狀態更改消息的委託，例如原生廣告請求成功\/失敗。"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TADNativeAdDelegate"}],"url":"\/documentation\/tamediaadsframework\/tadnativeaddelegate"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADNativeAd":{"role":"symbol","title":"TADNativeAd","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADNativeAd"}],"abstract":[{"type":"text","text":"Native廣告的物件。"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAd","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TADNativeAd"}],"url":"\/documentation\/tamediaadsframework\/tadnativead"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"nativeAdDidImpression:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"nativeAdDidImpression:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"nativeAdDidImpression:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAd","preciseIdentifier":"c:objc(cs)TADNativeAd","text":"TADNativeAd"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"ad"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAdDelegate~1nativeAdDidImpression(_:)\/title","value":"nativeAdDidImpression:"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAdDelegate~1nativeAdDidImpression(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"nativeAdDidImpression:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAdDelegate\/title","value":"TADNativeAdDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAdDelegate\/fragments","value":[{"kind":"identifier","text":"TADNativeAdDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAd\/title","value":"TADNativeAd"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAd\/fragments","value":[{"kind":"identifier","text":"TADNativeAd"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}