{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"anchorWillLeaveApplication"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"anchor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInReadAnchor","preciseIdentifier":"c:objc(cs)TADInReadAnchor","text":"TADInReadAnchor"},{"kind":"text","text":"!)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/tamediaadsframework\/tadinreadanchordelegate\/anchorwillleaveapplication(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/tamediaadsframework\/tadinreadanchordelegate\/anchorwillleaveapplication(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInReadAnchorDelegate\/anchorWillLeaveApplication(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"在應用程序將進入後台或終止之前發送，因為用戶點擊的廣告將啟動另一個應用程序（例如AppStore）。"},{"type":"text","text":" "},{"type":"text","text":"將比普通的 UIApplicationDelegate 方法早調用，比如applicationDidEnterBackground"}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"anchorWillLeaveApplication:"}],"role":"symbol","title":"anchorWillLeaveApplication(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"anchorWillLeaveApplication"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"TADInReadAnchor","preciseIdentifier":"c:objc(cs)TADInReadAnchor"},{"kind":"text","text":"!)"}],"symbolKind":"method","externalID":"c:objc(pl)TADInReadAnchorDelegate(im)anchorWillLeaveApplication:","required":true,"modules":[{"name":"TAMediaAdsFramework"}]},"hierarchy":{"paths":[["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInReadAnchorDelegate"]]},"references":{"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADInReadAnchorDelegate/anchorWillLeaveApplication(_:)":{"navigatorTitle":[{"kind":"identifier","text":"anchorWillLeaveApplication:"}],"role":"symbol","title":"anchorWillLeaveApplication(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"anchorWillLeaveApplication"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"TADInReadAnchor","preciseIdentifier":"c:objc(cs)TADInReadAnchor"},{"kind":"text","text":"!)"}],"abstract":[{"type":"text","text":"在應用程序將進入後台或終止之前發送，因為用戶點擊的廣告將啟動另一個應用程序（例如AppStore）。"},{"type":"text","text":" "},{"type":"text","text":"將比普通的 UIApplicationDelegate 方法早調用，比如applicationDidEnterBackground"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInReadAnchorDelegate\/anchorWillLeaveApplication(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/tamediaadsframework\/tadinreadanchordelegate\/anchorwillleaveapplication(_:)"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework":{"role":"collection","title":"TAMediaAdsFramework","abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","kind":"symbol","type":"topic","url":"\/documentation\/tamediaadsframework"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADInReadAnchor":{"role":"symbol","title":"TADInReadAnchor","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADInReadAnchor"}],"abstract":[{"type":"text","text":"顯示 InReadAnchor 廣告的視圖。"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInReadAnchor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TADInReadAnchor"}],"url":"\/documentation\/tamediaadsframework\/tadinreadanchor"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADInReadAnchorDelegate":{"role":"symbol","title":"TADInReadAnchorDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADInReadAnchorDelegate"}],"abstract":[{"type":"text","text":"用於從 TADInReadAnchor 接收狀態更改消息的委託，例如廣告請求成功\/失敗或點擊廣告時。"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInReadAnchorDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TADInReadAnchorDelegate"}],"url":"\/documentation\/tamediaadsframework\/tadinreadanchordelegate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"anchorWillLeaveApplication:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"anchorWillLeaveApplication:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"anchorWillLeaveApplication:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInReadAnchor","preciseIdentifier":"c:objc(cs)TADInReadAnchor","text":"TADInReadAnchor"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"anchor"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADInReadAnchorDelegate~1anchorWillLeaveApplication(_:)\/title","value":"anchorWillLeaveApplication:"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADInReadAnchorDelegate~1anchorWillLeaveApplication(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"anchorWillLeaveApplication:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADInReadAnchor\/title","value":"TADInReadAnchor"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADInReadAnchor\/fragments","value":[{"kind":"identifier","text":"TADInReadAnchor"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADInReadAnchorDelegate\/title","value":"TADInReadAnchorDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADInReadAnchorDelegate\/fragments","value":[{"kind":"identifier","text":"TADInReadAnchorDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}