{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"minimized"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/tamediaadsframework\/omidplayerstate\/minimized"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/tamediaadsframework\/omidplayerstate\/minimized"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDPlayerState\/minimized","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The player is collapsed in such a way that the video is hidden."},{"type":"text","text":" "},{"type":"text","text":"The video may or may not still be progressing in this state, and sound may be audible."},{"type":"text","text":" "},{"type":"text","text":"This refers specifically to the video player state on the page, and not the state of"},{"type":"text","text":" "},{"type":"text","text":"the browser window."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"minimized"}],"title":"OMIDPlayerState.minimized","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@OMIDPlayerState@OMIDPlayerStateMinimized","modules":[{"name":"TAMediaAdsFramework"}],"navigatorTitle":[{"kind":"identifier","text":"OMIDPlayerStateMinimized"}]},"hierarchy":{"paths":[["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDPlayerState"]]},"references":{"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/OMIDPlayerState/minimized":{"role":"symbol","title":"OMIDPlayerState.minimized","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"minimized"}],"abstract":[{"type":"text","text":"The player is collapsed in such a way that the video is hidden."},{"type":"text","text":" "},{"type":"text","text":"The video may or may not still be progressing in this state, and sound may be audible."},{"type":"text","text":" "},{"type":"text","text":"This refers specifically to the video player state on the page, and not the state of"},{"type":"text","text":" "},{"type":"text","text":"the browser window."}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDPlayerState\/minimized","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OMIDPlayerStateMinimized"}],"url":"\/documentation\/tamediaadsframework\/omidplayerstate\/minimized"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework":{"role":"collection","title":"TAMediaAdsFramework","abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","kind":"symbol","type":"topic","url":"\/documentation\/tamediaadsframework"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/OMIDPlayerState":{"role":"symbol","title":"OMIDPlayerState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"OMIDPlayerState"}],"abstract":[{"type":"text","text":"List of supported media event player states."}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDPlayerState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OMIDPlayerState"}],"url":"\/documentation\/tamediaadsframework\/omidplayerstate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"OMIDPlayerStateMinimized"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"OMIDPlayerStateMinimized"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"OMIDPlayerStateMinimized"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDPlayerState~1minimized\/title","value":"OMIDPlayerStateMinimized"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDPlayerState~1minimized\/fragments","value":[{"kind":"identifier","text":"OMIDPlayerStateMinimized"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDPlayerState\/title","value":"OMIDPlayerState"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDPlayerState\/fragments","value":[{"kind":"identifier","text":"OMIDPlayerState"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}