{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"OMIDInteractionType"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/tamediaadsframework\/omidinteractiontype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/tamediaadsframework\/omidinteractiontype"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/SQ","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/SH","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/SY","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDInteractionType","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"List of supported media event user interaction types."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"OMIDInteractionType"}],"title":"OMIDInteractionType","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@OMIDInteractionType","modules":[{"name":"TAMediaAdsFramework"}],"navigatorTitle":[{"kind":"identifier","text":"OMIDInteractionType"}]},"hierarchy":{"paths":[["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDInteractionType\/acceptInvitation","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDInteractionType\/click"]},{"title":"Initializers","identifiers":["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDInteractionType\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDInteractionType\/Equatable-Implementations","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDInteractionType\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/OMIDInteractionType/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDInteractionType\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/tamediaadsframework\/omidinteractiontype\/rawrepresentable-implementations"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/OMIDInteractionType":{"role":"symbol","title":"OMIDInteractionType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"OMIDInteractionType"}],"abstract":[{"type":"text","text":"List of supported media event user interaction types."}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDInteractionType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OMIDInteractionType"}],"url":"\/documentation\/tamediaadsframework\/omidinteractiontype"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework":{"role":"collection","title":"TAMediaAdsFramework","abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","kind":"symbol","type":"topic","url":"\/documentation\/tamediaadsframework"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/OMIDInteractionType/acceptInvitation":{"role":"symbol","title":"OMIDInteractionType.acceptInvitation","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"acceptInvitation"}],"abstract":[{"type":"text","text":"The user engaged with ad content to load a separate experience."}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDInteractionType\/acceptInvitation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OMIDInteractionTypeAcceptInvitation"}],"url":"\/documentation\/tamediaadsframework\/omidinteractiontype\/acceptinvitation"},"doc://com.taiwanmobile.TAMediaAdsFramework/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/SY"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/OMIDInteractionType/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDInteractionType\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/tamediaadsframework\/omidinteractiontype\/init(rawvalue:)"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/OMIDInteractionType/click":{"role":"symbol","title":"OMIDInteractionType.click","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"click"}],"abstract":[{"type":"text","text":"The user clicked to load the ad’s landing page."}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDInteractionType\/click","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OMIDInteractionTypeClick"}],"url":"\/documentation\/tamediaadsframework\/omidinteractiontype\/click"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/OMIDInteractionType/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDInteractionType\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/tamediaadsframework\/omidinteractiontype\/equatable-implementations"},"doc://com.taiwanmobile.TAMediaAdsFramework/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/SH"},"doc://com.taiwanmobile.TAMediaAdsFramework/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/SQ"},"doc://com.taiwanmobile.TAMediaAdsFramework/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/s8SendableP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"OMIDInteractionType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"OMIDInteractionType"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"OMIDInteractionType"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDInteractionType\/acceptInvitation","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/OMIDInteractionType\/click"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"OMIDInteractionType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDInteractionType\/title","value":"OMIDInteractionType"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDInteractionType\/fragments","value":[{"kind":"identifier","text":"OMIDInteractionType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDInteractionType~1acceptInvitation\/title","value":"OMIDInteractionTypeAcceptInvitation"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDInteractionType~1acceptInvitation\/fragments","value":[{"kind":"identifier","text":"OMIDInteractionTypeAcceptInvitation"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDInteractionType~1click\/title","value":"OMIDInteractionTypeClick"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1OMIDInteractionType~1click\/fragments","value":[{"kind":"identifier","text":"OMIDInteractionTypeClick"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}