{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADBannerViewDelegate"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/tamediaadsframework\/tadbannerviewdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/tamediaadsframework\/tadbannerviewdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"identifier":{"url":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADBannerViewDelegate","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"用於從 TADBannerView 接收狀態更改消息的委託，例如廣告請求成功\/失敗或點擊廣告時。"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADBannerViewDelegate"}],"title":"TADBannerViewDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:objc(pl)TADBannerViewDelegate","modules":[{"name":"TAMediaAdsFramework"}],"navigatorTitle":[{"kind":"identifier","text":"TADBannerViewDelegate"}]},"hierarchy":{"paths":[["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADBannerViewDelegate\/adView(_:didFailToReceiveAdWithError:)","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADBannerViewDelegate\/adViewDidDismissScreen(_:)","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADBannerViewDelegate\/adViewDidReceiveAd(_:)","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADBannerViewDelegate\/adViewWillDismissScreen(_:)","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADBannerViewDelegate\/adViewWillLeaveApplication(_:)","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADBannerViewDelegate\/adViewWillPresentScreen(_:)"]}],"references":{"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADBannerViewDelegate/adViewDidDismissScreen(_:)":{"navigatorTitle":[{"kind":"identifier","text":"adViewDidDismissScreen:"}],"role":"symbol","title":"adViewDidDismissScreen(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"adViewDidDismissScreen"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"TADBannerView","preciseIdentifier":"c:objc(cs)TADBannerView"},{"kind":"text","text":"!)"}],"abstract":[{"type":"text","text":"廣告即將被關閉之前被呼叫"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADBannerViewDelegate\/adViewDidDismissScreen(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/tamediaadsframework\/tadbannerviewdelegate\/adviewdiddismissscreen(_:)"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADBannerViewDelegate/adView(_:didFailToReceiveAdWithError:)":{"navigatorTitle":[{"kind":"identifier","text":"adView:didFailToReceiveAdWithError:"}],"role":"symbol","title":"adView(_:didFailToReceiveAdWithError:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"adView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"TADBannerView","preciseIdentifier":"c:objc(cs)TADBannerView"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"didFailToReceiveAdWithError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TADRequestError","preciseIdentifier":"c:objc(cs)TADRequestError"},{"kind":"text","text":"!)"}],"abstract":[{"type":"text","text":"廣告取得失敗"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADBannerViewDelegate\/adView(_:didFailToReceiveAdWithError:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/tamediaadsframework\/tadbannerviewdelegate\/adview(_:didfailtoreceiveadwitherror:)"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADBannerViewDelegate":{"role":"symbol","title":"TADBannerViewDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADBannerViewDelegate"}],"abstract":[{"type":"text","text":"用於從 TADBannerView 接收狀態更改消息的委託，例如廣告請求成功\/失敗或點擊廣告時。"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADBannerViewDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TADBannerViewDelegate"}],"url":"\/documentation\/tamediaadsframework\/tadbannerviewdelegate"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework":{"role":"collection","title":"TAMediaAdsFramework","abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","kind":"symbol","type":"topic","url":"\/documentation\/tamediaadsframework"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADBannerViewDelegate/adViewWillPresentScreen(_:)":{"navigatorTitle":[{"kind":"identifier","text":"adViewWillPresentScreen:"}],"role":"symbol","title":"adViewWillPresentScreen(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"adViewWillPresentScreen"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"TADBannerView","preciseIdentifier":"c:objc(cs)TADBannerView"},{"kind":"text","text":"!)"}],"abstract":[{"type":"text","text":"廣告即將被呈現之前被呼叫"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADBannerViewDelegate\/adViewWillPresentScreen(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/tamediaadsframework\/tadbannerviewdelegate\/adviewwillpresentscreen(_:)"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADBannerViewDelegate/adViewWillDismissScreen(_:)":{"navigatorTitle":[{"kind":"identifier","text":"adViewWillDismissScreen:"}],"role":"symbol","title":"adViewWillDismissScreen(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"adViewWillDismissScreen"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"TADBannerView","preciseIdentifier":"c:objc(cs)TADBannerView"},{"kind":"text","text":"!)"}],"abstract":[{"type":"text","text":"廣告即將被關閉之前被呼叫"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADBannerViewDelegate\/adViewWillDismissScreen(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/tamediaadsframework\/tadbannerviewdelegate\/adviewwilldismissscreen(_:)"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADBannerViewDelegate/adViewWillLeaveApplication(_:)":{"navigatorTitle":[{"kind":"identifier","text":"adViewWillLeaveApplication:"}],"role":"symbol","title":"adViewWillLeaveApplication(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"adViewWillLeaveApplication"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"TADBannerView","preciseIdentifier":"c:objc(cs)TADBannerView"},{"kind":"text","text":"!)"}],"abstract":[{"type":"text","text":"在應用程序將進入後台或終止之前發送，因為用戶點擊的廣告將啟動另一個應用程序（例如AppStore）。"},{"type":"text","text":" "},{"type":"text","text":"將比普通的 UIApplicationDelegate 方法早調用，比如applicationDidEnterBackground"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADBannerViewDelegate\/adViewWillLeaveApplication(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/tamediaadsframework\/tadbannerviewdelegate\/adviewwillleaveapplication(_:)"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADBannerViewDelegate/adViewDidReceiveAd(_:)":{"navigatorTitle":[{"kind":"identifier","text":"adViewDidReceiveAd:"}],"role":"symbol","title":"adViewDidReceiveAd(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"adViewDidReceiveAd"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"TADBannerView","preciseIdentifier":"c:objc(cs)TADBannerView"},{"kind":"text","text":"!)"}],"abstract":[{"type":"text","text":"廣告取得成功"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADBannerViewDelegate\/adViewDidReceiveAd(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/tamediaadsframework\/tadbannerviewdelegate\/adviewdidreceivead(_:)"},"doc://com.taiwanmobile.TAMediaAdsFramework/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)NSObject"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"TADBannerViewDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"TADBannerViewDelegate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"TADBannerViewDelegate"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADBannerViewDelegate\/adView(_:didFailToReceiveAdWithError:)","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADBannerViewDelegate\/adViewDidDismissScreen(_:)","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADBannerViewDelegate\/adViewDidReceiveAd(_:)","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADBannerViewDelegate\/adViewWillDismissScreen(_:)","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADBannerViewDelegate\/adViewWillLeaveApplication(_:)","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADBannerViewDelegate\/adViewWillPresentScreen(_:)"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADBannerViewDelegate"},{"kind":"text","text":"<"},{"kind":"keyword","text":"NSObject"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADBannerViewDelegate~1adViewDidDismissScreen(_:)\/title","value":"adViewDidDismissScreen:"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADBannerViewDelegate~1adViewDidDismissScreen(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"adViewDidDismissScreen:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADBannerViewDelegate~1adView(_:didFailToReceiveAdWithError:)\/title","value":"adView:didFailToReceiveAdWithError:"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADBannerViewDelegate~1adView(_:didFailToReceiveAdWithError:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"adView:didFailToReceiveAdWithError:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADBannerViewDelegate\/title","value":"TADBannerViewDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADBannerViewDelegate\/fragments","value":[{"kind":"identifier","text":"TADBannerViewDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADBannerViewDelegate~1adViewWillPresentScreen(_:)\/title","value":"adViewWillPresentScreen:"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADBannerViewDelegate~1adViewWillPresentScreen(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"adViewWillPresentScreen:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADBannerViewDelegate~1adViewWillDismissScreen(_:)\/title","value":"adViewWillDismissScreen:"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADBannerViewDelegate~1adViewWillDismissScreen(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"adViewWillDismissScreen:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADBannerViewDelegate~1adViewWillLeaveApplication(_:)\/title","value":"adViewWillLeaveApplication:"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADBannerViewDelegate~1adViewWillLeaveApplication(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"adViewWillLeaveApplication:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADBannerViewDelegate~1adViewDidReceiveAd(_:)\/title","value":"adViewDidReceiveAd:"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADBannerViewDelegate~1adViewDidReceiveAd(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"adViewDidReceiveAd:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}