{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADErrorCode"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/tamediaadsframework\/taderrorcode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/tamediaadsframework\/taderrorcode"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/SQ","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/SH","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/SY","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADErrorCode","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"TAmedia中定義的NSError資訊"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADErrorCode"}],"title":"TADErrorCode","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@TADErrorCode","modules":[{"name":"TAMediaAdsFramework"}],"navigatorTitle":[{"kind":"identifier","text":"TADErrorCode"}]},"hierarchy":{"paths":[["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADErrorCode\/interstitialAlreadyUsed","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADErrorCode\/invalidRequest","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADErrorCode\/networkError","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADErrorCode\/noFill","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADErrorCode\/osVersionTooLow","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADErrorCode\/serverError","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADErrorCode\/timeout"]},{"title":"Initializers","identifiers":["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADErrorCode\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADErrorCode\/Equatable-Implementations","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADErrorCode\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADErrorCode/invalidRequest":{"role":"symbol","title":"TADErrorCode.invalidRequest","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidRequest"}],"abstract":[{"type":"text","text":"廣告請求無效。 localizedFailureReason 錯誤說明"},{"type":"text","text":" "},{"type":"text","text":"會有更多細節。 通常這是因為廣告沒有"},{"type":"text","text":" "},{"type":"text","text":"廣告單元 ID 或根視圖控制器集。"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADErrorCode\/invalidRequest","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"kTADErrorInvalidRequest"}],"url":"\/documentation\/tamediaadsframework\/taderrorcode\/invalidrequest"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADErrorCode/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADErrorCode\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/tamediaadsframework\/taderrorcode\/init(rawvalue:)"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADErrorCode":{"role":"symbol","title":"TADErrorCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADErrorCode"}],"abstract":[{"type":"text","text":"TAmedia中定義的NSError資訊"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADErrorCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TADErrorCode"}],"url":"\/documentation\/tamediaadsframework\/taderrorcode"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADErrorCode/interstitialAlreadyUsed":{"role":"symbol","title":"TADErrorCode.interstitialAlreadyUsed","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"interstitialAlreadyUsed"}],"abstract":[{"type":"text","text":"不會發送請求，因為插頁式對像已經被用過。"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADErrorCode\/interstitialAlreadyUsed","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"kTADErrorInterstitialAlreadyUsed"}],"url":"\/documentation\/tamediaadsframework\/taderrorcode\/interstitialalreadyused"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADErrorCode/networkError":{"role":"symbol","title":"TADErrorCode.networkError","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"networkError"}],"abstract":[{"type":"text","text":"從網絡加載數據時出錯。"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADErrorCode\/networkError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"kTADErrorNetworkError"}],"url":"\/documentation\/tamediaadsframework\/taderrorcode\/networkerror"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADErrorCode/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADErrorCode\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/tamediaadsframework\/taderrorcode\/rawrepresentable-implementations"},"doc://com.taiwanmobile.TAMediaAdsFramework/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/SQ"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADErrorCode/noFill":{"role":"symbol","title":"TADErrorCode.noFill","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"noFill"}],"abstract":[{"type":"text","text":"廣告請求成功，但沒有返回廣告。"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADErrorCode\/noFill","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"kTADErrorNoFill"}],"url":"\/documentation\/tamediaadsframework\/taderrorcode\/nofill"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADErrorCode/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADErrorCode\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/tamediaadsframework\/taderrorcode\/equatable-implementations"},"doc://com.taiwanmobile.TAMediaAdsFramework/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/s8SendableP"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework":{"role":"collection","title":"TAMediaAdsFramework","abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","kind":"symbol","type":"topic","url":"\/documentation\/tamediaadsframework"},"doc://com.taiwanmobile.TAMediaAdsFramework/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/SH"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADErrorCode/serverError":{"role":"symbol","title":"TADErrorCode.serverError","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"serverError"}],"abstract":[{"type":"text","text":"廣告服務器在處理請求時遇到失敗。"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADErrorCode\/serverError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"kTADErrorServerError"}],"url":"\/documentation\/tamediaadsframework\/taderrorcode\/servererror"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADErrorCode/osVersionTooLow":{"role":"symbol","title":"TADErrorCode.osVersionTooLow","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"osVersionTooLow"}],"abstract":[{"type":"text","text":"當前設備的操作系統低於最低要求版本。"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADErrorCode\/osVersionTooLow","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"kTADErrorOSVersionTooLow"}],"url":"\/documentation\/tamediaadsframework\/taderrorcode\/osversiontoolow"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADErrorCode/timeout":{"role":"symbol","title":"TADErrorCode.timeout","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"timeout"}],"abstract":[{"type":"text","text":"請求在超時之前無法加載。"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADErrorCode\/timeout","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"kTADErrorTimeout"}],"url":"\/documentation\/tamediaadsframework\/taderrorcode\/timeout"},"doc://com.taiwanmobile.TAMediaAdsFramework/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/SY"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"TADErrorCode"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"TADErrorCode"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"TADErrorCode"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADErrorCode\/interstitialAlreadyUsed","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADErrorCode\/invalidRequest","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADErrorCode\/networkError","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADErrorCode\/noFill","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADErrorCode\/osVersionTooLow","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADErrorCode\/serverError","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADErrorCode\/timeout"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADErrorCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADErrorCode~1invalidRequest\/title","value":"kTADErrorInvalidRequest"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADErrorCode~1invalidRequest\/fragments","value":[{"kind":"identifier","text":"kTADErrorInvalidRequest"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADErrorCode\/title","value":"TADErrorCode"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADErrorCode\/fragments","value":[{"kind":"identifier","text":"TADErrorCode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADErrorCode~1interstitialAlreadyUsed\/title","value":"kTADErrorInterstitialAlreadyUsed"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADErrorCode~1interstitialAlreadyUsed\/fragments","value":[{"kind":"identifier","text":"kTADErrorInterstitialAlreadyUsed"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADErrorCode~1networkError\/title","value":"kTADErrorNetworkError"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADErrorCode~1networkError\/fragments","value":[{"kind":"identifier","text":"kTADErrorNetworkError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADErrorCode~1noFill\/title","value":"kTADErrorNoFill"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADErrorCode~1noFill\/fragments","value":[{"kind":"identifier","text":"kTADErrorNoFill"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADErrorCode~1serverError\/title","value":"kTADErrorServerError"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADErrorCode~1serverError\/fragments","value":[{"kind":"identifier","text":"kTADErrorServerError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADErrorCode~1osVersionTooLow\/title","value":"kTADErrorOSVersionTooLow"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADErrorCode~1osVersionTooLow\/fragments","value":[{"kind":"identifier","text":"kTADErrorOSVersionTooLow"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADErrorCode~1timeout\/title","value":"kTADErrorTimeout"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADErrorCode~1timeout\/fragments","value":[{"kind":"identifier","text":"kTADErrorTimeout"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}