{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADInReadAnchorDelegate"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/tamediaadsframework\/tadinreadanchordelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/tamediaadsframework\/tadinreadanchordelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"identifier":{"url":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInReadAnchorDelegate","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"用於從 TADInReadAnchor 接收狀態更改消息的委託，例如廣告請求成功\/失敗或點擊廣告時。"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADInReadAnchorDelegate"}],"title":"TADInReadAnchorDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:objc(pl)TADInReadAnchorDelegate","modules":[{"name":"TAMediaAdsFramework"}],"navigatorTitle":[{"kind":"identifier","text":"TADInReadAnchorDelegate"}]},"hierarchy":{"paths":[["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInReadAnchorDelegate\/anchor(_:didFailToReceiveAdWithError:)","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInReadAnchorDelegate\/anchorDidReceiveAd(_:)","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInReadAnchorDelegate\/anchorUserPressedCloseAd()","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInReadAnchorDelegate\/anchorWillLeaveApplication(_:)","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInReadAnchorDelegate\/anchorWillShow(_:)"]}],"references":{"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADInReadAnchorDelegate":{"role":"symbol","title":"TADInReadAnchorDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADInReadAnchorDelegate"}],"abstract":[{"type":"text","text":"用於從 TADInReadAnchor 接收狀態更改消息的委託，例如廣告請求成功\/失敗或點擊廣告時。"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInReadAnchorDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TADInReadAnchorDelegate"}],"url":"\/documentation\/tamediaadsframework\/tadinreadanchordelegate"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADInReadAnchorDelegate/anchorWillLeaveApplication(_:)":{"navigatorTitle":[{"kind":"identifier","text":"anchorWillLeaveApplication:"}],"role":"symbol","title":"anchorWillLeaveApplication(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"anchorWillLeaveApplication"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"TADInReadAnchor","preciseIdentifier":"c:objc(cs)TADInReadAnchor"},{"kind":"text","text":"!)"}],"abstract":[{"type":"text","text":"在應用程序將進入後台或終止之前發送，因為用戶點擊的廣告將啟動另一個應用程序（例如AppStore）。"},{"type":"text","text":" "},{"type":"text","text":"將比普通的 UIApplicationDelegate 方法早調用，比如applicationDidEnterBackground"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInReadAnchorDelegate\/anchorWillLeaveApplication(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/tamediaadsframework\/tadinreadanchordelegate\/anchorwillleaveapplication(_:)"},"doc://com.taiwanmobile.TAMediaAdsFramework/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)NSObject"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADInReadAnchorDelegate/anchorWillShow(_:)":{"navigatorTitle":[{"kind":"identifier","text":"anchorWillShow:"}],"role":"symbol","title":"anchorWillShow(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"anchorWillShow"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"TADInReadAnchor","preciseIdentifier":"c:objc(cs)TADInReadAnchor"},{"kind":"text","text":"!)"}],"abstract":[{"type":"text","text":"anchor廣告版位即將顯示"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInReadAnchorDelegate\/anchorWillShow(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/tamediaadsframework\/tadinreadanchordelegate\/anchorwillshow(_:)"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADInReadAnchorDelegate/anchorUserPressedCloseAd()":{"navigatorTitle":[{"kind":"identifier","text":"anchorUserPressedCloseAd"}],"role":"symbol","title":"anchorUserPressedCloseAd()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"anchorUserPressedCloseAd"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"使用者點按關閉廣告"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInReadAnchorDelegate\/anchorUserPressedCloseAd()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/tamediaadsframework\/tadinreadanchordelegate\/anchoruserpressedclosead()"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADInReadAnchorDelegate/anchor(_:didFailToReceiveAdWithError:)":{"navigatorTitle":[{"kind":"identifier","text":"anchor:didFailToReceiveAdWithError:"}],"role":"symbol","title":"anchor(_:didFailToReceiveAdWithError:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"anchor"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"TADInReadAnchor","preciseIdentifier":"c:objc(cs)TADInReadAnchor"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"didFailToReceiveAdWithError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TADRequestError","preciseIdentifier":"c:objc(cs)TADRequestError"},{"kind":"text","text":"!)"}],"abstract":[{"type":"text","text":"在收到廣告請求失敗時發送。"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInReadAnchorDelegate\/anchor(_:didFailToReceiveAdWithError:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/tamediaadsframework\/tadinreadanchordelegate\/anchor(_:didfailtoreceiveadwitherror:)"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADInReadAnchorDelegate/anchorDidReceiveAd(_:)":{"navigatorTitle":[{"kind":"identifier","text":"anchorDidReceiveAd:"}],"role":"symbol","title":"anchorDidReceiveAd(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"anchorDidReceiveAd"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"TADInReadAnchor","preciseIdentifier":"c:objc(cs)TADInReadAnchor"},{"kind":"text","text":"!)"}],"abstract":[{"type":"text","text":"在收到廣告請求成功時發送。"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInReadAnchorDelegate\/anchorDidReceiveAd(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/tamediaadsframework\/tadinreadanchordelegate\/anchordidreceivead(_:)"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework":{"role":"collection","title":"TAMediaAdsFramework","abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","kind":"symbol","type":"topic","url":"\/documentation\/tamediaadsframework"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"TADInReadAnchorDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"TADInReadAnchorDelegate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"TADInReadAnchorDelegate"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInReadAnchorDelegate\/anchor(_:didFailToReceiveAdWithError:)","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInReadAnchorDelegate\/anchorDidReceiveAd(_:)","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInReadAnchorDelegate\/anchorUserPressedCloseAd()","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInReadAnchorDelegate\/anchorWillLeaveApplication(_:)","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInReadAnchorDelegate\/anchorWillShow(_:)"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADInReadAnchorDelegate"},{"kind":"text","text":"<"},{"kind":"keyword","text":"NSObject"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADInReadAnchorDelegate\/title","value":"TADInReadAnchorDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADInReadAnchorDelegate\/fragments","value":[{"kind":"identifier","text":"TADInReadAnchorDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADInReadAnchorDelegate~1anchorWillLeaveApplication(_:)\/title","value":"anchorWillLeaveApplication:"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADInReadAnchorDelegate~1anchorWillLeaveApplication(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"anchorWillLeaveApplication:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADInReadAnchorDelegate~1anchorWillShow(_:)\/title","value":"anchorWillShow:"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADInReadAnchorDelegate~1anchorWillShow(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"anchorWillShow:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADInReadAnchorDelegate~1anchorUserPressedCloseAd()\/title","value":"anchorUserPressedCloseAd"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADInReadAnchorDelegate~1anchorUserPressedCloseAd()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"anchorUserPressedCloseAd"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADInReadAnchorDelegate~1anchor(_:didFailToReceiveAdWithError:)\/title","value":"anchor:didFailToReceiveAdWithError:"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADInReadAnchorDelegate~1anchor(_:didFailToReceiveAdWithError:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"anchor:didFailToReceiveAdWithError:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADInReadAnchorDelegate~1anchorDidReceiveAd(_:)\/title","value":"anchorDidReceiveAd:"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADInReadAnchorDelegate~1anchorDidReceiveAd(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"anchorDidReceiveAd:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}