{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADInterstitialDelegate"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/tamediaadsframework\/tadinterstitialdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/tamediaadsframework\/tadinterstitialdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"identifier":{"url":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInterstitialDelegate","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"用於從 TADInterstitialDelegate 接收狀態更改消息的委託，例如插頁式廣告請求成功\/失敗。"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADInterstitialDelegate"}],"title":"TADInterstitialDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:objc(pl)TADInterstitialDelegate","modules":[{"name":"TAMediaAdsFramework"}],"navigatorTitle":[{"kind":"identifier","text":"TADInterstitialDelegate"}]},"hierarchy":{"paths":[["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInterstitialDelegate\/interstitial(_:didFailToReceiveAdWithError:)","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInterstitialDelegate\/interstitialDidDismissScreen(_:)","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInterstitialDelegate\/interstitialDidReceiveAd(_:)","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInterstitialDelegate\/interstitialWillDismissScreen(_:)","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInterstitialDelegate\/interstitialWillLeaveApplication(_:)","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInterstitialDelegate\/interstitialWillPresentScreen(_:)"]}],"references":{"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADInterstitialDelegate/interstitialWillDismissScreen(_:)":{"navigatorTitle":[{"kind":"identifier","text":"interstitialWillDismissScreen:"}],"role":"symbol","title":"interstitialWillDismissScreen(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"interstitialWillDismissScreen"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"TADInterstitial","preciseIdentifier":"c:objc(cs)TADInterstitial"},{"kind":"text","text":"!)"}],"abstract":[{"type":"text","text":"Interstitial廣告關閉, 在螢幕上消失之前呼叫, 再次提醒在Interstitail消失前, 必須將Interstitial及delegate設為nil (可以在這個function中執行)"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInterstitialDelegate\/interstitialWillDismissScreen(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/tamediaadsframework\/tadinterstitialdelegate\/interstitialwilldismissscreen(_:)"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADInterstitialDelegate":{"role":"symbol","title":"TADInterstitialDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADInterstitialDelegate"}],"abstract":[{"type":"text","text":"用於從 TADInterstitialDelegate 接收狀態更改消息的委託，例如插頁式廣告請求成功\/失敗。"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInterstitialDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TADInterstitialDelegate"}],"url":"\/documentation\/tamediaadsframework\/tadinterstitialdelegate"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADInterstitialDelegate/interstitialDidDismissScreen(_:)":{"navigatorTitle":[{"kind":"identifier","text":"interstitialDidDismissScreen:"}],"role":"symbol","title":"interstitialDidDismissScreen(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"interstitialDidDismissScreen"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"TADInterstitial","preciseIdentifier":"c:objc(cs)TADInterstitial"},{"kind":"text","text":"!)"}],"abstract":[{"type":"text","text":"Interstitial廣告關閉, 在螢幕上消失之後呼叫"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInterstitialDelegate\/interstitialDidDismissScreen(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/tamediaadsframework\/tadinterstitialdelegate\/interstitialdiddismissscreen(_:)"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADInterstitialDelegate/interstitialDidReceiveAd(_:)":{"navigatorTitle":[{"kind":"identifier","text":"interstitialDidReceiveAd:"}],"role":"symbol","title":"interstitialDidReceiveAd(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"interstitialDidReceiveAd"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"TADInterstitial","preciseIdentifier":"c:objc(cs)TADInterstitial"},{"kind":"text","text":"!)"}],"abstract":[{"type":"text","text":"廣告取得成功，可以在此時間點及之後顯示呈現廣告"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInterstitialDelegate\/interstitialDidReceiveAd(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/tamediaadsframework\/tadinterstitialdelegate\/interstitialdidreceivead(_:)"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADInterstitialDelegate/interstitial(_:didFailToReceiveAdWithError:)":{"navigatorTitle":[{"kind":"identifier","text":"interstitial:didFailToReceiveAdWithError:"}],"role":"symbol","title":"interstitial(_:didFailToReceiveAdWithError:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"interstitial"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"TADInterstitial","preciseIdentifier":"c:objc(cs)TADInterstitial"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"didFailToReceiveAdWithError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TADRequestError","preciseIdentifier":"c:objc(cs)TADRequestError"},{"kind":"text","text":"!)"}],"abstract":[{"type":"text","text":"廣告取得失敗"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInterstitialDelegate\/interstitial(_:didFailToReceiveAdWithError:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/tamediaadsframework\/tadinterstitialdelegate\/interstitial(_:didfailtoreceiveadwitherror:)"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADInterstitialDelegate/interstitialWillPresentScreen(_:)":{"navigatorTitle":[{"kind":"identifier","text":"interstitialWillPresentScreen:"}],"role":"symbol","title":"interstitialWillPresentScreen(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"interstitialWillPresentScreen"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"TADInterstitial","preciseIdentifier":"c:objc(cs)TADInterstitial"},{"kind":"text","text":"!)"}],"abstract":[{"type":"text","text":"Interstitial廣告呈現之前呼叫, 注意使用者可能會在廣告內按下連結(網頁, AppStore, …)而因此離開應用程式, 可以在這function中處理該暫停之項目"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInterstitialDelegate\/interstitialWillPresentScreen(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/tamediaadsframework\/tadinterstitialdelegate\/interstitialwillpresentscreen(_:)"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework":{"role":"collection","title":"TAMediaAdsFramework","abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","kind":"symbol","type":"topic","url":"\/documentation\/tamediaadsframework"},"doc://com.taiwanmobile.TAMediaAdsFramework/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)NSObject"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADInterstitialDelegate/interstitialWillLeaveApplication(_:)":{"navigatorTitle":[{"kind":"identifier","text":"interstitialWillLeaveApplication:"}],"role":"symbol","title":"interstitialWillLeaveApplication(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"interstitialWillLeaveApplication"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"TADInterstitial","preciseIdentifier":"c:objc(cs)TADInterstitial"},{"kind":"text","text":"!)"}],"abstract":[{"type":"text","text":"在應用程序將進入後台或終止之前發送，因為用戶點擊的廣告將啟動另一個應用程序（例如AppStore）。"},{"type":"text","text":" "},{"type":"text","text":"將比普通的 UIApplicationDelegate 方法早調用，比如applicationDidEnterBackground"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInterstitialDelegate\/interstitialWillLeaveApplication(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/tamediaadsframework\/tadinterstitialdelegate\/interstitialwillleaveapplication(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"TADInterstitialDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"TADInterstitialDelegate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"TADInterstitialDelegate"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInterstitialDelegate\/interstitial(_:didFailToReceiveAdWithError:)","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInterstitialDelegate\/interstitialDidDismissScreen(_:)","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInterstitialDelegate\/interstitialDidReceiveAd(_:)","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInterstitialDelegate\/interstitialWillDismissScreen(_:)","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInterstitialDelegate\/interstitialWillLeaveApplication(_:)","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInterstitialDelegate\/interstitialWillPresentScreen(_:)"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADInterstitialDelegate"},{"kind":"text","text":"<"},{"kind":"keyword","text":"NSObject"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADInterstitialDelegate~1interstitialWillDismissScreen(_:)\/title","value":"interstitialWillDismissScreen:"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADInterstitialDelegate~1interstitialWillDismissScreen(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"interstitialWillDismissScreen:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADInterstitialDelegate\/title","value":"TADInterstitialDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADInterstitialDelegate\/fragments","value":[{"kind":"identifier","text":"TADInterstitialDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADInterstitialDelegate~1interstitialDidDismissScreen(_:)\/title","value":"interstitialDidDismissScreen:"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADInterstitialDelegate~1interstitialDidDismissScreen(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"interstitialDidDismissScreen:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADInterstitialDelegate~1interstitialDidReceiveAd(_:)\/title","value":"interstitialDidReceiveAd:"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADInterstitialDelegate~1interstitialDidReceiveAd(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"interstitialDidReceiveAd:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADInterstitialDelegate~1interstitial(_:didFailToReceiveAdWithError:)\/title","value":"interstitial:didFailToReceiveAdWithError:"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADInterstitialDelegate~1interstitial(_:didFailToReceiveAdWithError:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"interstitial:didFailToReceiveAdWithError:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADInterstitialDelegate~1interstitialWillPresentScreen(_:)\/title","value":"interstitialWillPresentScreen:"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADInterstitialDelegate~1interstitialWillPresentScreen(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"interstitialWillPresentScreen:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADInterstitialDelegate~1interstitialWillLeaveApplication(_:)\/title","value":"interstitialWillLeaveApplication:"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADInterstitialDelegate~1interstitialWillLeaveApplication(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"interstitialWillLeaveApplication:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}