{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADNativeAdView"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/tamediaadsframework\/tadnativeadview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/tamediaadsframework\/tadnativeadview"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)NSCoding","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)NSObject","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)CALayerDelegate","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/s7CVarArgP","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/s28CustomDebugStringConvertibleP","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/s23CustomStringConvertibleP","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/SQ","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/SH","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/s8SendableP","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UIAccessibilityIdentification","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UIAppearance","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UIAppearanceContainer","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UICoordinateSpace","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UIDynamicItem","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UIFocusEnvironment","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UIFocusItem","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UIFocusItemContainer","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UILargeContentViewerItem","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UITraitEnvironment","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdView","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"用於呈現 NativeAd 的視圖，內有 Label、ImageView、mediaView 等屬性可控制。"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADNativeAdView"}],"title":"TADNativeAdView","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@TAMediaAdsFramework@objc(cs)TADNativeAdView","modules":[{"name":"TAMediaAdsFramework"}],"navigatorTitle":[{"kind":"identifier","text":"TADNativeAdView"}]},"hierarchy":{"paths":[["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdView\/init(coder:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdView\/bodyLabel","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdView\/callToActionView","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdView\/friendlyObstructions","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdView\/longSubjectLabel","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdView\/mediaView","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdView\/nativeAd","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdView\/rectangleImgeView","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdView\/shortSubjectLabel","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdView\/squareImgeView"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdView\/addFriendlyObstruction(view:purpose:)","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdView\/removeFriendlyObstruction(view:)","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdView\/setImageView(imageView:with:)"]}],"references":{"doc://com.taiwanmobile.TAMediaAdsFramework/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/s28CustomDebugStringConvertibleP"},"doc://com.taiwanmobile.TAMediaAdsFramework/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UIFocusItem"},"doc://com.taiwanmobile.TAMediaAdsFramework/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/s8SendableP"},"doc://com.taiwanmobile.TAMediaAdsFramework/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UITraitEnvironment"},"doc://com.taiwanmobile.TAMediaAdsFramework/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADNativeAdView/friendlyObstructions":{"role":"symbol","title":"friendlyObstructions","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"friendlyObstructions"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"TADFriendlyObstruction","preciseIdentifier":"c:@M@TAMediaAdsFramework@objc(cs)TADFriendlyObstruction"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdView\/friendlyObstructions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"friendlyObstructions"}],"url":"\/documentation\/tamediaadsframework\/tadnativeadview\/friendlyobstructions"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADNativeAdView/mediaView":{"role":"symbol","title":"mediaView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mediaView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TADNativeMediaView","preciseIdentifier":"c:@M@TAMediaAdsFramework@objc(cs)TADNativeMediaView"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"與 xib 做關聯，用來呈現廣告的 media view，呈現影片或圖片"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdView\/mediaView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"mediaView"}],"url":"\/documentation\/tamediaadsframework\/tadnativeadview\/mediaview"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADNativeAdView/addFriendlyObstruction(view:purpose:)":{"role":"symbol","title":"addFriendlyObstruction(view:purpose:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addFriendlyObstruction"},{"kind":"text","text":"("},{"kind":"externalParam","text":"view"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"purpose"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TADFriendlyObstructionPurpose","preciseIdentifier":"c:@M@TAMediaAdsFramework@E@TADFriendyObstrucitonPurpose"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"加入障礙物"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdView\/addFriendlyObstruction(view:purpose:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"addFriendlyObstructionWithView:purpose:"}],"url":"\/documentation\/tamediaadsframework\/tadnativeadview\/addfriendlyobstruction(view:purpose:)"},"doc://com.taiwanmobile.TAMediaAdsFramework/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UICoordinateSpace"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADNativeAdView/rectangleImgeView":{"role":"symbol","title":"rectangleImgeView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rectangleImgeView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImageView","preciseIdentifier":"c:objc(cs)UIImageView"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"與 xib 做關聯，用來呈現廣告的 rectangle image"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdView\/rectangleImgeView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rectangleImgeView"}],"url":"\/documentation\/tamediaadsframework\/tadnativeadview\/rectangleimgeview"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADNativeAdView/setImageView(imageView:with:)":{"role":"symbol","title":"setImageView(imageView:with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setImageView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"imageView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImageView","preciseIdentifier":"c:objc(cs)UIImageView"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"若將 disableContentImageLoading 設為 YES，TADNativeAdImage 內將不提供 image，可利用此方法設定圖片 URL string"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdView\/setImageView(imageView:with:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setImageView:withUrlString:"}],"url":"\/documentation\/tamediaadsframework\/tadnativeadview\/setimageview(imageview:with:)"},"doc://com.taiwanmobile.TAMediaAdsFramework/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/s7CVarArgP"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADNativeAdView/squareImgeView":{"role":"symbol","title":"squareImgeView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"squareImgeView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImageView","preciseIdentifier":"c:objc(cs)UIImageView"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"與 xib 做關聯，用來呈現廣告的 square image"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdView\/squareImgeView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"squareImgeView"}],"url":"\/documentation\/tamediaadsframework\/tadnativeadview\/squareimgeview"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADNativeAdView/bodyLabel":{"role":"symbol","title":"bodyLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bodyLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"與 xib 做關聯，用來呈現廣告的 body"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdView\/bodyLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"bodyLabel"}],"url":"\/documentation\/tamediaadsframework\/tadnativeadview\/bodylabel"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADNativeAdView":{"role":"symbol","title":"TADNativeAdView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADNativeAdView"}],"abstract":[{"type":"text","text":"用於呈現 NativeAd 的視圖，內有 Label、ImageView、mediaView 等屬性可控制。"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TADNativeAdView"}],"url":"\/documentation\/tamediaadsframework\/tadnativeadview"},"doc://com.taiwanmobile.TAMediaAdsFramework/objc(cs)UIView":{"type":"unresolvable","title":"UIView","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(cs)UIView"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework":{"role":"collection","title":"TAMediaAdsFramework","abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","kind":"symbol","type":"topic","url":"\/documentation\/tamediaadsframework"},"doc://com.taiwanmobile.TAMediaAdsFramework/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/SH"},"doc://com.taiwanmobile.TAMediaAdsFramework/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UIAccessibilityIdentification"},"doc://com.taiwanmobile.TAMediaAdsFramework/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADNativeAdView/shortSubjectLabel":{"role":"symbol","title":"shortSubjectLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shortSubjectLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"與 xib 做關聯，用來呈現廣告的 short subject"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdView\/shortSubjectLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"shortSubjectLabel"}],"url":"\/documentation\/tamediaadsframework\/tadnativeadview\/shortsubjectlabel"},"doc://com.taiwanmobile.TAMediaAdsFramework/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UIFocusItemContainer"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADNativeAdView/init(coder:)":{"role":"symbol","title":"init(coder:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"初始物件"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdView\/init(coder:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/tamediaadsframework\/tadnativeadview\/init(coder:)"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADNativeAdView/nativeAd":{"role":"symbol","title":"nativeAd","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"nativeAd"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TADNativeAd","preciseIdentifier":"c:objc(cs)TADNativeAd"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"務必將 Native 廣告物件指定給此屬性，Native 廣告才可正常執行"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdView\/nativeAd","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"nativeAd"}],"url":"\/documentation\/tamediaadsframework\/tadnativeadview\/nativead"},"doc://com.taiwanmobile.TAMediaAdsFramework/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)NSObject"},"doc://com.taiwanmobile.TAMediaAdsFramework/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/s23CustomStringConvertibleP"},"doc://com.taiwanmobile.TAMediaAdsFramework/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UIDynamicItem"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADNativeAdView/callToActionView":{"role":"symbol","title":"callToActionView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"callToActionView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"與 xib 做關聯，用來呈現廣告的 call to action view，讓使用者可以開啟廣告網頁"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdView\/callToActionView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"callToActionView"}],"url":"\/documentation\/tamediaadsframework\/tadnativeadview\/calltoactionview"},"doc://com.taiwanmobile.TAMediaAdsFramework/objc(pl)CALayerDelegate":{"type":"unresolvable","title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)CALayerDelegate"},"doc://com.taiwanmobile.TAMediaAdsFramework/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UIFocusEnvironment"},"doc://com.taiwanmobile.TAMediaAdsFramework/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UIUserActivityRestoring"},"doc://com.taiwanmobile.TAMediaAdsFramework/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADNativeAdView/removeFriendlyObstruction(view:)":{"role":"symbol","title":"removeFriendlyObstruction(view:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeFriendlyObstruction"},{"kind":"text","text":"("},{"kind":"externalParam","text":"view"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"移除障礙物"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdView\/removeFriendlyObstruction(view:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"removeFriendlyObstructionWithView:"}],"url":"\/documentation\/tamediaadsframework\/tadnativeadview\/removefriendlyobstruction(view:)"},"doc://com.taiwanmobile.TAMediaAdsFramework/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UIAppearance"},"doc://com.taiwanmobile.TAMediaAdsFramework/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/SQ"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADNativeAdView/longSubjectLabel":{"role":"symbol","title":"longSubjectLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"longSubjectLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"與 xib 做關聯，用來呈現廣告的 long subject"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdView\/longSubjectLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"longSubjectLabel"}],"url":"\/documentation\/tamediaadsframework\/tadnativeadview\/longsubjectlabel"},"doc://com.taiwanmobile.TAMediaAdsFramework/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UILargeContentViewerItem"},"doc://com.taiwanmobile.TAMediaAdsFramework/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UIAppearanceContainer"},"doc://com.taiwanmobile.TAMediaAdsFramework/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)NSCoding"},"doc://com.taiwanmobile.TAMediaAdsFramework/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)UIResponderStandardEditActions"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"TADNativeAdView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"TADNativeAdView"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"TADNativeAdView"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdView\/bodyLabel","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdView\/callToActionView","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdView\/friendlyObstructions","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdView\/longSubjectLabel","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdView\/mediaView","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdView\/nativeAd","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdView\/rectangleImgeView","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdView\/shortSubjectLabel","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdView\/squareImgeView"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdView\/addFriendlyObstruction(view:purpose:)","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdView\/init(coder:)","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdView\/removeFriendlyObstruction(view:)","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdView\/setImageView(imageView:with:)"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADNativeAdView"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAdView~1friendlyObstructions\/title","value":"friendlyObstructions"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAdView~1friendlyObstructions\/fragments","value":[{"kind":"identifier","text":"friendlyObstructions"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAdView~1mediaView\/title","value":"mediaView"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAdView~1mediaView\/fragments","value":[{"kind":"identifier","text":"mediaView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAdView~1addFriendlyObstruction(view:purpose:)\/title","value":"addFriendlyObstructionWithView:purpose:"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAdView~1addFriendlyObstruction(view:purpose:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addFriendlyObstructionWithView:purpose:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAdView~1rectangleImgeView\/title","value":"rectangleImgeView"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAdView~1rectangleImgeView\/fragments","value":[{"kind":"identifier","text":"rectangleImgeView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAdView~1setImageView(imageView:with:)\/title","value":"setImageView:withUrlString:"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAdView~1setImageView(imageView:with:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setImageView:withUrlString:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAdView~1squareImgeView\/title","value":"squareImgeView"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAdView~1squareImgeView\/fragments","value":[{"kind":"identifier","text":"squareImgeView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAdView~1bodyLabel\/title","value":"bodyLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAdView~1bodyLabel\/fragments","value":[{"kind":"identifier","text":"bodyLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAdView\/title","value":"TADNativeAdView"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAdView\/fragments","value":[{"kind":"identifier","text":"TADNativeAdView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAdView~1shortSubjectLabel\/title","value":"shortSubjectLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAdView~1shortSubjectLabel\/fragments","value":[{"kind":"identifier","text":"shortSubjectLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAdView~1init(coder:)\/title","value":"initWithCoder:"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAdView~1init(coder:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAdView~1nativeAd\/title","value":"nativeAd"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAdView~1nativeAd\/fragments","value":[{"kind":"identifier","text":"nativeAd"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAdView~1callToActionView\/title","value":"callToActionView"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAdView~1callToActionView\/fragments","value":[{"kind":"identifier","text":"callToActionView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAdView~1removeFriendlyObstruction(view:)\/title","value":"removeFriendlyObstructionWithView:"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAdView~1removeFriendlyObstruction(view:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeFriendlyObstructionWithView:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAdView~1longSubjectLabel\/title","value":"longSubjectLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAdView~1longSubjectLabel\/fragments","value":[{"kind":"identifier","text":"longSubjectLabel"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}