{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADNativeAdDelegate"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/tamediaadsframework\/tadnativeaddelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/tamediaadsframework\/tadnativeaddelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"identifier":{"url":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdDelegate","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"用於從 TADNativeAdDelegate 接收狀態更改消息的委託，例如原生廣告請求成功\/失敗。"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADNativeAdDelegate"}],"title":"TADNativeAdDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:objc(pl)TADNativeAdDelegate","modules":[{"name":"TAMediaAdsFramework"}],"navigatorTitle":[{"kind":"identifier","text":"TADNativeAdDelegate"}]},"hierarchy":{"paths":[["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdDelegate\/nativeAd(_:didFailToReceiveAdWithError:)","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdDelegate\/nativeAdDidClick(_:)","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdDelegate\/nativeAdDidImpression(_:)","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdDelegate\/nativeAdDidReceive(_:)","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdDelegate\/nativeAdWillLeaveApplication(_:)"]}],"references":{"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADNativeAdDelegate/nativeAd(_:didFailToReceiveAdWithError:)":{"navigatorTitle":[{"kind":"identifier","text":"nativeAd:didFailToReceiveAdWithError:"}],"role":"symbol","title":"nativeAd(_:didFailToReceiveAdWithError:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"nativeAd"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"TADNativeAd","preciseIdentifier":"c:objc(cs)TADNativeAd"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"didFailToReceiveAdWithError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TADRequestError","preciseIdentifier":"c:objc(cs)TADRequestError"},{"kind":"text","text":"!)"}],"abstract":[{"type":"text","text":"請求廣告失敗"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdDelegate\/nativeAd(_:didFailToReceiveAdWithError:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/tamediaadsframework\/tadnativeaddelegate\/nativead(_:didfailtoreceiveadwitherror:)"},"doc://com.taiwanmobile.TAMediaAdsFramework/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)NSObject"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework":{"role":"collection","title":"TAMediaAdsFramework","abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","kind":"symbol","type":"topic","url":"\/documentation\/tamediaadsframework"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADNativeAdDelegate/nativeAdDidClick(_:)":{"navigatorTitle":[{"kind":"identifier","text":"nativeAdDidClick:"}],"role":"symbol","title":"nativeAdDidClick(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"nativeAdDidClick"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"TADNativeAd","preciseIdentifier":"c:objc(cs)TADNativeAd"},{"kind":"text","text":"!)"}],"abstract":[{"type":"text","text":"點按廣告時觸發"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdDelegate\/nativeAdDidClick(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/tamediaadsframework\/tadnativeaddelegate\/nativeaddidclick(_:)"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADNativeAdDelegate/nativeAdWillLeaveApplication(_:)":{"navigatorTitle":[{"kind":"identifier","text":"nativeAdWillLeaveApplication:"}],"role":"symbol","title":"nativeAdWillLeaveApplication(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"nativeAdWillLeaveApplication"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"TADNativeAd","preciseIdentifier":"c:objc(cs)TADNativeAd"},{"kind":"text","text":"!)"}],"abstract":[{"type":"text","text":"在應用程序將進入後台或終止之前發送，因為用戶點擊的廣告將啟動另一個應用程序（例如AppStore）。"},{"type":"text","text":" "},{"type":"text","text":"將比普通的 UIApplicationDelegate 方法早調用，比如applicationDidEnterBackground"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdDelegate\/nativeAdWillLeaveApplication(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/tamediaadsframework\/tadnativeaddelegate\/nativeadwillleaveapplication(_:)"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADNativeAdDelegate/nativeAdDidImpression(_:)":{"navigatorTitle":[{"kind":"identifier","text":"nativeAdDidImpression:"}],"role":"symbol","title":"nativeAdDidImpression(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"nativeAdDidImpression"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"TADNativeAd","preciseIdentifier":"c:objc(cs)TADNativeAd"},{"kind":"text","text":"!)"}],"abstract":[{"type":"text","text":"廣告有效曝光時觸發"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdDelegate\/nativeAdDidImpression(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/tamediaadsframework\/tadnativeaddelegate\/nativeaddidimpression(_:)"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADNativeAdDelegate":{"role":"symbol","title":"TADNativeAdDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADNativeAdDelegate"}],"abstract":[{"type":"text","text":"用於從 TADNativeAdDelegate 接收狀態更改消息的委託，例如原生廣告請求成功\/失敗。"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TADNativeAdDelegate"}],"url":"\/documentation\/tamediaadsframework\/tadnativeaddelegate"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADNativeAdDelegate/nativeAdDidReceive(_:)":{"navigatorTitle":[{"kind":"identifier","text":"nativeAdDidReceiveAd:"}],"role":"symbol","title":"nativeAdDidReceive(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"nativeAdDidReceive"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"TADNativeAd","preciseIdentifier":"c:objc(cs)TADNativeAd"},{"kind":"text","text":"!)"}],"abstract":[{"type":"text","text":"請求廣告成功"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdDelegate\/nativeAdDidReceive(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/tamediaadsframework\/tadnativeaddelegate\/nativeaddidreceive(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"TADNativeAdDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"TADNativeAdDelegate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"TADNativeAdDelegate"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdDelegate\/nativeAd(_:didFailToReceiveAdWithError:)","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdDelegate\/nativeAdDidClick(_:)","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdDelegate\/nativeAdDidImpression(_:)","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdDelegate\/nativeAdDidReceive(_:)","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdDelegate\/nativeAdWillLeaveApplication(_:)"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADNativeAdDelegate"},{"kind":"text","text":"<"},{"kind":"keyword","text":"NSObject"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAdDelegate~1nativeAd(_:didFailToReceiveAdWithError:)\/title","value":"nativeAd:didFailToReceiveAdWithError:"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAdDelegate~1nativeAd(_:didFailToReceiveAdWithError:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"nativeAd:didFailToReceiveAdWithError:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAdDelegate~1nativeAdDidClick(_:)\/title","value":"nativeAdDidClick:"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAdDelegate~1nativeAdDidClick(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"nativeAdDidClick:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAdDelegate~1nativeAdWillLeaveApplication(_:)\/title","value":"nativeAdWillLeaveApplication:"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAdDelegate~1nativeAdWillLeaveApplication(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"nativeAdWillLeaveApplication:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAdDelegate~1nativeAdDidImpression(_:)\/title","value":"nativeAdDidImpression:"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAdDelegate~1nativeAdDidImpression(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"nativeAdDidImpression:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAdDelegate\/title","value":"TADNativeAdDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAdDelegate\/fragments","value":[{"kind":"identifier","text":"TADNativeAdDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAdDelegate~1nativeAdDidReceive(_:)\/title","value":"nativeAdDidReceiveAd:"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAdDelegate~1nativeAdDidReceive(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"nativeAdDidReceiveAd:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}