{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADNativeAdContent"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/tamediaadsframework\/tadnativeadcontent"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/tamediaadsframework\/tadnativeadcontent"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)NSObject","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/s7CVarArgP","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/s28CustomDebugStringConvertibleP","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/s23CustomStringConvertibleP","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/Se","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/SE","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/SQ","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdContent","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"封裝 native 廣告的物件"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADNativeAdContent"}],"title":"TADNativeAdContent","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@TAMediaAdsFramework@objc(cs)TADNativeAdContent","modules":[{"name":"TAMediaAdsFramework"}],"navigatorTitle":[{"kind":"identifier","text":"TADNativeAdContent"}]},"hierarchy":{"paths":[["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdContent\/init(from:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdContent\/body","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdContent\/callToAction","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdContent\/iconRect","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdContent\/iconSquare","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdContent\/longSubject","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdContent\/mediaContent","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdContent\/shortSubject"]}],"references":{"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADNativeAdContent/longSubject":{"role":"symbol","title":"longSubject","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"longSubject"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"長標題 long subject, ※預設值為空字串"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdContent\/longSubject","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"longSubject"}],"url":"\/documentation\/tamediaadsframework\/tadnativeadcontent\/longsubject"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADNativeAdContent":{"role":"symbol","title":"TADNativeAdContent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADNativeAdContent"}],"abstract":[{"type":"text","text":"封裝 native 廣告的物件"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdContent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TADNativeAdContent"}],"url":"\/documentation\/tamediaadsframework\/tadnativeadcontent"},"doc://com.taiwanmobile.TAMediaAdsFramework/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/s7CVarArgP"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADNativeAdContent/shortSubject":{"role":"symbol","title":"shortSubject","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shortSubject"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"短標題 short subject, ※預設值為空字串"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdContent\/shortSubject","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"shortSubject"}],"url":"\/documentation\/tamediaadsframework\/tadnativeadcontent\/shortsubject"},"doc://com.taiwanmobile.TAMediaAdsFramework/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/SQ"},"doc://com.taiwanmobile.TAMediaAdsFramework/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(cs)NSObject"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADNativeAdContent/mediaContent":{"role":"symbol","title":"mediaContent","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mediaContent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TADNativeAdMediaContent","preciseIdentifier":"c:@M@TAMediaAdsFramework@objc(cs)TADNativeAdMediaContent"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"原生廣告的 media 物件, 其中包含圖片和影片"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdContent\/mediaContent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"mediaContent"}],"url":"\/documentation\/tamediaadsframework\/tadnativeadcontent\/mediacontent"},"doc://com.taiwanmobile.TAMediaAdsFramework/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)NSObject"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADNativeAdContent/callToAction":{"role":"symbol","title":"callToAction","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"callToAction"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"外開廣告網頁的文字, ※預設值為空字串"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdContent\/callToAction","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"callToAction"}],"url":"\/documentation\/tamediaadsframework\/tadnativeadcontent\/calltoaction"},"doc://com.taiwanmobile.TAMediaAdsFramework/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/SE"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADNativeAdContent/new":{"role":"symbol","title":"new","fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"new"}],"abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdContent\/new","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"new"}],"url":"\/documentation\/tamediaadsframework\/tadnativeadcontent\/new"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADNativeAdContent/body":{"role":"symbol","title":"body","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"body"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"內文 body, ※預設值為空字串"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdContent\/body","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"body"}],"url":"\/documentation\/tamediaadsframework\/tadnativeadcontent\/body"},"doc://com.taiwanmobile.TAMediaAdsFramework/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/s23CustomStringConvertibleP"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADNativeAdContent/iconSquare":{"role":"symbol","title":"iconSquare","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"iconSquare"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TADNativeAdImage","preciseIdentifier":"c:@M@TAMediaAdsFramework@objc(cs)TADNativeAdImage"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"小圖示 方 icon square, ※預設值為空字串"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdContent\/iconSquare","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"iconSquare"}],"url":"\/documentation\/tamediaadsframework\/tadnativeadcontent\/iconsquare"},"doc://com.taiwanmobile.TAMediaAdsFramework/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/s28CustomDebugStringConvertibleP"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADNativeAdContent/init(from:)":{"role":"symbol","title":"init(from:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Decoder","preciseIdentifier":"s:s7DecoderP"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdContent\/init(from:)","kind":"symbol","type":"topic","url":"\/documentation\/tamediaadsframework\/tadnativeadcontent\/init(from:)"},"doc://com.taiwanmobile.TAMediaAdsFramework/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/Se"},"doc://com.taiwanmobile.TAMediaAdsFramework/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/SH"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework":{"role":"collection","title":"TAMediaAdsFramework","abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","kind":"symbol","type":"topic","url":"\/documentation\/tamediaadsframework"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADNativeAdContent/iconRect":{"role":"symbol","title":"iconRect","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"iconRect"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TADNativeAdImage","preciseIdentifier":"c:@M@TAMediaAdsFramework@objc(cs)TADNativeAdImage"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"小圖示 長 icon rectangle, ※預設值為空字串"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdContent\/iconRect","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"iconRect"}],"url":"\/documentation\/tamediaadsframework\/tadnativeadcontent\/iconrect"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"TADNativeAdContent"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"TADNativeAdContent"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"TADNativeAdContent"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdContent\/body","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdContent\/callToAction","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdContent\/iconRect","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdContent\/iconSquare","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdContent\/longSubject","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdContent\/mediaContent","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdContent\/shortSubject"]},{"title":"Type Methods","identifiers":["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADNativeAdContent\/new"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADNativeAdContent"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAdContent~1longSubject\/title","value":"longSubject"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAdContent~1longSubject\/fragments","value":[{"kind":"identifier","text":"longSubject"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAdContent\/title","value":"TADNativeAdContent"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAdContent\/fragments","value":[{"kind":"identifier","text":"TADNativeAdContent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAdContent~1shortSubject\/title","value":"shortSubject"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAdContent~1shortSubject\/fragments","value":[{"kind":"identifier","text":"shortSubject"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAdContent~1mediaContent\/title","value":"mediaContent"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAdContent~1mediaContent\/fragments","value":[{"kind":"identifier","text":"mediaContent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAdContent~1callToAction\/title","value":"callToAction"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAdContent~1callToAction\/fragments","value":[{"kind":"identifier","text":"callToAction"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAdContent~1body\/title","value":"body"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAdContent~1body\/fragments","value":[{"kind":"identifier","text":"body"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAdContent~1iconSquare\/title","value":"iconSquare"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAdContent~1iconSquare\/fragments","value":[{"kind":"identifier","text":"iconSquare"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAdContent~1iconRect\/title","value":"iconRect"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADNativeAdContent~1iconRect\/fragments","value":[{"kind":"identifier","text":"iconRect"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}