{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADResponse"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/tamediaadsframework\/tadresponse"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/tamediaadsframework\/tadresponse"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)NSObject","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/s7CVarArgP","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/s28CustomDebugStringConvertibleP","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/s23CustomStringConvertibleP","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/SQ","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/init(params:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/adClickValidTime","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/adDictionary","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/adHasDuration","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/adNad","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/adParameters","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/adPlanID","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/adQuestion","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/adQuestionId","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/adReload_repeat","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/adReload_second","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/adSH","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/adSW","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/adSubScribeID","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/adSubType","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/adText","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/adType","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/clickURL","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/dimpUrl","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/duration","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/expandURL","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/impPercent","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/impSec","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/impUrl","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/isOMEnable","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/loadURL","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/mraidUrl","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/omsdk","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/partnerCustomData","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/partnerName","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/partnerVersion","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/priceMode","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/providers","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/slotFlag","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/targetURL","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/trackingData","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/trackingUrl","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/videoComplete","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/videoFirstQuartile","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/videoImpSec","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/videoMidpoint","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/videoMute","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/videoPause","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/videoReportUrl","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/videoResume","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/videoStart","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/videoThirdQuartile","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/videoURL","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/videoUnMute"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/getADType()","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/getPartnerInfo()","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/parse()","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/parseReturnCode()"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADResponse"}],"title":"TADResponse","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)TADResponse","modules":[{"name":"TAMediaAdsFramework"}],"navigatorTitle":[{"kind":"identifier","text":"TADResponse"}]},"hierarchy":{"paths":[["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework"]]},"references":{"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADResponse/adSH":{"role":"symbol","title":"adSH","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"adSH"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/adSH","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"adSH"}],"url":"\/documentation\/tamediaadsframework\/tadresponse\/adsh"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADResponse/adHasDuration":{"role":"symbol","title":"adHasDuration","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"adHasDuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/adHasDuration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"adHasDuration"}],"url":"\/documentation\/tamediaadsframework\/tadresponse\/adhasduration"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADResponse/parse()":{"role":"symbol","title":"parse()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"parse"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/parse()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"parse"}],"url":"\/documentation\/tamediaadsframework\/tadresponse\/parse()"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADResponse/adSubScribeID":{"role":"symbol","title":"adSubScribeID","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"adSubScribeID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/adSubScribeID","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"adSubScribeID"}],"url":"\/documentation\/tamediaadsframework\/tadresponse\/adsubscribeid"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADResponse/videoUnMute":{"role":"symbol","title":"videoUnMute","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoUnMute"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/videoUnMute","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"videoUnMute"}],"url":"\/documentation\/tamediaadsframework\/tadresponse\/videounmute"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADResponse/adReload_repeat":{"role":"symbol","title":"adReload_repeat","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"adReload_repeat"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/adReload_repeat","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"adReload_repeat"}],"url":"\/documentation\/tamediaadsframework\/tadresponse\/adreload_repeat"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADResponse/adSW":{"role":"symbol","title":"adSW","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"adSW"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/adSW","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"adSW"}],"url":"\/documentation\/tamediaadsframework\/tadresponse\/adsw"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADResponse/getPartnerInfo()":{"role":"symbol","title":"getPartnerInfo()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getPartnerInfo"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"TADPartnerInfo","preciseIdentifier":"c:objc(cs)TADPartnerInfo"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/getPartnerInfo()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getPartnerInfo"}],"url":"\/documentation\/tamediaadsframework\/tadresponse\/getpartnerinfo()"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADResponse/init(params:)":{"role":"symbol","title":"init(params:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"!("},{"kind":"externalParam","text":"params"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]!)"}],"abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/init(params:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithParams:"}],"url":"\/documentation\/tamediaadsframework\/tadresponse\/init(params:)"},"doc://com.taiwanmobile.TAMediaAdsFramework/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/s7CVarArgP"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADResponse/videoMidpoint":{"role":"symbol","title":"videoMidpoint","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoMidpoint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/videoMidpoint","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"videoMidpoint"}],"url":"\/documentation\/tamediaadsframework\/tadresponse\/videomidpoint"},"doc://com.taiwanmobile.TAMediaAdsFramework/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/s28CustomDebugStringConvertibleP"},"doc://com.taiwanmobile.TAMediaAdsFramework/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/SH"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADResponse/impPercent":{"role":"symbol","title":"impPercent","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"impPercent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/impPercent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"impPercent"}],"url":"\/documentation\/tamediaadsframework\/tadresponse\/imppercent"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADResponse/impSec":{"role":"symbol","title":"impSec","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"impSec"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/impSec","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"impSec"}],"url":"\/documentation\/tamediaadsframework\/tadresponse\/impsec"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADResponse":{"role":"symbol","title":"TADResponse","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADResponse"}],"abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TADResponse"}],"url":"\/documentation\/tamediaadsframework\/tadresponse"},"doc://com.taiwanmobile.TAMediaAdsFramework/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/SQ"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADResponse/adReload_second":{"role":"symbol","title":"adReload_second","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"adReload_second"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/adReload_second","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"adReload_second"}],"url":"\/documentation\/tamediaadsframework\/tadresponse\/adreload_second"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADResponse/priceMode":{"role":"symbol","title":"priceMode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"priceMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/priceMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"priceMode"}],"url":"\/documentation\/tamediaadsframework\/tadresponse\/pricemode"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADResponse/isOMEnable":{"role":"symbol","title":"isOMEnable","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isOMEnable"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/isOMEnable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isOMEnable"}],"url":"\/documentation\/tamediaadsframework\/tadresponse\/isomenable"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADResponse/trackingUrl":{"role":"symbol","title":"trackingUrl","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackingUrl"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]!"}],"abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/trackingUrl","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"trackingUrl"}],"url":"\/documentation\/tamediaadsframework\/tadresponse\/trackingurl"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADResponse/adType":{"role":"symbol","title":"adType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"adType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/adType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"adType"}],"url":"\/documentation\/tamediaadsframework\/tadresponse\/adtype"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADResponse/providers":{"role":"symbol","title":"providers","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"providers"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]!"}],"abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/providers","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"providers"}],"url":"\/documentation\/tamediaadsframework\/tadresponse\/providers"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADResponse/videoImpSec":{"role":"symbol","title":"videoImpSec","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoImpSec"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/videoImpSec","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"videoImpSec"}],"url":"\/documentation\/tamediaadsframework\/tadresponse\/videoimpsec"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADResponse/adDictionary":{"role":"symbol","title":"adDictionary","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"adDictionary"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]!"}],"abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/adDictionary","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"adDictionary"}],"url":"\/documentation\/tamediaadsframework\/tadresponse\/addictionary"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADResponse/videoReportUrl":{"role":"symbol","title":"videoReportUrl","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoReportUrl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/videoReportUrl","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"videoReportUrl"}],"url":"\/documentation\/tamediaadsframework\/tadresponse\/videoreporturl"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADResponse/adParameters":{"role":"symbol","title":"adParameters","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"adParameters"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]!"}],"abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/adParameters","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"adParameters"}],"url":"\/documentation\/tamediaadsframework\/tadresponse\/adparameters"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADResponse/clickURL":{"role":"symbol","title":"clickURL","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"clickURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/clickURL","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"clickURL"}],"url":"\/documentation\/tamediaadsframework\/tadresponse\/clickurl"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADResponse/adPlanID":{"role":"symbol","title":"adPlanID","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"adPlanID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/adPlanID","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"adPlanID"}],"url":"\/documentation\/tamediaadsframework\/tadresponse\/adplanid"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADResponse/adText":{"role":"symbol","title":"adText","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"adText"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/adText","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"adText"}],"url":"\/documentation\/tamediaadsframework\/tadresponse\/adtext"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADResponse/omsdk":{"role":"symbol","title":"omsdk","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"omsdk"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]!"}],"abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/omsdk","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OMSDK"}],"url":"\/documentation\/tamediaadsframework\/tadresponse\/omsdk"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADResponse/duration":{"role":"symbol","title":"duration","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"duration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/duration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"duration"}],"url":"\/documentation\/tamediaadsframework\/tadresponse\/duration"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADResponse/adClickValidTime":{"role":"symbol","title":"adClickValidTime","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"adClickValidTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/adClickValidTime","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"adClickValidTime"}],"url":"\/documentation\/tamediaadsframework\/tadresponse\/adclickvalidtime"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADResponse/adQuestionId":{"role":"symbol","title":"adQuestionId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"adQuestionId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/adQuestionId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"adQuestionId"}],"url":"\/documentation\/tamediaadsframework\/tadresponse\/adquestionid"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADResponse/loadURL":{"role":"symbol","title":"loadURL","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/loadURL","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"loadURL"}],"url":"\/documentation\/tamediaadsframework\/tadresponse\/loadurl"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADResponse/videoPause":{"role":"symbol","title":"videoPause","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoPause"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/videoPause","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"videoPause"}],"url":"\/documentation\/tamediaadsframework\/tadresponse\/videopause"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADResponse/videoResume":{"role":"symbol","title":"videoResume","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoResume"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/videoResume","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"videoResume"}],"url":"\/documentation\/tamediaadsframework\/tadresponse\/videoresume"},"doc://com.taiwanmobile.TAMediaAdsFramework/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/s23CustomStringConvertibleP"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADResponse/partnerVersion":{"role":"symbol","title":"partnerVersion","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"partnerVersion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/partnerVersion","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"partnerVersion"}],"url":"\/documentation\/tamediaadsframework\/tadresponse\/partnerversion"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADResponse/adQuestion":{"role":"symbol","title":"adQuestion","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"adQuestion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/adQuestion","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"adQuestion"}],"url":"\/documentation\/tamediaadsframework\/tadresponse\/adquestion"},"doc://com.taiwanmobile.TAMediaAdsFramework/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(pl)NSObject"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADResponse/videoMute":{"role":"symbol","title":"videoMute","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoMute"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/videoMute","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"videoMute"}],"url":"\/documentation\/tamediaadsframework\/tadresponse\/videomute"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADResponse/partnerName":{"role":"symbol","title":"partnerName","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"partnerName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/partnerName","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"partnerName"}],"url":"\/documentation\/tamediaadsframework\/tadresponse\/partnername"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADResponse/adSubType":{"role":"symbol","title":"adSubType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"adSubType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/adSubType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"adSubType"}],"url":"\/documentation\/tamediaadsframework\/tadresponse\/adsubtype"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADResponse/trackingData":{"role":"symbol","title":"trackingData","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackingData"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]!"}],"abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/trackingData","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"trackingData"}],"url":"\/documentation\/tamediaadsframework\/tadresponse\/trackingdata"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADResponse/videoURL":{"role":"symbol","title":"videoURL","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/videoURL","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"videoURL"}],"url":"\/documentation\/tamediaadsframework\/tadresponse\/videourl"},"doc://com.taiwanmobile.TAMediaAdsFramework/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/objc(cs)NSObject"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADResponse/expandURL":{"role":"symbol","title":"expandURL","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"expandURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/expandURL","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"expandURL"}],"url":"\/documentation\/tamediaadsframework\/tadresponse\/expandurl"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADResponse/videoFirstQuartile":{"role":"symbol","title":"videoFirstQuartile","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoFirstQuartile"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/videoFirstQuartile","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"videoFirstQuartile"}],"url":"\/documentation\/tamediaadsframework\/tadresponse\/videofirstquartile"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADResponse/getADType()":{"role":"symbol","title":"getADType()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getADType"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/getADType()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getADType"}],"url":"\/documentation\/tamediaadsframework\/tadresponse\/getadtype()"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADResponse/parseReturnCode()":{"role":"symbol","title":"parseReturnCode()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"parseReturnCode"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/parseReturnCode()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"parseReturnResponseCode"}],"url":"\/documentation\/tamediaadsframework\/tadresponse\/parsereturncode()"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADResponse/targetURL":{"role":"symbol","title":"targetURL","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"targetURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/targetURL","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"targetURL"}],"url":"\/documentation\/tamediaadsframework\/tadresponse\/targeturl"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework":{"role":"collection","title":"TAMediaAdsFramework","abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","kind":"symbol","type":"topic","url":"\/documentation\/tamediaadsframework"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADResponse/slotFlag":{"role":"symbol","title":"slotFlag","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"slotFlag"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/slotFlag","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"slotFlag"}],"url":"\/documentation\/tamediaadsframework\/tadresponse\/slotflag"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADResponse/adNad":{"role":"symbol","title":"adNad","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"adNad"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]!"}],"abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/adNad","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"adNad"}],"url":"\/documentation\/tamediaadsframework\/tadresponse\/adnad"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADResponse/partnerCustomData":{"role":"symbol","title":"partnerCustomData","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"partnerCustomData"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]!"}],"abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/partnerCustomData","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"partnerCustomData"}],"url":"\/documentation\/tamediaadsframework\/tadresponse\/partnercustomdata"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADResponse/videoStart":{"role":"symbol","title":"videoStart","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoStart"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/videoStart","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"videoStart"}],"url":"\/documentation\/tamediaadsframework\/tadresponse\/videostart"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADResponse/videoThirdQuartile":{"role":"symbol","title":"videoThirdQuartile","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoThirdQuartile"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/videoThirdQuartile","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"videoThirdQuartile"}],"url":"\/documentation\/tamediaadsframework\/tadresponse\/videothirdquartile"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADResponse/dimpUrl":{"role":"symbol","title":"dimpUrl","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"dimpUrl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/dimpUrl","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"dimpUrl"}],"url":"\/documentation\/tamediaadsframework\/tadresponse\/dimpurl"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADResponse/impUrl":{"role":"symbol","title":"impUrl","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"impUrl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/impUrl","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"impUrl"}],"url":"\/documentation\/tamediaadsframework\/tadresponse\/impurl"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADResponse/videoComplete":{"role":"symbol","title":"videoComplete","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoComplete"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/videoComplete","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"videoComplete"}],"url":"\/documentation\/tamediaadsframework\/tadresponse\/videocomplete"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADResponse/mraidUrl":{"role":"symbol","title":"mraidUrl","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mraidUrl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/mraidUrl","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"mraidUrl"}],"url":"\/documentation\/tamediaadsframework\/tadresponse\/mraidurl"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"TADResponse"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"TADResponse"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"TADResponse"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/adClickValidTime","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/adDictionary","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/adHasDuration","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/adNad","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/adParameters","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/adPlanID","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/adQuestion","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/adQuestionId","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/adReload_repeat","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/adReload_second","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/adSH","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/adSW","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/adSubScribeID","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/adSubType","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/adText","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/adType","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/clickURL","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/dimpUrl","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/duration","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/expandURL","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/impPercent","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/impSec","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/impUrl","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/isOMEnable","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/loadURL","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/mraidUrl","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/omsdk","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/partnerCustomData","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/partnerName","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/partnerVersion","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/priceMode","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/providers","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/slotFlag","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/targetURL","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/trackingData","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/trackingUrl","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/videoComplete","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/videoFirstQuartile","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/videoImpSec","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/videoMidpoint","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/videoMute","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/videoPause","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/videoReportUrl","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/videoResume","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/videoStart","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/videoThirdQuartile","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/videoURL","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/videoUnMute"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/getADType()","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/getPartnerInfo()","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/init(params:)","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/parse()","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADResponse\/parseReturnCode()"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADResponse"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1adSH\/title","value":"adSH"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1adSH\/fragments","value":[{"kind":"identifier","text":"adSH"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1adHasDuration\/title","value":"adHasDuration"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1adHasDuration\/fragments","value":[{"kind":"identifier","text":"adHasDuration"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1parse()\/title","value":"parse"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1parse()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"parse"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1adSubScribeID\/title","value":"adSubScribeID"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1adSubScribeID\/fragments","value":[{"kind":"identifier","text":"adSubScribeID"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1videoUnMute\/title","value":"videoUnMute"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1videoUnMute\/fragments","value":[{"kind":"identifier","text":"videoUnMute"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1adReload_repeat\/title","value":"adReload_repeat"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1adReload_repeat\/fragments","value":[{"kind":"identifier","text":"adReload_repeat"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1adSW\/title","value":"adSW"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1adSW\/fragments","value":[{"kind":"identifier","text":"adSW"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1getPartnerInfo()\/title","value":"getPartnerInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1getPartnerInfo()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getPartnerInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1init(params:)\/title","value":"initWithParams:"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1init(params:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithParams:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1videoMidpoint\/title","value":"videoMidpoint"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1videoMidpoint\/fragments","value":[{"kind":"identifier","text":"videoMidpoint"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1impPercent\/title","value":"impPercent"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1impPercent\/fragments","value":[{"kind":"identifier","text":"impPercent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1impSec\/title","value":"impSec"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1impSec\/fragments","value":[{"kind":"identifier","text":"impSec"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse\/title","value":"TADResponse"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse\/fragments","value":[{"kind":"identifier","text":"TADResponse"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1adReload_second\/title","value":"adReload_second"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1adReload_second\/fragments","value":[{"kind":"identifier","text":"adReload_second"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1priceMode\/title","value":"priceMode"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1priceMode\/fragments","value":[{"kind":"identifier","text":"priceMode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1isOMEnable\/title","value":"isOMEnable"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1isOMEnable\/fragments","value":[{"kind":"identifier","text":"isOMEnable"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1trackingUrl\/title","value":"trackingUrl"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1trackingUrl\/fragments","value":[{"kind":"identifier","text":"trackingUrl"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1adType\/title","value":"adType"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1adType\/fragments","value":[{"kind":"identifier","text":"adType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1providers\/title","value":"providers"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1providers\/fragments","value":[{"kind":"identifier","text":"providers"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1videoImpSec\/title","value":"videoImpSec"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1videoImpSec\/fragments","value":[{"kind":"identifier","text":"videoImpSec"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1adDictionary\/title","value":"adDictionary"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1adDictionary\/fragments","value":[{"kind":"identifier","text":"adDictionary"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1videoReportUrl\/title","value":"videoReportUrl"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1videoReportUrl\/fragments","value":[{"kind":"identifier","text":"videoReportUrl"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1adParameters\/title","value":"adParameters"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1adParameters\/fragments","value":[{"kind":"identifier","text":"adParameters"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1clickURL\/title","value":"clickURL"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1clickURL\/fragments","value":[{"kind":"identifier","text":"clickURL"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1adPlanID\/title","value":"adPlanID"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1adPlanID\/fragments","value":[{"kind":"identifier","text":"adPlanID"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1adText\/title","value":"adText"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1adText\/fragments","value":[{"kind":"identifier","text":"adText"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1omsdk\/title","value":"OMSDK"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1omsdk\/fragments","value":[{"kind":"identifier","text":"OMSDK"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1duration\/title","value":"duration"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1duration\/fragments","value":[{"kind":"identifier","text":"duration"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1adClickValidTime\/title","value":"adClickValidTime"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1adClickValidTime\/fragments","value":[{"kind":"identifier","text":"adClickValidTime"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1adQuestionId\/title","value":"adQuestionId"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1adQuestionId\/fragments","value":[{"kind":"identifier","text":"adQuestionId"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1loadURL\/title","value":"loadURL"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1loadURL\/fragments","value":[{"kind":"identifier","text":"loadURL"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1videoPause\/title","value":"videoPause"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1videoPause\/fragments","value":[{"kind":"identifier","text":"videoPause"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1videoResume\/title","value":"videoResume"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1videoResume\/fragments","value":[{"kind":"identifier","text":"videoResume"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1partnerVersion\/title","value":"partnerVersion"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1partnerVersion\/fragments","value":[{"kind":"identifier","text":"partnerVersion"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1adQuestion\/title","value":"adQuestion"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1adQuestion\/fragments","value":[{"kind":"identifier","text":"adQuestion"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1videoMute\/title","value":"videoMute"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1videoMute\/fragments","value":[{"kind":"identifier","text":"videoMute"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1partnerName\/title","value":"partnerName"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1partnerName\/fragments","value":[{"kind":"identifier","text":"partnerName"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1adSubType\/title","value":"adSubType"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1adSubType\/fragments","value":[{"kind":"identifier","text":"adSubType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1trackingData\/title","value":"trackingData"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1trackingData\/fragments","value":[{"kind":"identifier","text":"trackingData"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1videoURL\/title","value":"videoURL"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1videoURL\/fragments","value":[{"kind":"identifier","text":"videoURL"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1expandURL\/title","value":"expandURL"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1expandURL\/fragments","value":[{"kind":"identifier","text":"expandURL"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1videoFirstQuartile\/title","value":"videoFirstQuartile"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1videoFirstQuartile\/fragments","value":[{"kind":"identifier","text":"videoFirstQuartile"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1getADType()\/title","value":"getADType"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1getADType()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getADType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1parseReturnCode()\/title","value":"parseReturnResponseCode"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1parseReturnCode()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"parseReturnResponseCode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1targetURL\/title","value":"targetURL"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1targetURL\/fragments","value":[{"kind":"identifier","text":"targetURL"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1slotFlag\/title","value":"slotFlag"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1slotFlag\/fragments","value":[{"kind":"identifier","text":"slotFlag"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1adNad\/title","value":"adNad"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1adNad\/fragments","value":[{"kind":"identifier","text":"adNad"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1partnerCustomData\/title","value":"partnerCustomData"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1partnerCustomData\/fragments","value":[{"kind":"identifier","text":"partnerCustomData"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1videoStart\/title","value":"videoStart"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1videoStart\/fragments","value":[{"kind":"identifier","text":"videoStart"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1videoThirdQuartile\/title","value":"videoThirdQuartile"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1videoThirdQuartile\/fragments","value":[{"kind":"identifier","text":"videoThirdQuartile"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1dimpUrl\/title","value":"dimpUrl"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1dimpUrl\/fragments","value":[{"kind":"identifier","text":"dimpUrl"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1impUrl\/title","value":"impUrl"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1impUrl\/fragments","value":[{"kind":"identifier","text":"impUrl"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1videoComplete\/title","value":"videoComplete"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1videoComplete\/fragments","value":[{"kind":"identifier","text":"videoComplete"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1mraidUrl\/title","value":"mraidUrl"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADResponse~1mraidUrl\/fragments","value":[{"kind":"identifier","text":"mraidUrl"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}