{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"anchorUserPressedCloseAd"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/tamediaadsframework\/tadinreadanchordelegate\/anchoruserpressedclosead()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/tamediaadsframework\/tadinreadanchordelegate\/anchoruserpressedclosead()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInReadAnchorDelegate\/anchorUserPressedCloseAd()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"使用者點按關閉廣告"}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"anchorUserPressedCloseAd"}],"role":"symbol","title":"anchorUserPressedCloseAd()","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"anchorUserPressedCloseAd"},{"kind":"text","text":"()"}],"symbolKind":"method","externalID":"c:objc(pl)TADInReadAnchorDelegate(im)anchorUserPressedCloseAd","required":true,"modules":[{"name":"TAMediaAdsFramework"}]},"hierarchy":{"paths":[["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInReadAnchorDelegate"]]},"references":{"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADInReadAnchorDelegate/anchorUserPressedCloseAd()":{"navigatorTitle":[{"kind":"identifier","text":"anchorUserPressedCloseAd"}],"role":"symbol","title":"anchorUserPressedCloseAd()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"anchorUserPressedCloseAd"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"使用者點按關閉廣告"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInReadAnchorDelegate\/anchorUserPressedCloseAd()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/tamediaadsframework\/tadinreadanchordelegate\/anchoruserpressedclosead()"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework":{"role":"collection","title":"TAMediaAdsFramework","abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","kind":"symbol","type":"topic","url":"\/documentation\/tamediaadsframework"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADInReadAnchorDelegate":{"role":"symbol","title":"TADInReadAnchorDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADInReadAnchorDelegate"}],"abstract":[{"type":"text","text":"用於從 TADInReadAnchor 接收狀態更改消息的委託，例如廣告請求成功\/失敗或點擊廣告時。"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADInReadAnchorDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TADInReadAnchorDelegate"}],"url":"\/documentation\/tamediaadsframework\/tadinreadanchordelegate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"anchorUserPressedCloseAd"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"anchorUserPressedCloseAd"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"anchorUserPressedCloseAd"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADInReadAnchorDelegate~1anchorUserPressedCloseAd()\/title","value":"anchorUserPressedCloseAd"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADInReadAnchorDelegate~1anchorUserPressedCloseAd()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"anchorUserPressedCloseAd"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADInReadAnchorDelegate\/title","value":"TADInReadAnchorDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADInReadAnchorDelegate\/fragments","value":[{"kind":"identifier","text":"TADInReadAnchorDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}