{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"osVersionTooLow"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/tamediaadsframework\/taderrorcode\/osversiontoolow"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/tamediaadsframework\/taderrorcode\/osversiontoolow"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADErrorCode\/osVersionTooLow","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"當前設備的操作系統低於最低要求版本。"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"osVersionTooLow"}],"title":"TADErrorCode.osVersionTooLow","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@TADErrorCode@kTADErrorOSVersionTooLow","modules":[{"name":"TAMediaAdsFramework"}],"navigatorTitle":[{"kind":"identifier","text":"kTADErrorOSVersionTooLow"}]},"hierarchy":{"paths":[["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADErrorCode"]]},"references":{"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADErrorCode":{"role":"symbol","title":"TADErrorCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADErrorCode"}],"abstract":[{"type":"text","text":"TAmedia中定義的NSError資訊"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADErrorCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TADErrorCode"}],"url":"\/documentation\/tamediaadsframework\/taderrorcode"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework":{"role":"collection","title":"TAMediaAdsFramework","abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","kind":"symbol","type":"topic","url":"\/documentation\/tamediaadsframework"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADErrorCode/osVersionTooLow":{"role":"symbol","title":"TADErrorCode.osVersionTooLow","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"osVersionTooLow"}],"abstract":[{"type":"text","text":"當前設備的操作系統低於最低要求版本。"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADErrorCode\/osVersionTooLow","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"kTADErrorOSVersionTooLow"}],"url":"\/documentation\/tamediaadsframework\/taderrorcode\/osversiontoolow"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"kTADErrorOSVersionTooLow"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"kTADErrorOSVersionTooLow"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"kTADErrorOSVersionTooLow"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADErrorCode\/title","value":"TADErrorCode"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADErrorCode\/fragments","value":[{"kind":"identifier","text":"TADErrorCode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADErrorCode~1osVersionTooLow\/title","value":"kTADErrorOSVersionTooLow"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADErrorCode~1osVersionTooLow\/fragments","value":[{"kind":"identifier","text":"kTADErrorOSVersionTooLow"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}