{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"FlagLandscape"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/tamediaadsframework\/tadadsizeflags\/flaglandscape"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/tamediaadsframework\/tadadsizeflags\/flaglandscape"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADAdSizeFlags\/FlagLandscape","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"SmartBannerLandscape"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"FlagLandscape"}],"title":"TADAdSizeFlags.FlagLandscape","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@TADAdSizeFlags@FlagLandscape","modules":[{"name":"TAMediaAdsFramework"}],"navigatorTitle":[{"kind":"identifier","text":"FlagLandscape"}]},"hierarchy":{"paths":[["doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADAdSizeFlags"]]},"references":{"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADAdSizeFlags/FlagLandscape":{"role":"symbol","title":"TADAdSizeFlags.FlagLandscape","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"FlagLandscape"}],"abstract":[{"type":"text","text":"SmartBannerLandscape"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADAdSizeFlags\/FlagLandscape","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FlagLandscape"}],"url":"\/documentation\/tamediaadsframework\/tadadsizeflags\/flaglandscape"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework":{"role":"collection","title":"TAMediaAdsFramework","abstract":[],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework","kind":"symbol","type":"topic","url":"\/documentation\/tamediaadsframework"},"doc://com.taiwanmobile.TAMediaAdsFramework/documentation/TAMediaAdsFramework/TADAdSizeFlags":{"role":"symbol","title":"TADAdSizeFlags","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"TADAdSizeFlags"}],"abstract":[{"type":"text","text":"AdSize標籤，用於分類不同廣告尺寸對應的標籤"}],"identifier":"doc:\/\/com.taiwanmobile.TAMediaAdsFramework\/documentation\/TAMediaAdsFramework\/TADAdSizeFlags","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TADAdSizeFlags"}],"url":"\/documentation\/tamediaadsframework\/tadadsizeflags"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"FlagLandscape"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"FlagLandscape"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"FlagLandscape"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADAdSizeFlags~1FlagLandscape\/title","value":"FlagLandscape"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADAdSizeFlags~1FlagLandscape\/fragments","value":[{"kind":"identifier","text":"FlagLandscape"}]},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADAdSizeFlags\/title","value":"TADAdSizeFlags"},{"op":"replace","path":"\/references\/doc:~1~1com.taiwanmobile.TAMediaAdsFramework~1documentation~1TAMediaAdsFramework~1TADAdSizeFlags\/fragments","value":[{"kind":"identifier","text":"TADAdSizeFlags"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}